HVA-WIN: appl.c File Reference
appl.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <direct.h>
#include <time.h>
#include <string.h>
#include "keys.h"
#include "video/v_video.h"
#include "window.h"
#include "fortify.h"
Defines
#define MAIN_MODULE
Functions
void do_dir (void)
void do_exit (void)
void initialize (void)
void exit_prog (void)
int main (void)
void overlap_demo (void)
void call_zapload (void)
void call_hexconv (void)
void call_terminal (void)
void intro_screen (void)
Variables
SCREEN _cursvar
float test_f = 1.0
double test_d = 2.0
char test_s [80]
int test_i = 20
int test_h = 0x15
int test_b = FALSE
MENU M_shell []
MENU M_TEST_EDIT []
MENU M_TEST_HELP []
MENU M_WINDEMO []
MENU_HEAD heads []
char error_msg [132]
Define Documentation
#define MAIN_MODULE
Definition at line 6 of file appl.c.
Function Documentation
void call_hexconv (void)
Definition at line 187 of file appl.c.
References _cursvar, _NO_BORDER, BLACK, w, WHITE, wn_close(), and wn_open().
{
  char command_str[80];
  WINDOW *w;
  /*----------------------------
    Open standard DOS window
  -----------------------------*/
  w = wn_open(_NO_BORDER,0,0,_cursvar.cols,_cursvar.lines,
              16*BLACK+WHITE,16*BLACK+WHITE);
  sprintf(command_str,"convert");
  system(command_str);
  puts("\n\nPress any key to continue ...");
  getch();
  w = wn_close(w);
}
void call_terminal (void)
Definition at line 215 of file appl.c.
References _cursvar, _NO_BORDER, BLACK, w, WHITE, wn_close(), and wn_open().
{
  char command_str[80];
  WINDOW *w;
  /*----------------------------
    Open standard DOS window
  -----------------------------*/
  w = wn_open(_NO_BORDER,0,0,_cursvar.cols,_cursvar.lines,
              16*BLACK+WHITE,16*BLACK+WHITE);
  sprintf(command_str,"%s","procomm");
  system(command_str);
  w = wn_close(w);
}
void call_zapload (void)
Definition at line 160 of file appl.c.
References _cursvar, _NO_BORDER, BLACK, w, WHITE, wn_close(), and wn_open().
{
  char command_str[80];
  WINDOW *w;
  /*----------------------------
    Open standard DOS window
  -----------------------------*/
  w = wn_open(_NO_BORDER,0,0,_cursvar.cols,_cursvar.lines,
              16*BLACK+WHITE,16*BLACK+WHITE);
  sprintf(command_str,"zapload");
  system(command_str);
  puts("\n\nPress any key to continue ...");
  getch();
  w = wn_close(w);
}
void do_dir (void)
Definition at line 367 of file appl.c.
References _DRAW, action_col, action_row, editstr(), ESC, and get_dir().
{
  char filemask[20];
  int ret;
  strcpy(filemask,"*.*");
  ret = editstr(action_row+2,action_col+2,20,"Enter file mask",filemask,_DRAW);
  if (ret != ESC)
    get_dir(filemask,filemask);
}
void do_exit (void)
Definition at line 240 of file appl.c.
{
  exit(0);
}
void exit_prog (void)
Definition at line 256 of file appl.c.
References FALSE, TRUE, and wn_exit().
Referenced by initialize().
{
   static int done = FALSE;
  if (!done)               /* Do this only once */
  {
    wn_exit();          /* Exit from HvA window enviroment          */
    done = TRUE;        /* Set flag (this routine has been executed */
  }
}
void initialize (void)
Definition at line 309 of file appl.c.
References default_subject, exit_prog(), Fortify_ListAllMemory, init_help(), and wn_init().
Referenced by main().
{
  extern char *default_subject;
  /*----------------------------------------------
    Set vector to exit_prog() if exit() is called
  ------------------------------------------------*/
  atexit(exit_prog);
  /*----------------------------
    Initilize (graphic) screen
  ----------------------------*/
  wn_init();
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
  /*-------------------------------
    Initialize help file functions
  ---------------------------------*/
  default_subject = ":general_info";
  init_help("window");
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
  /*-------------------
    Show intro screen
  --------------------*/
  /*
  intro_screen();
  */
  /*-------------------------------------
    Initialize function key's functions
  --------------------------------------*/
  /*
  init_funkey(F2,call_zapload,"Zapload");
  init_funkey(F3,call_hexconv,"HEXconv");
  init_funkey(F4,call_terminal,"Terminal");
  init_funkey(F10,OS_shell,"SHELL");
  disp_funkeys(1);
  */
}
void intro_screen (void)
Definition at line 275 of file appl.c.
References EXIT, Fortify_ListAllMemory, menu, and wn_dialog().
{
  static MENU menu[]=
  {
    {"OK",   0, NULL, NULL,        NULL, NULL, EXIT      },
  };
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
  wn_dialog(13,40,1,menu,6,
    "       WINDOW TEST        ",
    "                          ",
    "                          ",
    "  (c) H.B.J. van Asselt   ",
    "      12 OCT 1993         ",
    "");
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
}
int main (void)
Definition at line 385 of file appl.c.
References ESC, Fortify_ListAllMemory, initialize(), pulldown(), and s.
{
  int choise;
  char s[80];
  int i;
  initialize();
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
  do
  {
    choise = pulldown(heads,0,":general_info");
  }
  while (choise != ESC);
  /*--------------------
    Exit this programm
  ---------------------*/
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
  exit(0);
  return(0);
}
void overlap_demo (void)
Definition at line 98 of file appl.c.
References _DOUBLE_LINE, _NO_BORDER, _SINGLE_LINE, BLUE, CYAN, GREEN, RED, wn_close(), wn_open(), wn_printf(), and YELLOW.
{
  WINDOW *w1;
  WINDOW *w2;
  WINDOW *w3;
  WINDOW *w4;
  w1 = wn_open(_SINGLE_LINE,10,10,10,10,
               16*YELLOW+GREEN,16*YELLOW+GREEN);
  wn_printf(w1,"Window 1\n");
  getch();
  w2 = wn_open(_DOUBLE_LINE,12,12,10,10,
               16*RED+GREEN,16*RED+GREEN);
  wn_printf(w2,"Window 2\n");
  getch();
  w3 = wn_open(_NO_BORDER,14,14,10,10,
               16*BLUE+GREEN,16*BLUE+GREEN);
  wn_printf(w3,"Window 3\n");
  getch();
  w4 = wn_open(_NO_BORDER,16,16,10,10,
               16*CYAN+YELLOW,16*CYAN+YELLOW);
  wn_printf(w4,"Window 4\n");
  wn_printf(w1,"Window 1\n");
  getch();
  wn_printf(w2,"Window 2\n");
  getch();
  wn_printf(w3,"Window 3\n");
  getch();
  wn_printf(w4,"Window 4\n");
  getch();
  wn_printf(w4,"Window 4\n");
  getch();
  wn_printf(w3,"Window 3\n");
  getch();
  wn_printf(w2,"Window 2\n");
  getch();
  wn_printf(w1,"Window 1\n");
  getch();
  w4 = wn_close(w4);
  getch();
  w3 = wn_close(w3);
  getch();
  w2 = wn_close(w2);
  getch();
  w1 = wn_close(w1);
}
Variable Documentation
SCREEN _cursvar
Referenced by call_hexconv(), call_terminal(), call_zapload(), disp_funkeys(), disp_status(), editstr(), help(), OS_shell(), show_bar(), show_time(), wn_debug(), wn_desktop(), wn_init(), wn_move(), wn_open(), wn_shadow(), and wn_shell().
char error_msg[132]
Definition at line 89 of file appl.c.
MENU_HEAD heads[]
Initial value:
{
  { "System",  0, 4, M_shell     },
  { "Edit",    0, 5, M_TEST_EDIT },
  { "Help",    0, 7, M_TEST_HELP },
  { "Window_demo", 0, 1, M_WINDEMO },
  { NULL }
}
Definition at line 77 of file appl.c.
MENU M_shell[]
Initial value:
{
  { "Directory ", 0, do_dir,     "", NULL, NULL, },
  { "Change dir", 0, change_dir, "", NULL, NULL, },
  { "OS shell  ", 0, OS_shell,   "", NULL, NULL, },
  { "Exit      ", 0, do_exit,    "", NULL, NULL, },
  { NULL }
}
Definition at line 45 of file appl.c.
MENU M_TEST_EDIT[]
Initial value:
{
  { "Edit float   ", 5, NULL, "",  &test_f, "%.3f"  ,EDIT_STR },
  { "Edit double  ", 5, NULL, "",  &test_d, "%.6lf" ,EDIT_STR },
  { "Edit string  ", 5, NULL, "",  test_s,  "%s"    ,EDIT_STR },
  { "Edit Integer ", 5, NULL, "",  &test_i, "%d"    ,EDIT_STR },
  { "Edit Hex     ", 5, NULL, "",  &test_h, "%x"    ,EDIT_STR },
  { "Edit Boolean ", 5, NULL, "",  &test_b, "%B"    ,SELECTABLE },
  { NULL }
}
Definition at line 54 of file appl.c.
MENU M_TEST_HELP[]
Initial value:
{
  { " Window functions", -1, NULL, "window functions",      NULL, NULL, HELP_ONLY },
  {NULL}
}
Definition at line 65 of file appl.c.
MENU M_WINDEMO[]
Initial value:
{
  { "Demo", 0, overlap_demo, "overlap demo", NULL, NULL, NO_FLAGS},
  { NULL }
}
Definition at line 71 of file appl.c.
int test_b = FALSE
Definition at line 42 of file appl.c.
double test_d = 2.0
Definition at line 38 of file appl.c.
float test_f = 1.0
Definition at line 37 of file appl.c.
int test_h = 0x15
Definition at line 41 of file appl.c.
int test_i = 20
Definition at line 40 of file appl.c.
char test_s[80]
Definition at line 39 of file appl.c.