HVA-WIN: funkey.c File Reference
funkey.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <ctype.h>
#include <dos.h>
#include <string.h>
#include <stdarg.h>
#include "keys.h"
#include "video/v_video.h"
#include "window.h"
Data Structures
struct FUNCTION_HANDLER
Functions
static int func_index (int function_key)
void init_funkey (int function_key, void *function, char *text)
int do_funkey (int key)
void disp_funkeys (int i)
void exit_funkey ()
Variables
SCREEN _cursvar
static WINDOW * w = NULL
static FUNCTION_HANDLER funkey [40]
static int show_funkeys = FALSE
Function Documentation
void disp_funkeys (int i)
Definition at line 205 of file funkey.c.
References _cursvar, _menu_att, _menu_hotkey, _NO_BORDER, col, FALSE, row, show_funkeys, TRUE, wn_clear(), wn_hide(), wn_locate(), wn_log(), wn_open(), wn_printf(), wn_setone(), and wn_unhide().
{
  int j;
  int row,col;
  show_funkeys = TRUE;
  if (i<0 || i>4)
  {
    wn_log("wrong index %d in disp_funkeys\n",i);
    i = 1;
  }
  /*--------------------------------------
    Check if we have to open a window for
    the function keys, or if this window
    has already been opened.
    The window will occupy the last row on
    the screen with a full length
  ----------------------------------------*/
  if (!w)
  {
    wn_log("*** START FUNKEY\n");
    w = wn_open(_NO_BORDER,_cursvar.lines,0,_cursvar.cols+1,1,_menu_att,_menu_att);
    wn_clear(w);
  }
  /*------------------------------------------------
    Check if user wants to hide function key labels
    or to display it
  --------------------------------------------------*/
  if (i==0)
  {
    show_funkeys = FALSE;
    wn_hide(w);
    return;
  }
  else {
    if (show_funkeys == FALSE) {
      show_funkeys = TRUE;
      if (w)
        wn_unhide(w);
    }
  }
  /*-------------------------
    Print the function keys
  --------------------------*/
  row = 0;
  col = 0;
  for (j = 0 ; j<10 ; j++)
  {
    wn_locate(w,row,col);
    if (funkey[j].text) {
      wn_printf(w,"%1d%-6.6s",j+1,funkey[j].text);
      wn_setone(w,row,col,_menu_hotkey);
      if (j==9)
       wn_setone(w,row,col+1,_menu_hotkey);
    }
    col+=7;
  }
}
int do_funkey (int key)
Definition at line 173 of file funkey.c.
References func_index(), is_fkey(), and wn_log().
Referenced by popup(), and pulldown().
{
  int ndx;
  wn_log("do_funkey(key=%2d)\n");
  if (is_fkey(key)) {
    ndx = func_index(key);                /* Find array index       */
    if (funkey[ndx].function) {           /* If function defined    */
      (*(PFI)(funkey[ndx].function))();   /* then execute function  */
      return(0);
    }
    else
      return(key);
  }
  else
    return(key);
}
void exit_funkey (void)
Definition at line 275 of file funkey.c.
References wn_close(), and wn_log().
Referenced by wn_exit().
{
  if (w)
  {
    wn_log("*** END FUNKEY\n");
    w = wn_close(w);
  }
}
static int func_index (int function_key) [static]
Definition at line 71 of file funkey.c.
References ALT_F1, ALT_F10, ALT_F2, ALT_F3, ALT_F4, ALT_F5, ALT_F6, ALT_F7, ALT_F8, ALT_F9, CTRL_F1, CTRL_F10, CTRL_F2, CTRL_F3, CTRL_F4, CTRL_F5, CTRL_F6, CTRL_F7, CTRL_F8, CTRL_F9, F1, F10, F2, F3, F4, F5, F6, F7, F8, F9, SHIFT_F1, SHIFT_F10, SHIFT_F2, SHIFT_F3, SHIFT_F4, SHIFT_F5, SHIFT_F6, SHIFT_F7, SHIFT_F8, SHIFT_F9, and wn_error().
Referenced by do_funkey(), and init_funkey().
{
  int ndx;
  switch (function_key)
  {
    case F1:
    case F2:
    case F3:
    case F4:
    case F5:
    case F6:
    case F7:
    case F8:
    case F9:
    case F10:
      ndx = function_key-F1;
      break;
    case SHIFT_F1:
    case SHIFT_F2:
    case SHIFT_F3:
    case SHIFT_F4:
    case SHIFT_F5:
    case SHIFT_F6:
    case SHIFT_F7:
    case SHIFT_F8:
    case SHIFT_F9:
    case SHIFT_F10:
      ndx = function_key - SHIFT_F1 + 10;
      break;
    case CTRL_F1:
    case CTRL_F2:
    case CTRL_F3:
    case CTRL_F4:
    case CTRL_F5:
    case CTRL_F6:
    case CTRL_F7:
    case CTRL_F8:
    case CTRL_F9:
    case CTRL_F10:
      ndx = function_key - CTRL_F1 + 20;
      break;
    case ALT_F1:
    case ALT_F2:
    case ALT_F3:
    case ALT_F4:
    case ALT_F5:
    case ALT_F6:
    case ALT_F7:
    case ALT_F8:
    case ALT_F9:
    case ALT_F10:
      ndx = function_key - ALT_F1 + 30;
      break;
    default:
      #ifdef TESTING
        wn_error("Wrong function key %d in init_funct_Fx()",function_key);
      #endif
      return(-1);
  }
  return(ndx);
}
void init_funkey (int function_key, void * function, char * text)
Definition at line 146 of file funkey.c.
References func_index(), FUNCTION_HANDLER::function, FUNCTION_HANDLER::text, and wn_log().
{
  int ndx;
  wn_log("init_funkey(key=%d,function=%p,text=%s\n",
    function_key, function, text);
  /*-------------------------------
    Initialize funkey[] variables
  ---------------------------------*/
  ndx = func_index(function_key);       /* Calculate index to array         */
  funkey[ndx].function = function;      /* Copy pointer to funkey function  */
  if (strlen(text) > 6) text[6] = '\0'; /* Check if text is not to long     */
  funkey[ndx].text     = text;          /* Copy pointer to funkey text      */
}
Variable Documentation
SCREEN _cursvar
FUNCTION_HANDLER funkey[40] [static]
Definition at line 53 of file funkey.c.
int show_funkeys = FALSE [static]
Definition at line 54 of file funkey.c.
Referenced by disp_funkeys().
WINDOW* w = NULL [static]
Definition at line 52 of file funkey.c.