HVA-WIN: genindex.c File Reference
genindex.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Defines
#define FALSE 0
#define TRUE !FALSE
Functions
int trimstr (char *s)
int main (int argc, char *argv[])
Define Documentation
#define FALSE 0
Definition at line 80 of file genindex.c.
#define TRUE !FALSE
Definition at line 81 of file genindex.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 121 of file genindex.c.
References fp, pos, and trimstr().
{
  FILE *fp;
  FILE *fo;
  char buf[132];
  static char fname[132];
  unsigned i;
  long pos;
  char *p;
  char *token;
  if(argc < 2)       /* check command line */
  {
    printf("Usage: genindex <filename.ext>");
    exit(1);
  }
  p = argv[1];      /* parse input filename */
  i = 0;
  while(*p) {
    fname[i++] = *p++;
    if(*p == ' ' || *p == '.') break;
  }
  strcat(fname, ".ndx");                /* create output filename */
  fp = fopen(argv[1], "r");             /* open input */
  if(!fp) {
    printf("Open failed: %s", argv[1]);
    exit(1);
  }
  printf("Creating: %s\n", fname);        /* say whats going on */
  fo = fopen(fname, "w");                 /* open output */
  while(fgets(&buf[0],132,fp))            /* read lines till eof */
  {
    /*-------------------------------------------
      Check if this line starts with a topic key
    ---------------------------------------------*/
    if(buf[0] == ':')                     /* look for topic key  */
    {
      token = strtok(buf,":\n\r");
      trimstr(token);
      while (token)
      {
        pos = ftell(fp);                        /* get file position */
        fprintf(fo,"%s\n%ld\n",token,pos);      /* write to index file */
        fprintf(stdout,"%s\n%ld\n",token,pos);  /* display on console */
        token = strtok(NULL,":\n\r");           /* Look for next subtopic key */
      }
    }
  }
  fclose(fp);                             /* close files */
  fclose(fo);
  return(0);
}
int trimstr (char * s)
Definition at line 91 of file genindex.c.
Referenced by help(), and main().
{
  int i;
  if (s == NULL)
    return(FALSE);
  i = strlen(s);
  if (i==0)
    return(TRUE);
  while (isspace(s[--i]))       /* Delete trailing blanks */
    s[i] = '\0';
  i = 0;                      /* Delete leading blanks */
  while (isspace(s[i]))
    i++;
  strcpy(s,s+i);
  return(TRUE);
}