HVA-WIN: help.c File Reference
help.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <conio.h>
#include "video/v_video.h"
#include "keys.h"
#include "window.h"
Data Structures
struct TOPIC
struct TOPIC_LINK
Defines
#define KEY_LEN 25
#define MAX_LINES 512
#define MAXKEY 512
#define HELP_LINE_LEN 90
#define MAX_TOS 25
Functions
static void show_line (WINDOW *w, int linenr, char *s)
static void show_topic (long offset)
static int filbuf (long offset, int flag)
static int find_topiclink (int linenr, int n)
static int push_subject (char *s)
static char * pop_subject (void)
static void display_stack (void)
int init_help (char *help_file_name)
int help (char *in_subject)
static int check_screen (int *sl, int *el, int no_lines)
int prev_link (int curlink, int maxlink)
int next_link (int curlink, int maxlink)
void redraw_helpscreen (WINDOW *w, int startline, int no_lines)
int first_link_on_screen (int sl, int el, int *ll, int n)
int last_link_on_screen (int sl, int el, int *ll, int n)
void exit_help ()
Variables
SCREEN _cursvar
TOPIC topic [MAXKEY]
TOPIC_LINK topic_link [MAXKEY]
char * topic_txt [MAXKEY]
static FILE * fp
static WINDOW * wn
static int initflg = FALSE
static int startline = 0
static int height = 0
static int endline = 0
static int link_selected = 0
static int no_topics
static char current_subject [KEY_LEN]
static char * subject = NULL
static char * topic_key_buffer = NULL
static char * topic_txt_buffer = NULL
static char * link_key_buffer = NULL
static char stack [MAX_TOS][KEY_LEN]
static int tos = 0
char * default_subject = NULL
Define Documentation
#define HELP_LINE_LEN 90
Definition at line 84 of file help.c.
Referenced by filbuf(), help(), and init_help().
#define KEY_LEN 25
Definition at line 81 of file help.c.
Referenced by help(), and init_help().
#define MAX_LINES 512
Definition at line 82 of file help.c.
Referenced by check_screen(), filbuf(), and help().
#define MAX_TOS 25
Definition at line 125 of file help.c.
Referenced by push_subject().
#define MAXKEY 512
Definition at line 83 of file help.c.
Referenced by filbuf(), find_topiclink(), help(), and init_help().
Function Documentation
static int check_screen (int * sl, int * el, int no_lines) [static]
Definition at line 482 of file help.c.
References FALSE, height, MAX_LINES, min, and TRUE.
Referenced by show_topic().
{
  int redraw = FALSE;
  /*-------------------------------------------------------------
    Check on valid start line:
    (1) The startline must be at least 0 and
        at most MAX_LINES - window height
    (2) If there are less textlines then the window height,
        the startline number is 0.
  ------------------------------------------------------------*/
  if (*sl < 0) {
    redraw = TRUE;
    *sl = 0;
  }
  if (*sl > (MAX_LINES-height+1)) {
    redraw = TRUE;
    *sl = MAX_LINES-height+1;
  }
  if (no_lines > height) {
    redraw = TRUE;
    *sl = min(*sl,no_lines-height+11);
  }
  if (no_lines < height) {
    redraw = TRUE;
    *sl = 0;
  }
  /*---------------------------------------------------------
    Check on valid end line:
    (1) The last line in the window is at
        most the number of the startline + the height of
        the window.
    (2) If there are less textlines then the window height,
        the last textline is 'no_lines
  ----------------------------------------------------------*/
  if (no_lines > height) {
    *el = *sl + height - 1;
    redraw = TRUE;
  }
  if (no_lines < height) {
    *el = no_lines - 1;
    redraw = TRUE;
  }
  return(redraw);
}
static void display_stack (void) [static]
void exit_help (void)
Definition at line 1113 of file help.c.
References topic_key_buffer.
Referenced by init_help(), and wn_exit().
{
  free(topic_key_buffer);
}
static int filbuf (long offset, int flag) [static]
Definition at line 909 of file help.c.
References fp, height, HELP_LINE_LEN, TOPIC_LINK::key, TOPIC_LINK::len, len, TOPIC_LINK::line, MAX_LINES, MAXKEY, no_topics, TOPIC_LINK::pos, pos, topic_txt, and TRUE.
Referenced by show_topic().
{
  int    i,j;
  static int no_lines;
  char   line[HELP_LINE_LEN];  /* line buffer       */
  char   token[80];            /* Pointer to token  */
  int    pos,len;
  /*-------------------------------
    If flag == 1 Return immediately.
    The complete text of the topic
    has been read already
  ---------------------------------*/
  if (flag > 1)
    return(no_lines);
  /*----------------------
    Initialize variables
  -----------------------*/
  no_lines=0;
  no_topics = 0;          /* Number of links in the list */
  /*-----------------------------------
    Position file pointer on topic key
  -----------------------------------*/
  fseek(fp, offset, 0);       /* position file               */
  /*---------------------------------
    Read and process the topic text
  ----------------------------------*/
  do
  {
    fgets(line, 132, fp);     /* fetch a line              */
    /*-----------------------
      Check for end of file
    ------------------------*/
    if (!strcmp("*END*\n",line))
      break;
    /*---------------------------------
      Check for start of next topic
    -----------------------------------*/
    if (line[0] == ':')
       break;
    /*----------------------
      Check for file title
    -----------------------*/
    if (line[0] == '@')
      break;
    /*----------------------
      Strip LF from string
    -----------------------*/
    len = strlen(line);
    line[len-1] = '\0';
    strcpy(topic_txt[no_lines],line);
    /*----------------------------------------------------
      Check the line for subtopic links.
      If one is found, add this to the subtopic link list
    -----------------------------------------------------*/
    i = 0;
    while (strchr(&line[i],'~')) {
      /*---------------------------------------
        Extract token from the line
      ---------------------------------------*/
      while (line[i] && line[i] != '~') i++;     /* Find first '~' */
      pos = i;                                   /* Save position  */
      j = 0;
      i++;                                       /* Point after first '~' */
      while (line[i] && line[i] != '~') token[j++] = line[i++]; /* Extr. token */
      token[j] = '\0';                           /* End of string         */
      i++;                                       /* Point after 2nd '~'   */
      /*---------------------------------------
        Set the topic variables
      ---------------------------------------*/
      strcpy(topic_link[no_topics].key,token);
      topic_link[no_topics].line = no_lines;
      topic_link[no_topics].pos  = pos;
      len = strlen(token);
      topic_link[no_topics].len  = len;
      topic_txt[no_lines][pos]       = ' ';   /* 0x10; */       /* Mark begin of link */
      topic_txt[no_lines][pos+len+1] = ' ';   /* 0x11; */      /* Mark end of link   */
      no_topics++;
    }
    no_lines++;
    /*----------------------------------------------
      If flag is zero, then check if first screen
      is completely read.
    ------------------------------------------------*/
    if (flag == 0 && no_lines >= height)
      break;
  }
  while (TRUE);
  /*------------------------------------
    Clear remainder of topic text lines
  -------------------------------------*/
  for (j=no_lines ; j < MAX_LINES ; j++)
    topic_txt[j][0] = '\0';
  /*------------------------------------
    Clear remainder of topic link list
  -------------------------------------*/
  for (j=no_topics ; j< MAXKEY ; j++)
  {
    topic_link[j].key[0] = '\0';
    topic_link[j].line   = -1;
    topic_link[j].pos    = -1;
    topic_link[j].len    = -1;
  }
  return(no_lines);
}
static int find_topiclink (int linenr, int n) [static]
Definition at line 443 of file help.c.
References TOPIC_LINK::line, MAXKEY, and TRUE.
Referenced by show_line().
{
  int i;
  int line;
  /*---------------------------------------
    Find the 1st topic in this line
  ---------------------------------------*/
  i = -1;               /* Reset index */
  while (TRUE) {
    i++;
    line = topic_link[i].line;
    if (line > linenr)
      return(-1);      /* We are past the wanted line in the list    */
    if (line < 0)
      return(-1);      /* We ran out of the actual number of topics  */
    else if (i >= MAXKEY)
      return(-1);      /* We ran out of the maximum number of topics */
    else if (line == linenr) {
      if (n <= 0)
        return(i);     /* We found the n'th topic on the line        */
      else
        n--;
    }
  }
}
int first_link_on_screen (int sl, int el, int * ll, int n)
Definition at line 602 of file help.c.
References TOPIC_LINK::line.
Referenced by show_topic().
{
  int i;
  i = 0;
  *ll = topic_link[i].line;
  while (i < n && *ll < sl) {
    *ll = topic_link[i].line;
    if (*ll >= sl && *ll <= el)
      return(i);
    if (*ll >= el)
      return(-1);
    i++;
  }
  return(i-1);
}
int help (char * in_subject)
Definition at line 288 of file help.c.
References _cursvar, _help_border, _help_text, _SINGLE_LINE, current_subject, default_subject, FALSE, height, HELP_LINE_LEN, initflg, KEY_LEN, link_key_buffer, MAX_LINES, MAXKEY, pop_subject(), show_topic(), subject, topic_txt, topic_txt_buffer, trimstr(), TRUE, wn_close(), wn_error(), wn_log(), wn_log_indent(), wn_open(), wcb::y1, and wcb::y2.
Referenced by do_action(), popup(), pulldown(), and wn_dialog().
{
  int i;                                  /* scratch integers */
  int  topic_found = FALSE;
  if (!initflg)
  {
    wn_error("HELP system not initialized");
    return(FALSE);
  }
  wn_log_indent(2);
  wn_log("HELP() START ****\n");
  /*------------------------------------------
    Allocate memory for topic text buffer
    and assign pointer to it.
  ------------------------------------------*/
  topic_txt_buffer = calloc(MAX_LINES,HELP_LINE_LEN);
  if (!topic_txt_buffer)
  {
    wn_error("ERROR in allocating TOPIC_TXT_BUFFER");
    return(FALSE);
  }
  for(i=0; i<MAX_LINES; i++) /* Assign pointers to each text line*/
    topic_txt[i] =  topic_txt_buffer + i*HELP_LINE_LEN;
  /*--------------------------------------------
  | allocate memory for topic link key buffer
  | and assign pointer to it.
  --------------------------------------------*/
  link_key_buffer = calloc(MAXKEY,KEY_LEN);
  if (!link_key_buffer)
  {
    wn_error("ERROR in allocating memory for LINK_KEY_BUFFER");
    return(FALSE);
  }
  for(i=0; i<MAXKEY; i++)
    topic_link[i].key =  link_key_buffer + i*KEY_LEN;
  /*--------------------------------
    Remove leading ':' from subject
  ----------------------------------*/
  if (in_subject && in_subject[0] == ':')
  {
    in_subject[0] = ' ';
    trimstr(in_subject);
  }
  /*--------------------------------------------------------
    If no in_subject given, set subject to default subject
  ---------------------------------------------------------*/
  if (in_subject == NULL || in_subject[0] == '\0')
  {
    if (default_subject)
      in_subject = default_subject;
    else {
      wn_error("No default subject given");
      return(FALSE);
    }
  }
  strcpy(current_subject,in_subject);
  subject = in_subject;
  wn = wn_open(_SINGLE_LINE,0,0,_cursvar.cols,_cursvar.lines,
               _help_text,_help_border);
  if (!wn)
    return(FALSE);
  height = (wn->y2 - wn->y1) + 1;
  while (TRUE)
  {
    /*----------------------------
      Check if a subject is given
    ------------------------------*/
    if (subject == NULL)
      break;
    /*-----------------------------
      Search for key in topic list
    -------------------------------*/
    i=0;
    topic_found = FALSE;
    while(i < MAXKEY)
    {
      trimstr(subject);
      trimstr(topic[i].key);
      if(!strcmp(subject,topic[i].key))
      {
        topic_found = TRUE;
        break;
      }
      else i++;
    }
    /*---------------------------------------
      If key was found, display text of topic
    -----------------------------------------*/
    if (topic_found)
    {
      show_topic(topic[i].loc);
    }
    else
    {
      /*---------------------------------------
        Show that topic text is not available
      ----------------------------------------*/
      wn_error("Sorry... No help available on subject %s",subject);
      /*-------------------------------------------------
        Retrieve last subject from stack. If no subject
        is available, then stop this loop
      -------------------------------------------------*/
      subject = pop_subject();
      if (subject)
      {
        strcpy(current_subject,subject);
        subject = current_subject;
      }
      else      /* No subjects available any more */
        break;
    }
  }
  /*--------------------
    Close help window
  ---------------------*/
  wn_close(wn);
  /*-------------------------------------
    Free allocated memory
  ---------------------------------------*/
  free(topic_txt_buffer);
  free(link_key_buffer);
  wn_log_indent(-2);
  wn_log("HELP() END *****\n");
  return(FALSE);
}
int init_help (char * help_file_name)
Definition at line 206 of file help.c.
References exit_help(), fp, HELP_LINE_LEN, initflg, KEY_LEN, TOPIC::loc, MAXKEY, topic_key_buffer, TRUE, and wn_error().
Referenced by initialize().
{
  int i;
  char tmpname[30];                   /* temporary filename */
  char *ptr;
  char line[HELP_LINE_LEN];           /* line buffer                     */
  if (initflg)
  {
    wn_error("Help system for %s already initialized",*help_file_name);
    return(initflg);
  }
  /*-----------------------------------------------
  | allocate memory for strings in topic key index
  | and allocate pointers to it.
  ------------------------------------------------*/
  topic_key_buffer = calloc(MAXKEY,KEY_LEN);
  if (!topic_key_buffer)
  {
    wn_error("ERROR in allocating TOPIC_KEY_BUFFER");
    return(initflg);
  }
  for(i=0; i<MAXKEY; i++)
    topic[i].key = topic_key_buffer + i*KEY_LEN;
  /*--------------------------------------------------
    Call exit_help when exiting from the main program
  ----------------------------------------------------*/
  atexit(exit_help);
  /*-----------------------------------------------------
  | Build the topic index table will be build by using
  | file 'subject.ndx'. After this the helpfile
  | 'subject.hlp' will be opened and left open to use
  -------------------------------------------------------*/
  strcpy(tmpname,help_file_name);   /* form filename from root */
  strcat(tmpname,".ndx");
  fp = fopen(tmpname,"r");
  if (!fp)                          /* index file cant be found ! */
  {
    wn_error("Can't find indexfile %s for help functions",tmpname);
    return(initflg);
  }
  i = 0;                                /* read and process key file */
  while(fgets(line,HELP_LINE_LEN,fp))   /* build the topic index table */
  {
    ptr = strchr(line,'\n');        /* Find '\n'        */
    if (ptr) *ptr = '\0';           /* And make it '\0' */
    strcpy(topic[i].key, line);
    #ifdef DONT_SKIP_THIS
    if(line[0] != ':')              /* ignore all but subjects */
      continue;
    #endif
    fgets(line,HELP_LINE_LEN,fp);
    topic[i].loc = atol(line);
    i++;
  }
  fclose(fp);                       /* close index file */
  strcpy(tmpname, help_file_name);  /* form help file name from root */
  strcat(tmpname, ".hlp");          /* open and leave open ! */
  fp = fopen(tmpname, "r");
  if (!fp)
    return(initflg);
  initflg = TRUE;
  return(initflg);
}
int last_link_on_screen (int sl, int el, int * ll, int n)
Definition at line 633 of file help.c.
References TOPIC_LINK::line.
Referenced by show_topic().
{
  int i;
  i = n-1;
  *ll = topic_link[i].line;
  while (i >= 0 && *ll >= 0) {
    *ll = topic_link[i].line;
    if (*ll <= el && *ll >= sl)         /* Break if within screen      */
      return(i);
    if (*ll < sl)                       /* Break if past top of screen */
      return(-1);
    i--;
  }
  return(-1);
}
int next_link (int curlink, int maxlink)
Definition at line 561 of file help.c.
Referenced by show_topic().
{
  if (curlink < (maxlink-1))
    return(curlink+1);
  else
    return(curlink);
}
static char * pop_subject (void) [static]
Definition at line 177 of file help.c.
References stack, and tos.
Referenced by help(), and show_topic().
{
  tos--;
  if (tos < 0)
  {
    /*----------------
      Stack is empty
    -----------------*/
    tos++;
    return(NULL);
  }
  else
  {
    /*---------------------------------
      return contents of top of stack
    ----------------------------------*/
    return(stack[tos]);
  }
}
int prev_link (int curlink, int maxlink)
Definition at line 542 of file help.c.
Referenced by show_topic().
{
  maxlink=0;
  if (curlink > 0)
    return(curlink-1);
  else
    return(curlink);
}
static int push_subject (char * s) [static]
Definition at line 157 of file help.c.
References MAX_TOS, stack, and tos.
Referenced by show_topic().
{
  /*---------------------------------------------
    If stack is not full, push data on the stack
  -----------------------------------------------*/
  if (tos < MAX_TOS)
  {
    strcpy(stack[tos],s);
    tos++;
  }
  return(tos);
}
void redraw_helpscreen (WINDOW * w, int startline, int no_lines)
Definition at line 580 of file help.c.
References height, show_line(), and topic_txt.
Referenced by show_topic().
{
  int j;
  for(j=0; j<no_lines && j < height; j++) {
    show_line(w,startline+j,topic_txt[startline+j]);
  }
}
static void show_line (WINDOW * w, int linenr, char * s) [static]
Definition at line 1043 of file help.c.
References _help_bold, _help_linkselect, _help_text, _help_topiclink, find_topiclink(), len, link_selected, pos, startline, wn_fill(), wn_locate(), wn_printf(), wn_setattrib(), and wcb::xsize.
Referenced by redraw_helpscreen(), and show_topic().
{
  int  link;
  int  i;
  int  w_line;        /* Window line number */
  /*-------------------
    Initializations
  -------------------*/
  w_line = linenr - startline;
  /*-------------------------------
    Clear the line in the window
  -------------------------------*/
  wn_fill(w,w_line,0,w->xsize-2,1,' ',_help_text);
  switch(s[0]) {
    case '^':       /* Centered, highlighted line */
      wn_locate(w,w_line,5);  /* Not centered yet */
      wn_printf(w,"%s",s+1);
      return;
      break;
    case '%':       /* Complete highlighted line */
      wn_setattrib(w,w_line,0,w->xsize-2,1,_help_bold);
      wn_locate(w,w_line,0);
      wn_printf(w,"%s",s+1);
      return;
      break;
    default:
      if (*s) {
        wn_locate(w,w_line,0);
        wn_printf(w,"%s",s+1);
      }
      break;
  }
  /*------------------------------------------
    Check if this line has a topic link in it
  --------------------------------------------*/
  i = 0;
  link = find_topiclink(linenr,i);
  while (link >= 0) {
    /*----------------------------------
      Set the attributes of a link key
    -----------------------------------*/
    if (link == link_selected)
      wn_setattrib(w,w_line,topic_link[link].pos,topic_link[link].len,1,
                _help_linkselect);
    /*------------------------------
      Highlight the selected link
    ------------------------------*/
    else
      wn_setattrib(w,w_line,topic_link[link].pos,topic_link[link].len,1,
                _help_topiclink);
    /*---------------------------------
      Find the next topic on this line
    ----------------------------------*/
    i++;
    link = find_topiclink(linenr,i);
  }
}
static void show_topic (long offset) [static]
Definition at line 700 of file help.c.
References ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, ARROW_UP, check_screen(), current_subject, endline, ENTER, ESC_KEY, filbuf(), first_link_on_screen(), height, HT, last_link_on_screen(), TOPIC_LINK::line, link_selected, next_link(), no_topics, PAGE_DOWN, PAGE_UP, pop_subject(), prev_link(), push_subject(), redraw_helpscreen(), show_line(), startline, subject, topic_txt, TRUE, waitkey(), wn_clear(), wn_log(), and wn_scroll().
Referenced by help().
{
  /*------------
    Variables
  ------------*/
  int no_lines;                 /* No of lines of topic        */
  unsigned int choise;                   /* User input                  */
  int flag = 0;                 /* Flag for reading topic text */
  int old_link = 0;
  int old_linkline;
  int linkline;
  /*-------------------
    Initializations
  -------------------*/
  startline = 0;
  link_selected = 0;
  old_linkline  = startline;
  /*------------------------------------
    Get first screen of text from topic
  ------------------------------------*/
  no_lines = filbuf(offset, flag++);
  /*-------------------
    Show first screen
  --------------------*/
  wn_clear(wn);
  redraw_helpscreen(wn,startline,no_lines);
  /*----------------
    Show the text
  ----------------*/
  while(TRUE)
  {
    endline      = startline+height-1;
    linkline     = topic_link[link_selected].line;
    old_linkline = topic_link[old_link].line;
    /*----------------------------------------
      Hide old selected link and show new one
    -----------------------------------------*/
    /* link is on the same line */
    if ((link_selected != old_link) && old_linkline == linkline)
      show_line(wn,linkline,topic_txt[linkline]);
    else {
      if (old_linkline >= startline && old_linkline <= endline)
        show_line(wn,old_linkline,topic_txt[old_linkline]);
      if (linkline >= startline && linkline <= endline)
        show_line(wn,linkline,topic_txt[linkline]);
    }
    /*------------------------------------
      Read complete text for this topic
      (only once, controlled by 'flag'
    ------------------------------------*/
    no_lines = filbuf(offset, flag++);
    /*----------------------------------------
      Wait for valid keypress and react on it
    -----------------------------------------*/
    choise = waitkey();
    wn_log("startline = %d   endline = %d   linkline = %d ",startline,endline,linkline);
    wn_log("height = %d no_lines = %d ",height,no_lines);
    wn_log("key pressed: %x\n",choise);
    switch (choise)
    {
      case PAGE_UP:
        /*---------------------------------------
          Scroll the screen 1 page up
        ---------------------------------------*/
        startline -= height;
        endline   -= height;
        check_screen(&startline,&endline,no_lines);
        redraw_helpscreen(wn,startline,no_lines);
        if (linkline > endline) {
          link_selected = last_link_on_screen(startline,endline,&linkline,no_topics);
          if (linkline >= 0)
            show_line(wn,linkline,topic_txt[linkline]);
        }
        break;
      case PAGE_DOWN:
        /*---------------------------------------
          Scroll the screen 1 page down
        ---------------------------------------*/
        startline += height;
        endline   += height;
        check_screen(&startline,&endline,no_lines);
        redraw_helpscreen(wn,startline,no_lines);
        if (linkline < startline) {
          link_selected = first_link_on_screen(startline,endline,&linkline,no_topics);
          if (linkline >= 0)
            show_line(wn,linkline,topic_txt[linkline]);
        }
        break;
      case ARROW_UP:
        /*---------------------------------------
          Scroll the screen 1 line down
        ---------------------------------------*/
        if (startline > 0) {
          startline--;
          endline--;
          wn_scroll(wn,-1);
          show_line(wn,startline,topic_txt[startline]);
        }
        /*---------------------------------------
          Check if selected link is not
          outside the screen. If so, search
          for new link and show this line
        ---------------------------------------*/
        if (linkline >= endline) {
          old_link = link_selected;       /* Save old link */
          while (linkline >= endline && link_selected > 0) {
            link_selected = prev_link(link_selected,no_topics);
          }
          show_line(wn,linkline,topic_txt[linkline]);
        }
        break;
      case ARROW_DOWN:
        /*---------------------------------------
          Scroll the screen 1 line up
        ---------------------------------------*/
        if (endline < no_lines) {
          startline++;
          endline++;
          wn_scroll(wn,1);
          show_line(wn,endline,topic_txt[endline]);
        }
        if (linkline < startline) {
          link_selected = first_link_on_screen(startline,endline,&linkline,no_topics);
          if (linkline >= 0)
            show_line(wn,linkline,topic_txt[linkline]);
        }
        break;
      case ARROW_LEFT:
        /*---------------------------------------
          Goto previous link
        ---------------------------------------*/
        old_link = link_selected;
        link_selected = prev_link(link_selected,no_topics);
        linkline = topic_link[link_selected].line;
        if (linkline < startline) {
          startline = linkline;
          redraw_helpscreen(wn,startline,no_lines);
        }
        break;
      case HT:
      case ARROW_RIGHT:
        /*---------------------------------------
          Goto next link
        ---------------------------------------*/
        old_link = link_selected;
        link_selected = next_link(link_selected,no_topics);
        linkline = topic_link[link_selected].line;
        if (linkline > endline) {
          endline = linkline;
          startline = endline - height + 1;
          redraw_helpscreen(wn,startline,no_lines);
        }
        break;
      /*----------------------------------
        Get topic key if ENTER is pressed
      -----------------------------------*/
      case ENTER:
        if (no_topics > 0)
        {
          push_subject(subject);
          strcpy(current_subject,topic_link[link_selected].key);
          subject = current_subject;
        }
        return;
        break;
      /*---------------
        Quit from help
      -----------------*/
      case ESC_KEY:
        subject = pop_subject();
        if (subject)
        {
          strcpy(current_subject,subject);
          subject = current_subject;
        }
        return;
        break;
    }
  }
}
Variable Documentation
SCREEN _cursvar
char current_subject[KEY_LEN] [static]
Definition at line 119 of file help.c.
Referenced by help(), and show_topic().
char* default_subject = NULL
Definition at line 144 of file help.c.
Referenced by help(), and initialize().
int endline = 0 [static]
Definition at line 116 of file help.c.
Referenced by show_topic().
FILE* fp [static]
Definition at line 109 of file help.c.
Referenced by filbuf(), init_help(), main(), and wn_log().
int height = 0 [static]
Definition at line 115 of file help.c.
Referenced by check_screen(), filbuf(), help(), redraw_helpscreen(), show_topic(), and wn_dialog().
int initflg = FALSE [static]
Definition at line 113 of file help.c.
Referenced by help(), and init_help().
char* link_key_buffer = NULL [static]
Definition at line 123 of file help.c.
Referenced by help().
int link_selected = 0 [static]
Definition at line 117 of file help.c.
Referenced by show_line(), and show_topic().
int no_topics [static]
Definition at line 118 of file help.c.
Referenced by filbuf(), and show_topic().
char stack[MAX_TOS][KEY_LEN] [static]
Definition at line 126 of file help.c.
Referenced by pop_subject(), and push_subject().
int startline = 0 [static]
Definition at line 114 of file help.c.
Referenced by show_line(), and show_topic().
char* subject = NULL [static]
Definition at line 120 of file help.c.
Referenced by help(), and show_topic().
TOPIC topic[MAXKEY]
Definition at line 105 of file help.c.
char* topic_key_buffer = NULL [static]
Definition at line 121 of file help.c.
Referenced by exit_help(), and init_help().
TOPIC_LINK topic_link[MAXKEY]
Definition at line 106 of file help.c.
char* topic_txt[MAXKEY]
Definition at line 107 of file help.c.
Referenced by filbuf(), help(), redraw_helpscreen(), and show_topic().
char* topic_txt_buffer = NULL [static]
Definition at line 122 of file help.c.
Referenced by help().
int tos = 0 [static]
Definition at line 127 of file help.c.
Referenced by pop_subject(), and push_subject().
WINDOW* wn [static]
Definition at line 111 of file help.c.