HVA-WIN: keys.c File Reference
keys.c File Reference
#include <bios.h>
#include "keys.h"
Functions
int key_pressed ()
unsigned char shift_status ()
unsigned int waitkey ()
int is_fkey (unsigned int scancode)
Function Documentation
int is_fkey (unsigned int scancode)
Definition at line 55 of file keys.c.
References FALSE, and TRUE.
Referenced by do_funkey(), popup(), and pulldown().
{
  switch (scancode) {
        /*--- F1...F12  */
    case        0x3B00 :
    case        0x3C00 :
    case        0x3D00 :
    case        0x3E00 :
    case        0x3F00 :
    case        0x4000 :
    case        0x4100 :
    case        0x4200 :
    case        0x4300 :
    case        0x4400 :
    case        0x8500 :
    case        0x8600 :
    /*--- Shift F1..F2  */
    case        0x5400 :
    case        0x5500 :
    case        0x5600 :
    case        0x5700 :
    case        0x5800 :
    case        0x5900 :
    case        0x5A00 :
    case        0x5B00 :
    case        0x5C00 :
    case        0x5D00 :
    case        0x8700 :
    case        0x8800 :
    /*--- CTRL F1..F12  */
    case        0x5E00 :
    case        0x5F00 :
    case        0x6000 :
    case        0x6100 :
    case        0x6200 :
    case        0x6300 :
    case        0x6400 :
    case        0x6500 :
    case        0x6600 :
    case        0x6700 :
    case        0x8900 :
    case        0x8A00 :
    /*---  ALT F1..F12  */
    case        0x6800 :
    case        0x6900 :
    case        0x6A00 :
    case        0x6B00 :
    case        0x6C00 :
    case        0x6D00 :
    case        0x6E00 :
    case        0x6F00 :
    case    0x7000 :
        case    0x7100 :
        case    0x8B00 :
        case    0x8C00 : return TRUE;
        default        : return FALSE;
  }
}
int key_pressed (void)
Definition at line 14 of file keys.c.
References FALSE, TRUE, and wn_log().
Referenced by waitkey().
{
  if (bioskey(1)) {
    wn_log("key_pressed() TRUE\n");
    wn_log("TRUE \n");
    return(TRUE);
  }
  return(FALSE);
}
unsigned char shift_status (void)
Definition at line 27 of file keys.c.
Referenced by editstr().
{
  return(bioskey(2));
}
unsigned int waitkey (void)
Definition at line 37 of file keys.c.
References key_pressed(), and wn_log().
Referenced by editstr(), get_dir(), popup(), pulldown(), show_topic(), and wn_dialog().
{
  unsigned int scancode;
  wn_log("waitkey()\n");
  /*--- Wait for a keypress  */
  while (!key_pressed());
  scancode = bioskey(0x10);
  wn_log("scancode = %0lx\n",scancode);
  return(scancode);
}