HVA-WIN: popup.c File Reference
popup.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <dos.h>
#include "video/v_video.h"
#include "keys.h"
#include "window.h"
Functions
char * void_sprintf (char *datastr, char *format, void *data)
void void_sscanf (char *str, char *format, void *data)
void do_action (MENU *menu, int i)
unsigned int popup (int number, MENU *menu, int row, int col)
Function Documentation
void do_action (MENU * menu, int i)
Definition at line 49 of file popup.c.
References _DRAW, action_col, action_row, MENU::data, EDIT_STR, editstr(), FALSE, MENU::flags, help(), HELP_ONLY, s, SELECTABLE, TRUE, void_sprintf(), and void_sscanf().
Referenced by popup(), and wn_dialog().
{
  char datastr[80], *s;
  /*---------------------------------------
    Toggle a BOOLEAN value
  ---------------------------------------*/
  if (menu[i].flags & SELECTABLE) {
    if (menu[i].data == FALSE)
      menu[i].data = (void *) TRUE;
    else
      menu[i].data = (void *) FALSE;
    return;
  }
  /*---------------------------------------
    Edit a string
  ---------------------------------------*/
  if (menu[i].data != NULL
  && (menu[i].format != NULL)
  && (menu[i].flags & EDIT_STR)) {
    s = void_sprintf(datastr,menu[i].format,menu[i].data);
    if (s) {
      editstr(action_row+2,action_col+2,30,menu[i].header,datastr,_DRAW);
      void_sscanf(datastr,menu[i].format,menu[i].data);
      return;
    }
  }
  /*---------------------------------------
    Enter help functions if HELP_ONLY
  ---------------------------------------*/
  if (menu[i].flags & HELP_ONLY)
  {
    help(menu[i].help);
    return;
  }
  /*---------------------------------------------
    If a function was defined, perform function
  -----------------------------------------------*/
  if (menu[i].function != NULL)
  {
    (*(PFI)(menu[i].function))();
    return;
  }
}
unsigned int popup (int number, MENU * menu, int row, int col)
Definition at line 112 of file popup.c.
References _border_att, _comment_att, _disabled_att, _menu_att, _menu_highlight, _SINGLE_LINE, action_col, action_row, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, ARROW_UP, AUTO_COL, AUTO_ROW, COMMENT, DISABLED, do_action(), do_funkey(), ENTER, ESC, ESC_KEY, EXIT, F1, FALSE, MENU::header, help(), MENU::hotkey, hotstring(), is_fkey(), max, s, MENU::string, TRUE, void_sprintf(), waitkey(), wn_close(), wn_log(), wn_log_indent(), wn_open(), wcb::x1, and wcb::y1.
Referenced by pulldown().
{
  int i,mlen;
  unsigned int key = ARROW_DOWN;    /* Default key */
  WINDOW *popup_window;
  char datastr[132], *s;
  static int select = 0, old_select = 0;
  static MENU *oldmenu = NULL;
  static int autorow = FALSE;
  static int last_row = 0;
  static int autocol = FALSE;
  static int last_col = 0;
  wn_log("START POPUP()\n");
  wn_log_indent(+2);
  /*---------------------------------------
    Determine row
  ---------------------------------------*/
  if (row == AUTO_ROW) {
    if (!autorow) {
      row = action_row;
      last_row = action_row;
      autorow = TRUE;
    }
    else {
      row = last_row;
    }
  }
  else {
    autorow = FALSE;
    last_row = row;
  }
  /*---------------------------------------
    Determine column
  ---------------------------------------*/
  if (col == AUTO_COL) {
    if (!autocol) {
      col = action_col;
      last_col = action_col;
      autocol = TRUE;
    }
    else {
      col = last_col;
    }
  }
  else {
    autocol = FALSE;
    last_col = col;
  }
  /*---------------------------------------
    Fill menu strings with data
  ---------------------------------------*/
  for (i=0 ; i<number ; i++)
  {
    menu[i].string[0] = '\0';
    strcpy(menu[i].string,menu[i].header);  /* Copy 'header' to 'string' */
    s = void_sprintf(datastr,menu[i].format,menu[i].data);
    if (s)
    {
      strcat(menu[i].string,"  ");      /* Add blanks  */
      strcat(menu[i].string,datastr);   /* Add 'datastr' to 'string' */
    }
  }
  /*-----------------------------------
    Determine the maximum line length
  ------------------------------------*/
  mlen = 0;
  for (i=0 ; i<number ; i++)
    mlen = max(mlen,strlen(menu[i].string));
  /*------------------------------------------------------------
    Open the window and print the items
    12-Oct-1993 V0.7: Add 2 for xsize to include window borders
  -------------------------------------------------------------*/
  popup_window = wn_open(_SINGLE_LINE, row, col, mlen+2, number+2,
                    _menu_att, _border_att);
  row = popup_window->y1;
  col = popup_window->x1;
  wn_log("printing popup menu items:\n");
  for (i=0 ; i<number ; i++)
  {
    if (menu[i].flags & COMMENT)
      hotstring(row+i,col,-1,menu[i].string,_comment_att);
    else if (menu[i].flags & DISABLED)
      hotstring(row+i,col,-1,menu[i].string,_disabled_att);
    else
      hotstring(row+i,col,menu[i].hotkey,menu[i].string,_menu_att);
  }
  /*-------------------------------------------------------
    If it is the same menu as last time, we use the last
    selected item to highlight
  -------------------------------------------------------*/
  if (menu == oldmenu)
  {
    select = ++select % number;
    old_select = select;
  }
  else
  {
    select = 0;
    old_select = 0;
    oldmenu = menu;
  }
  while(TRUE)
  {
    /*-------------------------------------------------------------------
      Reset attribute of old selected line.
      Don't do this when the item is a COMMENT or when it is DISABLED
    --------------------------------------------------------------------*/
    if (!(menu[old_select].flags & (COMMENT|DISABLED))) {
      v_setattrib_area(row+old_select,col,mlen,1,_menu_att);
      hotstring(row+old_select,col,
        menu[old_select].hotkey,menu[old_select].string,_menu_att);
    }
    /*-------------------------------------------------------------------
      Set attribute of new selected line.
      Don't do this when the item is a COMMENT or when it is DISABLED
    --------------------------------------------------------------------*/
    if (!(menu[select].flags & (COMMENT|DISABLED))) {
      action_row = row+select;
      action_col = col;
      v_setattrib_area(action_row,action_col,mlen,1,_menu_highlight);
    }
    if (!(menu[select].flags & (COMMENT|DISABLED)))
      key = waitkey();            /*--- Scancode is returned here  */
    if (is_fkey(key)) {
      switch(key) {
        case F1:  help(menu[select].help); break;
        default:  do_funkey(key); break;
      }
    }
    /*-----------------------------------------------
      If hotkey defined, make this the new key value
    ------------------------------------------------*/
    switch(key) {
      case ENTER:
        if (menu[select].hotkey != -1)
          key = menu[select].header[menu[select].hotkey];
        break;
      default:
        break;
    }
    switch(key) {
      /*----------------------
      | Up- and down arrow
      -----------------------*/
      case ARROW_UP:
            wn_log("ARROW_UP\n");
        old_select = select;
        select = (--select+number) % number;
        break;
      case ARROW_DOWN:
            wn_log("ARROW_DOWN\n");
        old_select = select;
        select = ++select % number;
        break;
      /*--------------------------------------
      | No hotkey defined for this popup menu
      ----------------------------------------*/
      case ENTER:
            wn_log("ENTER\n");
        if (menu[select].flags & EXIT) {
          wn_log_indent(-2);
          wn_log("END POPUP()\n");
          popup_window = wn_close(popup_window);   /* Close it before actions */
        }
        do_action(menu,select);
        wn_log_indent(-2);
        wn_log("END POPUP()\n");
        popup_window = wn_close(popup_window);
        return(select);           /* Return number of selected item [0,...> */
      /*----------------------
      | Escape from popup()
      ----------------------*/
      case ESC_KEY:
      case ARROW_LEFT:
      case ARROW_RIGHT:
            wn_log("ESC or ARROW_LEFT or ARROW_RIGHT\n");
        wn_log_indent(-2);
        wn_log("END POPUP()\n");
        popup_window = wn_close(popup_window);
        return(key);
      default:
            wn_log("OTHER KEY\n");
                key = key & 0x00FF;
        if (key > 31 && key < 128) {
          for (i=0 ; i<number ; i++) {
            if (toupper(key) == toupper(menu[i].header[menu[i].hotkey])) {
              if (menu[i].flags & EXIT) {
                wn_log_indent(-2);
                wn_log("END POPUP()\n");
                popup_window = wn_close(popup_window);
              }
              do_action(menu,i);
              wn_log_indent(-2);
              wn_log("END POPUP()\n");
              popup_window = wn_close(popup_window);
              return(toupper(key));
            }
          }
        } /* if (key ...) */
    } /* switch(key) */
  } /* while (TRUE) */
  if (key == ENTER)
    return(select);
  else if (key == ESC_KEY)
    return(ESC);
  else
    return(toupper(key));
}
char* void_sprintf (char * datastr, char * format, void * data)
Definition at line 197 of file windio.c.
Referenced by do_action(), edit_data(), and popup().
{
  char *s;
  int long_format = FALSE;
  if (!format) /* || !data) */
    return(NULL);
  s = strchr(format,'%'); /* Check for format identifier   */
  if (!s)                 /* If no identifier, return NULL */
    return(NULL);
  s = strpbrk(format,"duouxXfegEGcsB");
  if (*(s-1) == 'l')
    long_format = TRUE;
  switch (*s)
  {
    case 'd':
    case 'i':
      if (long_format)
        sprintf(str,format, *((long *) data));
      else
        sprintf(str,format, *((unsigned int *) data));
      break;
    case 'o':
    case 'u':
    case 'x':
      sprintf(str,format, *((unsigned int *) data));
      break;
    case 'X':
      if (long_format)
        sprintf(str,format,*((unsigned long *) data));
      else
        sprintf(str,format, *((unsigned int *) data));
      break;
    case 'f':
    case 'e':
    case 'g':
    case 'E':
    case 'G':
      if (long_format)
        sprintf(str,format,*((double *)data));
      else
        sprintf(str,format, *((float *) data));
      break;
    case 'c':
      sprintf(str,format,*(char *)data);
      break;
    case 's':
      sprintf(str,format,(char *) data);
      break;
    case 'B':
      if ((int *)data)
        strcpy(str,"ON");
      else
        strcpy(str,"OFF");
      break;
    default:
      break;
  }
  return(str);
}
void void_sscanf (char * str, char * format, void * data)
Definition at line 269 of file windio.c.
Referenced by do_action(), and edit_data().
{
  char *s;
  char *dummy;
  int long_format = FALSE;
  s = strchr(format,'%'); /* Check for format identifier   */
  if (!s)                 /* If no identifier, return NULL */
    return;
  if (format == NULL)
    return;
  s = strpbrk(format,"duouxXfegEGcsB");
  if (*(s-1) == 'l')
    long_format = TRUE;
  switch (*s)
  {
    case 'd':
    case 'i':
      if (long_format)
        *(long *)data = atol(str);
      else
        *(int *)data = atoi(str);
      break;
    case 'o':
      *(unsigned int *)data = (unsigned int) strtol(str,&dummy,8);
      break;
    case 'O':
      *(long *)data = strtoul(str,&dummy,8);
      break;
    case 'u':
      *(unsigned int *)data = (unsigned int) strtoul(str,&dummy,10);
      break;
    case 'U':
      *(long *)data = strtoul(str,&dummy,10);
      break;
    case 'x':
      *(unsigned int *) data = (unsigned int) strtoul(str,&dummy,16);
      break;
    case 'X':
      *(long *) data = strtoul(str,&dummy,16);
      break;
    case 'f':
    case 'e':
    case 'g':
    case 'E':
    case 'G':
      if (long_format)
        *(double *)data = atof(str);
      else
        *(float *)data = (float) atof(str);
      break;
    case 'c':
      sscanf(str,"%c",(char *)data);
      break;
    case 's':
      strcpy((char *)data,str);
      break;
    default:
      break;
  }
}