HVA-WIN: pulldown.c File Reference
pulldown.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <conio.h>
#include "video/v_video.h"
#include "keys.h"
#include "window.h"
#include "fortify.h"
Functions
static void show_bar (void)
static void calc_pulldownbar (MENU_HEAD *head)
static void mem_pulldownbar (void)
int pulldown (MENU_HEAD *shead, int ikey, char *menu_help)
void pulldown_bar (MENU_HEAD *shead)
void exit_pulldown ()
Variables
SCREEN _cursvar
static int * columns
static char * hotkeys
static MENU_HEAD * cptr = NULL
static MENU_HEAD * head = NULL
static int no_heads = 0
static int menu
static MENU * mptr
static WINDOW * pd_bar = NULL
Function Documentation
static void calc_pulldownbar (MENU_HEAD * head) [static]
Definition at line 208 of file pulldown.c.
References col, columns, MENU::header, hotkeys, MENU_HEAD::mptr, no_heads, MENU_HEAD::number, MENU::string, and wn_log().
Referenced by pulldown_bar().
{
  int i,j;
  int col;
  MENU *m;         /* Pointer to menu        */
  wn_log("calc_pulldownbar()\n");
  /*-------------------------------------------
    Preprocess the entrys of each menu[header]
  ---------------------------------------------*/
  for (i=0 ; i<no_heads ; i++)
  {
    m = head[i].mptr;
    j = 0;
    while (m->header)
    {
      strcpy(m->string,m->header);   /* Copy header to string            */
      j++;                           /* Increase counter                 */
      m = m+1;                       /* Update menu pointer              */
      head[i].number = j;            /* Update cntr of number of entries */
    }
  }
  col = 1;                      /* start column of first header */
  for (i=0 ; i<no_heads ; i++)
  {
    /*--- Save header hotkey and header start column ---*/
    columns[i] = col;
    hotkeys[i] = toupper(head[i].header[head[i].hotkey]);
    col += strlen(head[i].header) + 2;
  }
  hotkeys[no_heads] = '\0';  /* Terminate the array of hotkeys   */
}
void exit_pulldown (void)
Definition at line 348 of file pulldown.c.
References columns, hotkeys, and wn_log().
Referenced by wn_exit().
{
  wn_log("exit_pulldown()\n");
  if (hotkeys)
    free(hotkeys);
  if (columns)
    free((char *)columns);
}
static void mem_pulldownbar (void) [static]
Definition at line 253 of file pulldown.c.
References columns, hotkeys, and no_heads.
Referenced by pulldown_bar().
{
  /*--------------------------------------------
    ALLOCATE OR REALLOCATE MEMORY FOR 'COLUMNS'
  ----------------------------------------------*/
  if (columns == NULL)
  { if ((columns = (int *) malloc(no_heads*sizeof(int))) == NULL)
    { printf("Out of memory\n");
      exit(1);
    }
  }
  else
  {
    if ((columns = (int *) realloc((char *)columns,no_heads*sizeof(int))) == NULL)
    {
      printf("Out of memory\n");
      exit(1);
    }
  }
  /*---------------------------------------------
    ALLOCATE OR REALLOCATE MEMORY FOR 'HOTKEYS'
  ----------------------------------------------*/
  if (hotkeys == NULL)
  {
    if ((hotkeys = malloc((no_heads+1)*sizeof(char))) == NULL)
    {
      printf("Out of memory\n");
      exit(1);
    }
  }
  else
  {
    if ((hotkeys = realloc(hotkeys,(no_heads+1)*sizeof(char))) == NULL)
    {
      printf("Out of memory\n");
      exit(1);
    }
  }
}
int pulldown (MENU_HEAD * shead, int ikey, char * menu_help)
Definition at line 92 of file pulldown.c.
References _menu_att, ARROW_LEFT, ARROW_RIGHT, columns, do_funkey(), ESC_KEY, F1, FALSE, help(), hotkeys, is_fkey(), menu, MENU_HEAD::mptr, no_heads, popup(), pulldown_bar(), show_bar(), TRUE, waitkey(), wn_log(), and wn_log_indent().
Referenced by main().
{
  unsigned int  key;
  char c;
  int match = FALSE;
  unsigned int choise = 0;
  int i;
  wn_log_indent(2);
  wn_log("pulldown() MENU_HEAD=%p\n",shead);
  /* SHOW MENU HEADERS
  --------------------*/
  pulldown_bar(shead);
  /*----------------------------------------
     Use initial key or wait for a keypress
  -----------------------------------------*/
  wn_log("pulldown() - Waiting for first key press\n");
  if (ikey)
    key = ikey;
  else
    key = waitkey();
  wn_log("key pressed = %x\n",key);
  /*--- If function key, react on it  */
  if (is_fkey(key)) {
    wn_log("function key pressed\n");
    switch(key) {
      case F1:  help(menu_help); return(0); break;
      default:  do_funkey(key); break;
    }
  }
  /*--- If ESC key, return  */
  if (key == ESC_KEY)
    return(ESC_KEY);
  c = (char) (key & 0x00FF);
  wn_log("character = <%c>\n",c);
  /*----------------------------------------------
    Check if key matches with one of the hotkeys
  -----------------------------------------------*/
  for (i=0 ; i<strlen(hotkeys) ; i++) {
    if (c == hotkeys[i] || toupper(c) == hotkeys[i]) {
          wn_log("we have a hotkey match\n");
          match = TRUE;
          break;
        }
  }
  if (match == TRUE) {
    menu = i;
  }
  else {
    wn_log("no match found\n");
    return(key);
  }
  /* THERE IS A MATCH ...
  ----------------------*/
  v_cursoroff();
  while(TRUE)
  {
    mptr = head[menu].mptr;
        wn_log("mptr = %p\n",mptr);
    if (head[menu].number != 0)
      choise = popup(head[menu].number,mptr,1,columns[menu]);
    else
    {
          wn_log("pulldown() - check if a function is defined\n");
      /*---------------------------------------------
        If a function was defined, perform function
      -----------------------------------------------*/
      if (mptr[0].function != NULL) {
            wn_log("perform function \n");
        (*(PFI)(mptr[0].function))();
          }
    }
    wn_log("choise = %x\n",choise);
    switch(choise)
    {
      case ARROW_LEFT:
        v_setattrib_area(0, columns[menu], strlen(head[menu].header), 1, _menu_att);
        menu = (--menu + no_heads) % no_heads;
        show_bar();
        break;
      case ARROW_RIGHT:
        v_setattrib_area(0, columns[menu], strlen(head[menu].header), 1, _menu_att);
        menu = ++menu % no_heads;
        show_bar();
        break;
      default:
        break;
    } /* switch(choise) */
    if (choise == ESC_KEY)
      break;
  } /* while(TRUE) */
  show_bar();
  return(0);
}
void pulldown_bar (MENU_HEAD * shead)
Definition at line 301 of file pulldown.c.
References calc_pulldownbar(), MENU_HEAD::header, mem_pulldownbar(), no_heads, show_bar(), and wn_log().
Referenced by pulldown().
{
  MENU_HEAD *h;
  wn_log("pulldown_bar() MENU_HEAD=%p\n",shead);
  /*--------------------------------------
    If same menuline as last time, return
  ----------------------------------------*/
  if (cptr == shead)
    return;
  else
  {
    cptr = shead;
    head = shead;
  }
  /*-------------------------------
    Determine number of menu heads
    this must be done before calling
    mem_pulldownbar()
  ---------------------------------*/
  h = shead;
  while (h->header)
  {
    no_heads++;
    h++;
  }
  /*------------------------------
    Assign memory and
    Perform initial calculations
    Show the menu bar
  -------------------------------*/
  mem_pulldownbar();
  calc_pulldownbar(head);
  show_bar();
}
static void show_bar (void) [static]
Definition at line 51 of file pulldown.c.
References _cursvar, _menu_att, _NO_BORDER, col, hotstring(), no_heads, wn_log(), wn_log_indent(), wn_open(), wn_restore(), and wn_save().
Referenced by pulldown(), and pulldown_bar().
{
  int i;
  int col;
  wn_log_indent(2);
  wn_log("SHOW_BAR *****()\n");
  /*----------------------------------------------------------
    Check if pulldownbar already openened. If not, do it here
  ------------------------------------------------------------*/
  if (!pd_bar)
  {
    pd_bar = wn_open(_NO_BORDER,0,0,_cursvar.cols,1,_menu_att,_menu_att);
    col = 1;
    for (i=0 ; i<no_heads ; i++)
    {
      /*--- show header ---*/
      hotstring(0,col,head[i].hotkey,head[i].header,_menu_att);
      col += strlen(head[i].header) + 2;
    }
    wn_save(pd_bar);
  }
  else
    wn_restore(pd_bar);
  wn_log("END SHOW_BAR *****\n");
  wn_log_indent(-2);
}
Variable Documentation
SCREEN _cursvar
int* columns [static]
Definition at line 31 of file pulldown.c.
Referenced by calc_pulldownbar(), exit_pulldown(), mem_pulldownbar(), and pulldown().
MENU_HEAD* cptr = NULL [static]
Definition at line 33 of file pulldown.c.
MENU_HEAD* head = NULL [static]
Definition at line 34 of file pulldown.c.
char* hotkeys [static]
Definition at line 32 of file pulldown.c.
Referenced by calc_pulldownbar(), exit_pulldown(), mem_pulldownbar(), and pulldown().
int menu [static]
Definition at line 36 of file pulldown.c.
Referenced by intro_screen(), pulldown(), wn_error(), and wn_yesno().
MENU* mptr [static]
Definition at line 37 of file pulldown.c.
int no_heads = 0 [static]
Definition at line 35 of file pulldown.c.
Referenced by calc_pulldownbar(), mem_pulldownbar(), pulldown(), pulldown_bar(), and show_bar().
WINDOW* pd_bar = NULL [static]
Definition at line 38 of file pulldown.c.