HVA-WIN: window.c File Reference
window.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <conio.h>
#include <dos.h>
#include <ctype.h>
#include <string.h>
#include "video/v_video.h"
#include "window.h"
#include <mem.h>
Defines
#define MAIN_WINDOW_MODULE
Functions
static WINDOW * add_wn_list (WINDOW *w)
static WINDOW * del_wn_list (WINDOW *w)
static void level_wnds (WINDOW *startw)
int wn_closeall ()
int wn_update ()
void wn_dmode (int mode)
WINDOW * wn_save (WINDOWPTR w)
int wn_hide (WINDOWPTR w)
int wn_unhide (WINDOWPTR w)
int wn_move (WINDOW *w, int row, int col)
void wn_restore (WINDOWPTR w)
int wn_top (WINDOW *w)
void wn_dma (int flag)
int wn_sync (WINDOW *w, int flag)
int wn_fixcsr (WINDOW *w)
void wn_fill (WINDOW *w, int row, int col, int width, int height, int c, int att)
void wn_setattrib (WINDOW *w, int row1, int col1, int xsize, int ysize, int att)
int wn_setone (WINDOW *w, int row, int col, int attrib)
int wn_nattrib (WINDOW *w, int wcolor)
WINDOW * wn_open (int btype, int row, int col, int xsize, int ysize, int wcolor, int bcolor)
WINDOW * wn_close (WINDOW *w)
void wn_init ()
void wn_exit ()
int wn_overlap (WINDOW *w1, WINDOW *w2)
Variables
static int startrow
static int startcol
char * start_screen = NULL
WINDOW * top_window = NULL
WINDOW * start_window = NULL
WINDOW * last_window = NULL
unsigned int non_ibm = 0x0001
SCREEN _cursvar
Define Documentation
#define MAIN_WINDOW_MODULE
Definition at line 10 of file window.c.
Function Documentation
static WINDOW * add_wn_list (WINDOW * w) [static]
Definition at line 542 of file window.c.
References wcb::next, wcb::prev, wcb::title, and wn_log().
Referenced by wn_open(), and wn_top().
{
  WINDOW *tmp_w;
  wn_log("add_wn_list(%p,%s)\n",w,w->title);
  /*-----------------------
    Check if window opened
  -------------------------*/
  if (!w)
    return(NULL);
  /*-----------------------------------
    Add window to double linked list
  ------------------------------------*/
  if (start_window == NULL)
  {
    /*--- This is the first window in the list ---*/
    last_window  = w;
    start_window = w;
    w->next   = NULL;
    w->prev   = NULL;
  }
  else
  {
    /*--- Add this window to end of the list ---*/
    last_window->next = w;
    w->next  = NULL;
    w->prev  = last_window;
    last_window = w;
  }
  tmp_w = start_window;
  while(tmp_w)
    tmp_w = tmp_w->next;
  return(start_window);
}
static WINDOW * del_wn_list (WINDOW * w) [static]
Definition at line 589 of file window.c.
References level_wnds(), wcb::next, wcb::prev, wcb::title, and wn_log().
Referenced by wn_close(), and wn_top().
{
  wn_log("del_wn_list(%p,%s)\n",w,w->title);
  /*------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NULL);
  if (w == start_window)
  {
    /*--- We are going to delete the first window in the
          double linked list ---*/
    start_window = start_window->next;
    if (start_window)
      start_window->prev = NULL;
    if (!start_window)   /* If no window opened any more ... */
      last_window = NULL;
  }
  else {
    /*--- We are going to delete a window in the middle or at the
          end of the double linked list ---*/
    if (!w->next) {
      /*--- This window is the last one of the list ---*/
      last_window = w->prev;
      w->prev->next = NULL;
    }
    else {
      /*--- This window is in the middle of the list ---*/
      w->prev->next = w->next;
      w->next->prev = w->prev;
    }
  }
  level_wnds(start_window);
  return(start_window);
}
static void level_wnds (WINDOW * startw) [static]
Definition at line 638 of file window.c.
References wcb::level, wcb::next, wcb::title, w, and wn_log().
Referenced by del_wn_list().
{
  int  i = 1;
  WINDOW *w;
  w = startw;
  while (w) {               /* While window pointer not NULL */
    w->level = i++;         /* Assign a new level number */
    wn_log("  --- %p (%s) level:%2d\n",w,w->title,w->level);
    w = w->next;            /* Get next window */
  }
}
WINDOW* wn_close (WINDOW * w)
Definition at line 821 of file window.c.
References del_wn_list(), wcb::scrnsave, wcb::title, wn_log(), wn_top(), and wn_update().
Referenced by call_hexconv(), call_terminal(), call_zapload(), editstr(), exit_funkey(), get_dir(), help(), OS_shell(), overlap_demo(), popup(), wn_closeall(), wn_dialog(), and wn_shell().
{
  wn_log("wn_close(%p,%s)\n",w,w->title);
  /*---------------------------
    Check if window was opened
  -----------------------------*/
  if (w) {
    /*-------------------------------------------
      Check if window to close is the top window
    ---------------------------------------------*/
    if (w == top_window) {
      top_window = NULL;
      last_window = NULL;
    }
    /*-----------------------------------------------
      Delete the window from the double linked list
      and free memory of window's save area and
      control block
    -------------------------------------------------*/
    del_wn_list(w);
    if (w->scrnsave)
      free(w->scrnsave);
    if (w->title)
      free(w->title);
    free((char *) w);
    /*-----------------------------------------------
      Make last window in linked list the top window
      and update the screen
    -------------------------------------------------*/
    wn_top(last_window);
    wn_update();
  }
  return(NULL);
}
int wn_closeall (void)
Definition at line 71 of file window.c.
References wcb::next, TRUE, w, and wn_close().
Referenced by wn_exit().
{
  WINDOW *w, *nextw;
  /*------------------
    Close all windows
  --------------------*/
  if (start_window != NULL) {
    w = start_window;
    while (w) {
      nextw = w->next;
      wn_close(w);
      w = nextw;
    }
  }
  return(TRUE);
}
void wn_dma (int flag)
Definition at line 389 of file window.c.
{
  flag++;
}
void wn_dmode (int mode)
Definition at line 154 of file window.c.
{
  mode++;
}
void wn_exit (void)
Definition at line 930 of file window.c.
References exit_funkey(), exit_help(), exit_pulldown(), FALSE, start_screen, startcol, startrow, TRUE, wn_closeall(), and wn_log().
Referenced by exit_prog(), and wn_init().
{
  static int done = FALSE;
  if (!done)               /* Do this only once */
  {
    wn_log("wn_exit()\n");
    exit_help();
    exit_pulldown();
    exit_funkey();
    wn_closeall();
    if (start_screen)
      start_screen = v_restorescreen(start_screen);
    v_setcurpos(startrow,startcol);
    v_cursoron();
    done = TRUE;        /* Set flag (this routine has been executed */
  }
}
void wn_fill (WINDOW * w, int row, int col, int width, int height, int c, int att)
Definition at line 462 of file window.c.
References wcb::x1, and wcb::y1.
Referenced by show_line(), and wn_scroll().
{
  v_fillarea(w->y1+row,w->x1+col,width,height,c,att);
}
int wn_fixcsr (WINDOW * w)
Definition at line 426 of file window.c.
References wcb::ccx, wcb::ccy, NO_WINDOW, wcb::synflg, and TRUE.
Referenced by editstr(), wn_restore(), and wn_top().
{
  /*------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*--------------------------------
    Check if this is the top window
  ----------------------------------*/
  if (w != top_window)
    return(NO_WINDOW);
  /*--------------------------------------
    Get physical cursor coordinates and
    show cursor (if wanted
  --------------------------------------*/
  v_setcurpos(w->ccy,w->ccx);
  if (w->synflg)
    v_cursoron();
  else
    v_cursoroff();
  return(TRUE);
}
int wn_hide (WINDOWPTR w)
Definition at line 218 of file window.c.
References wcb::flag, NO_WINDOW, wcb::title, TRUE, wn_log(), and wn_update().
Referenced by disp_funkeys(), and wn_dialog().
{
  wn_log("wn_hide(%p,%s)\n",w,w->title);
  if (!w)                   /* Check if window opened */
    return(NO_WINDOW);
  w->flag = TRUE;           /* Set hidden flag        */
  wn_update();              /* Update all windows     */
  return(TRUE);
}
void wn_init (void)
Definition at line 876 of file window.c.
References _cursvar, COLOR, Fortify_ListAllMemory, set_display_colors(), start_screen, startcol, startrow, wn_exit(), and wn_log().
Referenced by initialize().
{
  /*------------------
    Initializations
  ------------------*/
  wn_log("wn_init()\n");
  atexit(wn_exit);
  /*-----------------------------------------------------------------
     Initializes global variables _NormAttr, _TextAttr, _LastMode,
     _CurCrtSize, _CheckSnow, _DirectVideo, _WindMin and _WindMax.
  -----------------------------------------------------------------*/
  initscr();
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
  /*-----------------------------
    Get original cursor position
  --------------------------------*/
  v_getcurpos(&startrow,&startcol);
  v_cursoroff();
  set_display_colors(COLOR);
  /*---------------------
    Open the top window
  ----------------------*/
  start_screen = v_savescreen(_cursvar.cols,_cursvar.lines);
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
  clrscr();
}
int wn_move (WINDOW * w, int row, int col)
Definition at line 260 of file window.c.
References _cursvar, minmax, NO_WINDOW, wcb::title, wn_log(), wn_log_indent(), wn_restore(), wn_update(), wcb::wx1, wcb::wx2, wcb::wy1, wcb::wy2, wcb::x1, wcb::x2, wcb::y1, and wcb::y2.
{
  int dx = 0;
  int dy = 0;
  wn_log("wn_move(%p,%s,%2d,%2d)\n",w,w->title,row,col);
  wn_log_indent(+2);
  /*--------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*--------------------------
    Check parameters
  --------------------------*/
  row = minmax(0,row,_cursvar.lines);
  col = minmax(0,col,_cursvar.cols);
  /*----------------------------------------------
    Calculate in which direction we have to move
  -----------------------------------------------*/
  if (row > w->wy1) dy=1; else dy=-1 ;
  if (col > w->wx1) dx=1; else dx=-1 ;
  /*---------------------------------
    Move the window over the screen
  -----------------------------------*/
  do {
    /* Update column pointers */
    if (((dx>0 && w->wx2<_cursvar.cols) || (dx<0 && w->wx1 > 0)) && w->wx1 != col) {
      w->wx1 += dx;
      w->wx2 += dx;
      w->x1  += dx;
      w->x2  += dx;
    }
    /* Update row pointers */
    if (((dy>0 && w->wy2 < _cursvar.lines) || (dy<0 && w->wy1 > 0)) && w->wy1 != row) {
      w->wy1 += dy;
      w->wy2 += dy;
      w->y1  += dy;
      w->y2  += dy;
    }
    wn_restore(w);
    wn_update();
    wn_log("target row=%2d, target col=%2d\n",row,col);
    wn_log("moved to (%02d,%02d)\n",w->wx1, w->wy1);
  }
  while ((w->wx1 != col) || (w->wy1 != row));
  wn_log_indent(-2);
  wn_log("end of wn_move()\n");
  return(0);
}
int wn_nattrib (WINDOW * w, int wcolor)
Definition at line 519 of file window.c.
References NO_WINDOW, TRUE, wcb::wcolor, wn_top(), wcb::x1, wcb::xsize, wcb::y1, and wcb::ysize.
{
  /*----------------------------------
    Check if window opened and topped
  -----------------------------------*/
  if (!w)
    return(NO_WINDOW);
  if (w != top_window)
    wn_top(w);
  w->wcolor = wcolor;     /* Save attribute */
  v_setattrib_area(w->y1, w->x1, w->xsize, w->ysize, wcolor);
  return(TRUE);
}
WINDOW* wn_open (int btype, int row, int col, int xsize, int ysize, int wcolor, int bcolor)
Definition at line 667 of file window.c.
References _cursvar, _NO_BORDER, add_wn_list(), wcb::bcolor, wcb::btype, wcb::ccx, wcb::ccy, FALSE, minmax, monitor, wcb::monitor, wcb::page, wcb::scrnsave, wcb::scroll_ok, wcb::synflg, wcb::title, TRUE, w, wcb::wcolor, wn_border(), wn_clear(), wn_log(), wn_save(), wn_shadow(), wcb::wx1, wcb::wx2, wcb::wy1, wcb::wy2, wcb::x1, wcb::x2, wcb::xsize, wcb::y1, wcb::y2, and wcb::ysize.
Referenced by call_hexconv(), call_terminal(), call_zapload(), disp_funkeys(), editstr(), get_dir(), help(), OS_shell(), overlap_demo(), popup(), show_bar(), wn_debug(), wn_dialog(), and wn_shell().
{
  WINDOWPTR w;
  /*----------------------------------
    Reserve memory for the window
  -----------------------------------*/
  w = (WINDOWPTR) calloc(sizeof(WINDOW),1);
  if (!w) {
    fprintf(stderr,"Not enough memory to open window\n");
    exit(1);
  }
  wn_log("wn_open() %p: (%2d,%2d) w=%2d h=%2d\n",w,row,col,xsize,ysize);
  /*------------------
    Check parameters
  -------------------*/
  if (btype == _NO_BORDER) {
    wn_log("wn_open(1) NO_BORDER\n");
    /*---------------------------------------
      Window has no border
    ---------------------------------------*/
    ysize  = minmax(0,ysize,_cursvar.lines);
    xsize  = minmax(0,xsize,_cursvar.cols);
        wn_log("wn_open(2) xsize = %d   ysize = %d\n",xsize,ysize);
    row = minmax(0,row,_cursvar.lines);
    col = minmax(0,col,_cursvar.cols);
        wn_log("wn_open(3) row = %d   col = %d\n",row,col);
    if (row+ysize > _cursvar.lines)
      ysize = _cursvar.lines-row;
    if (col+xsize > _cursvar.cols)
      xsize = _cursvar.cols-col;
        wn_log("wn_open(4) xsize = %d   ysize = %d\n",xsize,ysize);
  }
  else {
    wn_log("wn_open() WITH BORDER");
    /*---------------------------------------
      Window has a border
    ---------------------------------------*/
    ysize  = minmax(0,ysize,_cursvar.lines);
    xsize  = minmax(0,xsize,_cursvar.cols);
        wn_log("wn_open() xsize = %d   ysize = %d\n",xsize,ysize);
    row = minmax(0,row,_cursvar.lines-4);
    col = minmax(0,col,_cursvar.cols-4);
        wn_log("wn_open() row = %d   col = %d\n",row,col);
    if (row+ysize > _cursvar.lines-2)
      ysize  = (_cursvar.lines-row);
    if (col+xsize > _cursvar.cols-2)
      xsize = _cursvar.cols-col;
        wn_log("wn_open() xsize = %d   ysize = %d\n",xsize,ysize);
  }
  /*---------------------------------------
    Save coordinates of complete window
  ---------------------------------------*/
  w->wx1 = col;
  w->wy1 = row;
  w->wx2 = w->wx1 + xsize - 1;
  w->wy2 = w->wy1 + ysize - 1;
  /*---------------------------------------
    Save coordinates of 'text' window
  ---------------------------------------*/
  if (btype == _NO_BORDER) {
    w->x1 = w->wx1;
    w->y1 = w->wy1;
    w->x2 = w->wx2;
    w->y2 = w->wy2;
  }
  else {   /* Window has a border */
    w->x1 = w->wx1 + 1;
    w->y1 = w->wy1 + 1;
    w->x2 = w->wx2 - 1;
    w->y2 = w->wy2 - 1;
  }
  wn_log("wn_open(5) (%d,%d) x2 = %d  y2=%d\n",w->x1,w->y1,w->x2,w->y2);
  /*-----------------------------------
    Save variables in window structure
  -------------------------------------*/
  w->btype     = btype;           /* Border type         */
  w->xsize     = xsize;
  w->ysize     = ysize;
  w->wcolor    = wcolor;
  w->bcolor    = bcolor;
  w->ccy       = row;            /* Initialize screen cursor row  */
  w->ccx       = col;            /* Initialize screen cursor col  */
  w->synflg    = FALSE;          /* Standard cursor off           */
  w->scroll_ok = TRUE;           /* Standard scrolling window     */
  w->scrnsave  = NULL;
  w->monitor   = monitor;
  w->title     = NULL;
  w->page      = 0;
  wn_log("Variables are initialized\n");
  /*---------------------------------------
    Save contents of current active window
    Add window to double linked list
  --------------------------------------*/
  if (top_window != NULL) {
    wn_save(top_window);
  }
  add_wn_list(w);
  top_window = w;
  /*--------------------------------
    Draw window border (if wanted)
  --------------------------------*/
  if (btype != _NO_BORDER)
  {
    wn_border(w,btype);
  }
  /*-----------------------
    Add the shadow effect
  ------------------------*/
  if ( btype != _NO_BORDER && shadow != FALSE)
    wn_shadow(w);
  /*------------------------------
    Clear the inside of the window
  --------------------------------*/
  wn_clear(w);
  return(w);
}
int wn_overlap (WINDOW * w1, WINDOW * w2)
Definition at line 959 of file window.c.
References FALSE, wcb::page, TRUE, wcb::x1, wcb::x2, wcb::y1, and wcb::y2.
{
  if (w1->page != w2->page)          /* If not in same page */
     return(FALSE);                  /* they can't overlap  */
  if (((w2->x1 >= w1->x1) && (w2->x1 <= w1->x2)) &&
     (((w2->y1 >= w1->y1) && (w2->y1 <= w1->y2)) ||
      ((w2->y2 >= w1->y1) && (w2->y2 <= w1->y2))))
          return(TRUE);
  if (((w2->x2 >= w1->x1) && (w2->x2 <= w1->x2)) &&
     (((w2->y1 >= w1->y1) && (w2->y1 <= w1->y2)) ||
      ((w2->y2 >= w1->y1) && (w2->y2 <= w1->y2))))
          return(TRUE);
  if (((w1->x1 >= w2->x1) && (w1->x2 <= w2->x2)) &&
     (((w1->y1 >= w2->y1) && (w1->y1 <= w2->y2)) ||
      ((w1->y2 >= w2->y1) && (w1->y2 <= w2->y2))))
          return(TRUE);
  if (((w1->y1 >= w2->y1) && (w1->y2 <= w2->y2)) &&
     (((w1->x1 >= w2->x1) && (w1->x1 <= w2->x2)) ||
      ((w1->x2 >= w2->x1) && (w1->x2 <= w2->x2))))
          return(TRUE);
  if ((w1->x1 > w2->x1 && w1->x2 < w2->x2) &&
      (w1->y1 > w2->y1 && w1->y2 < w2->y2))
          return(TRUE);
  return(FALSE);
}
void wn_restore (WINDOWPTR w)
Definition at line 327 of file window.c.
References wcb::hideflag, wcb::scrnsave, wcb::title, wn_fixcsr(), wn_log(), wcb::wx1, wcb::wx2, wcb::wy1, and wcb::wy2.
Referenced by show_bar(), wn_move(), wn_top(), and wn_update().
{
  wn_log("wn_restore(%p,%s) (%d,%d)-(%d,%d)\n",w,w->title,w->wx1,w->wy1,w->wx2,w->wy2);
  if (!w)             /* Check if window opened */
    return;
  if (w->hideflag)    /* Check if window not hidden */
    return;
  if (w->scrnsave)    /* Restore contents of window */
    v_puttext(w->wx1,w->wy1,w->wx2,w->wy2,w->scrnsave);
  wn_fixcsr(w);     /* Initialize cursor */
}
WINDOW* wn_save (WINDOWPTR w)
Definition at line 172 of file window.c.
References wcb::ccx, wcb::ccy, col, row, wcb::scrnsave, wcb::title, wn_log(), wcb::wx1, wcb::wx2, wcb::wy1, wcb::wy2, wcb::xsize, and wcb::ysize.
Referenced by show_bar(), wn_open(), wn_top(), and wn_update().
{
  int row,col;
  if (!w)              /* Check if window opened */
    return(NULL);
  wn_log("wn_save(%p,%s) (%d,%d)-(%d,%d) \n",w,w->title,w->wx1,w->wy1,w->wx2,w->wy2);
  /*---------------------------------------
    Allocate memory for saving window
    (inclusive border and shadow)
  ---------------------------------------*/
  if (!w->scrnsave) {
    w->scrnsave = (char *) calloc((w->xsize)*(w->ysize)*2,1);
    if (!w->scrnsave) {
      fprintf(stderr,"Not enough memory to save window\n");
      exit(1);
    }
  }
  /*---------------------------------------
    Save contents of the window
  ---------------------------------------*/
  v_gettext(w->wx1,w->wy1,w->wx2,w->wy2,w->scrnsave);
  /*-------------------------------
    Save cursor info of the window
  ---------------------------------*/
  v_getcurpos(&row,&col);
  w->ccy = row;
  w->ccx = col;
  return(w);        /* Return pointer to last saved window */
}
void wn_setattrib (WINDOW * w, int row1, int col1, int xsize, int ysize, int att)
Definition at line 475 of file window.c.
References wcb::x1, and wcb::y1.
Referenced by show_line().
{
  v_setattrib_area(w->y1+row1, w->x1+col1, xsize, ysize, att);
}
int wn_setone (WINDOW * w, int row, int col, int attrib)
Definition at line 493 of file window.c.
References NO_WINDOW, wcb::x1, and wcb::y1.
Referenced by disp_funkeys().
{
  /*----------------------------------
    Check if window opened and topped
  -----------------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*---------------------------
    Call the routine setone()
  ----------------------------*/
  v_setattrib(w->y1+row,w->x1+col,attrib);
  return(0);
}
int wn_sync (WINDOW * w, int flag)
Definition at line 404 of file window.c.
References NO_WINDOW, and wcb::synflg.
Referenced by editstr().
{
  /*------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  w->synflg = flag;
  return(flag);
}
int wn_top (WINDOW * w)
Definition at line 356 of file window.c.
References add_wn_list(), del_wn_list(), NO_WINDOW, wcb::title, TRUE, wn_fixcsr(), wn_log(), wn_restore(), and wn_save().
Referenced by wn_border(), wn_clear(), wn_close(), wn_locate(), wn_nattrib(), wn_printf(), wn_scroll(), and wn_title().
{
  if (!w)                    /* Check if the window is opened */
    return(NO_WINDOW);
  wn_log("wn_top(%p,%s)\n",w,w->title);
  if (w != last_window) {    /* If the window is not the last window */
    del_wn_list(w);          /* Of the double linked list, put it in */
    add_wn_list(w);          /* the last position */
  }
  if (w == top_window)       /* Check if window not already top window */
    wn_fixcsr(w);
  else
  {
    if (top_window != NULL)
      wn_save(top_window);   /* Save contents of active window */
    top_window = w;          /* Set pointer to top window */
    wn_restore(w);           /* Restore contents of new active window */
  }
  return(TRUE);
}
int wn_unhide (WINDOWPTR w)
Definition at line 240 of file window.c.
References wcb::hideflag, NO_WINDOW, wcb::title, TRUE, wn_log(), and wn_update().
Referenced by disp_funkeys(), and wn_dialog().
{
  wn_log("wn_unhide(%p,%s)\n",w,w->title);
  if (!w)                       /* Check if window opened */
    return(NO_WINDOW);
  w->hideflag = 0;              /* Reset hidden flag */
  wn_update();                  /* Update all windows */
  return(TRUE);
}
int wn_update (void)
Definition at line 102 of file window.c.
References wcb::flag, HIDDEN, wcb::next, TRUE, w, wn_log(), wn_log_indent(), wn_restore(), and wn_save().
Referenced by wn_close(), wn_hide(), wn_move(), and wn_unhide().
{
  WINDOW *w;
  wn_log("wn_update() START **** \n");
  wn_log_indent(+2);
  /*-------------------------------
    Save window currently active
  -------------------------------*/
  if (top_window)
    wn_save(top_window);
  /*---------------------------------------------
    Fill virtual screen with desktop attribute if
    no desktop saved
  ---------------------------------------------*/
  /*
  if (!wn_desktop(1))
    v_fillarea(0,0,_cursvar.cols,_cursvar.lines,' ',_desktop_att);
  */
  clrscr();
  /*------------------------------------
    Draw all windows on virtual screen
  -------------------------------------*/
  if (start_window != NULL) {
    w = start_window;
    while (w) {
      if (! (w->flag & HIDDEN))     /* Restore window if not hidden */
        wn_restore(w);
      w = w->next;
    }
  }
  wn_log_indent(-2);
  wn_log("wn_update() END ****\n");
  /*---------------------
    Return all OK flag
  ----------------------*/
  return(TRUE);
}
Variable Documentation
SCREEN _cursvar
WINDOW* last_window = NULL
Definition at line 48 of file window.c.
unsigned int non_ibm = 0x0001
Definition at line 50 of file window.c.
char* start_screen = NULL
Definition at line 45 of file window.c.
Referenced by wn_exit(), and wn_init().
WINDOW* start_window = NULL
Definition at line 47 of file window.c.
int startcol [static]
Definition at line 40 of file window.c.
int startrow [static]
Definition at line 39 of file window.c.
WINDOW* top_window = NULL
Definition at line 46 of file window.c.
Referenced by wn_border(), wn_clear(), wn_locate(), wn_printf(), wn_scroll(), and wn_title().