HVA-WIN: window.h File Reference
window.h File Reference
#include <stdio.h>
#include <mem.h>
#include <stdlib.h>
Data Structures
struct wcb
struct MENU
struct MENU_HEAD
Defines
#define FALSE 0
#define TRUE !FALSE
#define _IBM_CGA 0
#define _NONIBM_CGA 1
#define NO_WINDOW -1
#define ALLOC_ERR -2
#define AUTO_ROW -1
#define AUTO_COL -1
#define LAST_ROW -2
#define LAST_COL -2
#define BLACK 0
#define BLUE 1
#define GREEN 2
#define CYAN 3
#define RED 4
#define MAGENTA 5
#define BROWN 6
#define WHITE 7
#define DARKGRAY 8
#define LIGHTBLUE 9
#define LIGHTGREEN 10
#define LIGHTCYAN 11
#define LIGHTRED 12
#define LIGHTMAGENTA 13
#define YELLOW 14
#define INTENSE_WHITE 15
#define B4025 0
#define C4025 1
#define B8025 2
#define C8025 3
#define C320 4
#define B320 5
#define HIRES 6
#define MONO 7
#define COLOR 15
#define MONITOR_1 1
#define MONITOR_2 2
#define _NO_BORDER 0
#define _SINGLE_LINE 1
#define _DOUBLE_LINE 2
#define FRAME_0 10
#define FRAME_1 11
#define FRAME_2 12
#define FRAME_3 13
#define FRAME_4 14
#define FRAME_5 15
#define FRAME_6 16
#define FRAME_7 17
#define FRAME_8 18
#define FRAME_9 19
#define FRAME_10 20
#define FRAME_11 21
#define _DRAW 1
#define _NO_DRAW 0
#define _UP 0
#define _DOWN 1
#define _LEFT 2
#define _RIGHT 3
#define _UPA 4
#define _DOWNA 5
#define _LEFTA 6
#define _RIGHTA 7
#define BYTE unsigned char
#define FP_OFF(fptr) ((unsigned)(fptr))
#define FP_SEG(fptr) ((unsigned)((unsigned long)(fptr) >> 16))
#define NO_FLAGS 0x0000
#define SELECTABLE 0x0001
#define DEFAULT 0x0002
#define EXIT 0x0004
#define EDITABLE 0x0008
#define RBUTTON 0x0010
#define LASTOB 0x0020
#define TOUCHEXIT 0x0040
#define HIDETREE 0x0080
#define INDIRECT 0x0100
#define SELECTED 0x0200
#define CROSSED 0x0400
#define CHECKED 0x0800
#define DISABLED 0x1000
#define EDIT_STR 0x2000
#define HELP_ONLY 0x4000
#define COMMENT 0x8000
#define HIDDEN 0x0001
#define SHADOW 0x0002
#define clearone(row, col, att) fillone(row,col,' ',att1)
#define clearwindow(r1, c1, r2, c2, att) fillwindow(r1,c1,r2,c2,' ',att)
#define max(a, b) (((a) > (b)) ? (a) : (b))
#define min(a, b) (((a) < (b)) ? (a) : (b))
#define minmax(a, b, c) (max((a),((min((b),(c))))))
Typedefs
typedef struct wcb WINDOW
typedef struct wcb * WINDOWPTR
typedef int(* PFI)(void)
Functions
void printchar (int row, int col, char c)
void setattrib (int row1, int col1, int xsize, int ysize, int att)
void savewindow (int col1, int row1, int col2, int row2, char *videoarray)
int gettext (int row1, int col1, int row2, int col2, void *array)
int puttext (int row1, int col1, int row2, int col2, void *array)
void disp_status (char *format,...)
void set_display_colors (int mode)
char * void_sprintf (char *datastr, char *format, void *data)
void void_sscanf (char *str, char *format, void *data)
void trimstr (char *s)
void vb_scroll (int left, int right, int top, int bottom, int amount)
void drawbox (int row, int col, int width, int height, int attrib)
void printhotcenter (int row, int col, char *string, int str_att)
void hotstring (int row, int col, int hotchar, char *s, int str_att)
void setup_menu (MENU *menu, int i, char *header, int hotkey, void *function, char *help, void *data, char *format, int flags)
void init_menu (MENU *menu, int n)
void printcenter (int row, int col, char *s)
void edit_data (int row, int col, char *header, char *format, void *data)
int editstr (int row, int tcol, int len, char *header, char *str, int w_flag)
void show_time (void)
int wn_desktop (int mode)
int wn_top (WINDOW *w)
void wn_init (void)
void wn_exit (void)
int wn_monitor (int monitor_nr)
int wn_update (void)
int wn_border (WINDOW *w, int style)
int wn_clear (WINDOW *w)
int wn_fixcsr (WINDOW *w)
void wn_restore (WINDOW *w)
int wn_hide (WINDOW *w)
int wn_unhide (WINDOW *w)
int wn_move (WINDOW *w, int row, int col)
int wn_show (WINDOW *w)
int wn_printf (WINDOW *w, char *format,...)
int wn_debug (char *format,...)
int wn_title (WINDOW *w, char *format,...)
void wn_setbox (int border_linestyle)
void wn_dma (int flag)
int wn_locate (WINDOW *w, int row, int col)
int wn_sync (WINDOW *w, int flag)
WINDOW * wn_close (WINDOW *w)
int wn_closeall (void)
void wn_fill (WINDOW *w, int row, int col, int width, int height, int c, int att)
void wn_setattrib (WINDOW *w, int row, int col, int xsize, int ysize, int att)
int wn_setone (WINDOW *w, int row, int col, int attrib)
int wn_nattrib (WINDOW *w, int wattrib)
int wn_scroll (WINDOW *w, int i)
int wn_shadow (WINDOW *w)
WINDOW * wn_open (int page, int row, int col, int width, int height, int attrib, int battrib)
WINDOW * wn_save (WINDOW *w)
void wn_error (char *format,...)
int wn_yesno (char *format,...)
void OS_shell (void)
void wn_shell (char *command)
void wn_log (char *format,...)
int wn_log_indent (int i)
int wn_dialog (int, int, int, MENU *, int,...)
void do_action (MENU *menu, int i)
unsigned int popup (int, MENU *, int, int)
void pulldown_bar (MENU_HEAD *menu)
int pulldown (MENU_HEAD *m, int i, char *help_subject)
void exit_pulldown (void)
void show_dir (void)
void change_dir (void)
char * get_dir (char *path, char *filename)
void init_funkey (int function_key, void *function, char *text)
void exit_funkey (void)
int do_funkey (int function_key)
void disp_funkeys (int i)
int help (char *subject)
int init_help (char *help_file_name)
void exit_help (void)
Variables
unsigned char NormAttr
unsigned char TextAttr
unsigned int LastMode
unsigned int CurCrtSize
unsigned char CheckSnow
unsigned char DirectVideo
unsigned int WindMin
unsigned int WindMax
char * start_screen
WINDOW * top_window
WINDOW * start_window
WINDOW * last_window
int _menu_att
int _menu_hotkey
int _menu_highlight
int _window_att
int _border_att
int _error_att
int _disabled_att
int _comment_att
int _dialog_att
int _desktop_att
int _help_text
int _help_bold
int _help_border
int _help_topiclink
int _help_linkselect
int display_mode
char display_mode_str []
unsigned int action_row
unsigned int action_col
int mon1_color
int mon2_color
int monitor
int direct_screen
Define Documentation
#define _DOUBLE_LINE 2
Definition at line 87 of file window.h.
Referenced by overlap_demo(), wn_debug(), wn_dialog(), and wn_setbox().
#define _DOWN 1
Definition at line 130 of file window.h.
#define _DOWNA 5
Definition at line 134 of file window.h.
#define _DRAW 1
Definition at line 126 of file window.h.
Referenced by change_dir(), do_action(), do_dir(), edit_data(), and show_dir().
#define _IBM_CGA 0
Definition at line 29 of file window.h.
#define _LEFT 2
Definition at line 131 of file window.h.
#define _LEFTA 6
Definition at line 135 of file window.h.
#define _NO_BORDER 0
Definition at line 85 of file window.h.
Referenced by call_hexconv(), call_terminal(), call_zapload(), disp_funkeys(), editstr(), OS_shell(), overlap_demo(), show_bar(), wn_border(), wn_open(), wn_shell(), and wn_title().
#define _NO_DRAW 0
Definition at line 127 of file window.h.
#define _NONIBM_CGA 1
Definition at line 30 of file window.h.
#define _RIGHT 3
Definition at line 132 of file window.h.
#define _RIGHTA 7
Definition at line 136 of file window.h.
#define _SINGLE_LINE 1
Definition at line 86 of file window.h.
Referenced by editstr(), get_dir(), help(), overlap_demo(), popup(), wn_dialog(), and wn_setbox().
#define _UP 0
Definition at line 129 of file window.h.
#define _UPA 4
Definition at line 133 of file window.h.
#define ALLOC_ERR -2
Definition at line 36 of file window.h.
#define AUTO_COL -1
Definition at line 39 of file window.h.
Referenced by popup().
#define AUTO_ROW -1
Definition at line 38 of file window.h.
Referenced by popup().
#define B320 5
Definition at line 71 of file window.h.
#define B4025 0
Definition at line 66 of file window.h.
#define B8025 2
Definition at line 68 of file window.h.
#define BLACK 0
Definition at line 46 of file window.h.
Referenced by call_hexconv(), call_terminal(), call_zapload(), OS_shell(), set_display_colors(), and wn_debug().
#define BLUE 1
Definition at line 47 of file window.h.
Referenced by overlap_demo(), and set_display_colors().
#define BROWN 6
Definition at line 52 of file window.h.
#define BYTE unsigned char
Definition at line 139 of file window.h.
#define C320 4
Definition at line 70 of file window.h.
#define C4025 1
Definition at line 67 of file window.h.
#define C8025 3
Definition at line 69 of file window.h.
#define CHECKED 0x0800
Definition at line 167 of file window.h.
#define clearone (row, col, att) fillone(row,col,' ',att1)
Definition at line 251 of file window.h.
#define clearwindow (r1, c1, r2, c2, att) fillwindow(r1,c1,r2,c2,' ',att)
Definition at line 252 of file window.h.
#define COLOR 15
Definition at line 74 of file window.h.
Referenced by set_display_colors(), and wn_init().
#define COMMENT 0x8000
Definition at line 171 of file window.h.
Referenced by popup().
#define CROSSED 0x0400
Definition at line 166 of file window.h.
#define CYAN 3
Definition at line 49 of file window.h.
Referenced by overlap_demo().
#define DARKGRAY 8
Definition at line 54 of file window.h.
#define DEFAULT 0x0002
Definition at line 157 of file window.h.
#define DISABLED 0x1000
Definition at line 168 of file window.h.
Referenced by popup().
#define EDIT_STR 0x2000
Definition at line 169 of file window.h.
Referenced by do_action().
#define EDITABLE 0x0008
Definition at line 159 of file window.h.
#define EXIT 0x0004
Definition at line 158 of file window.h.
Referenced by intro_screen(), popup(), wn_dialog(), wn_error(), and wn_yesno().
#define FALSE 0
Definition at line 25 of file window.h.
#define FP_OFF (fptr) ((unsigned)(fptr))
Definition at line 146 of file window.h.
#define FP_SEG (fptr) ((unsigned)((unsigned long)(fptr) >> 16))
Definition at line 149 of file window.h.
#define FRAME_0 10
Definition at line 108 of file window.h.
Referenced by wn_setbox().
#define FRAME_1 11
Definition at line 109 of file window.h.
Referenced by wn_setbox().
#define FRAME_10 20
Definition at line 118 of file window.h.
Referenced by wn_setbox().
#define FRAME_11 21
Definition at line 119 of file window.h.
Referenced by wn_setbox().
#define FRAME_2 12
Definition at line 110 of file window.h.
Referenced by wn_setbox().
#define FRAME_3 13
Definition at line 111 of file window.h.
Referenced by wn_setbox().
#define FRAME_4 14
Definition at line 112 of file window.h.
Referenced by wn_setbox().
#define FRAME_5 15
Definition at line 113 of file window.h.
Referenced by wn_setbox().
#define FRAME_6 16
Definition at line 114 of file window.h.
Referenced by wn_setbox().
#define FRAME_7 17
Definition at line 115 of file window.h.
Referenced by wn_setbox().
#define FRAME_8 18
Definition at line 116 of file window.h.
Referenced by wn_setbox().
#define FRAME_9 19
Definition at line 117 of file window.h.
Referenced by wn_setbox().
#define GREEN 2
Definition at line 48 of file window.h.
Referenced by overlap_demo().
#define HELP_ONLY 0x4000
Definition at line 170 of file window.h.
Referenced by do_action().
#define HIDDEN 0x0001
Definition at line 176 of file window.h.
Referenced by wn_update().
#define HIDETREE 0x0080
Definition at line 163 of file window.h.
#define HIRES 6
Definition at line 72 of file window.h.
#define INDIRECT 0x0100
Definition at line 164 of file window.h.
#define INTENSE_WHITE 15
Definition at line 61 of file window.h.
Referenced by set_display_colors().
#define LAST_COL -2
Definition at line 41 of file window.h.
#define LAST_ROW -2
Definition at line 40 of file window.h.
#define LASTOB 0x0020
Definition at line 161 of file window.h.
#define LIGHTBLUE 9
Definition at line 55 of file window.h.
#define LIGHTCYAN 11
Definition at line 57 of file window.h.
#define LIGHTGREEN 10
Definition at line 56 of file window.h.
#define LIGHTMAGENTA 13
Definition at line 59 of file window.h.
#define LIGHTRED 12
Definition at line 58 of file window.h.
#define MAGENTA 5
Definition at line 51 of file window.h.
#define max (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 255 of file window.h.
Referenced by display_line(), popup(), and wn_dialog().
#define min (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 258 of file window.h.
Referenced by check_screen(), and editstr().
#define minmax (a, b, c) (max((a),((min((b),(c))))))
Definition at line 261 of file window.h.
Referenced by display_line(), editstr(), wn_move(), and wn_open().
#define MONITOR_1 1
Definition at line 79 of file window.h.
#define MONITOR_2 2
Definition at line 80 of file window.h.
Referenced by wn_debug().
#define MONO 7
Definition at line 73 of file window.h.
Referenced by set_display_colors().
#define NO_FLAGS 0x0000
Definition at line 155 of file window.h.
#define NO_WINDOW -1
Definition at line 35 of file window.h.
Referenced by wn_border(), wn_clear(), wn_fixcsr(), wn_hide(), wn_locate(), wn_move(), wn_nattrib(), wn_printf(), wn_scroll(), wn_setone(), wn_sync(), wn_title(), wn_top(), and wn_unhide().
#define RBUTTON 0x0010
Definition at line 160 of file window.h.
#define RED 4
Definition at line 50 of file window.h.
Referenced by overlap_demo(), and set_display_colors().
#define SELECTABLE 0x0001
Definition at line 156 of file window.h.
Referenced by do_action().
#define SELECTED 0x0200
Definition at line 165 of file window.h.
#define SHADOW 0x0002
Definition at line 177 of file window.h.
#define TOUCHEXIT 0x0040
Definition at line 162 of file window.h.
#define TRUE !FALSE
Definition at line 26 of file window.h.
#define WHITE 7
Definition at line 53 of file window.h.
Referenced by call_hexconv(), call_terminal(), call_zapload(), OS_shell(), set_display_colors(), and wn_debug().
#define YELLOW 14
Definition at line 60 of file window.h.
Referenced by overlap_demo(), and set_display_colors().
Typedef Documentation
typedef int(* PFI)(void)
Definition at line 235 of file window.h.
typedef struct wcb WINDOW
typedef struct wcb * WINDOWPTR
Function Documentation
void change_dir (void)
Definition at line 93 of file dir.c.
References _DRAW, action_col, action_row, editstr(), ESC, and wn_error().
{
  char path[81];
  int  ret;
  if (getcwd(path,80) != NULL)
  {
    ret = editstr(action_row+2,action_col+2,30,"Enter directory path",path,_DRAW);
    if (ret != ESC)
      chdir(path);
  }
  else
    wn_error("Error in change_dir()");
}
void disp_funkeys (int i)
Definition at line 205 of file funkey.c.
References _cursvar, _menu_att, _menu_hotkey, _NO_BORDER, col, FALSE, row, show_funkeys, TRUE, wn_clear(), wn_hide(), wn_locate(), wn_log(), wn_open(), wn_printf(), wn_setone(), and wn_unhide().
{
  int j;
  int row,col;
  show_funkeys = TRUE;
  if (i<0 || i>4)
  {
    wn_log("wrong index %d in disp_funkeys\n",i);
    i = 1;
  }
  /*--------------------------------------
    Check if we have to open a window for
    the function keys, or if this window
    has already been opened.
    The window will occupy the last row on
    the screen with a full length
  ----------------------------------------*/
  if (!w)
  {
    wn_log("*** START FUNKEY\n");
    w = wn_open(_NO_BORDER,_cursvar.lines,0,_cursvar.cols+1,1,_menu_att,_menu_att);
    wn_clear(w);
  }
  /*------------------------------------------------
    Check if user wants to hide function key labels
    or to display it
  --------------------------------------------------*/
  if (i==0)
  {
    show_funkeys = FALSE;
    wn_hide(w);
    return;
  }
  else {
    if (show_funkeys == FALSE) {
      show_funkeys = TRUE;
      if (w)
        wn_unhide(w);
    }
  }
  /*-------------------------
    Print the function keys
  --------------------------*/
  row = 0;
  col = 0;
  for (j = 0 ; j<10 ; j++)
  {
    wn_locate(w,row,col);
    if (funkey[j].text) {
      wn_printf(w,"%1d%-6.6s",j+1,funkey[j].text);
      wn_setone(w,row,col,_menu_hotkey);
      if (j==9)
       wn_setone(w,row,col+1,_menu_hotkey);
    }
    col+=7;
  }
}
void disp_status (char * format, ...)
Definition at line 351 of file windio.c.
References _cursvar, len, and s.
{
  va_list arguments;
  static unsigned int i = 0;
  int len;
  char s[132];
  /*------------------------------------
    Generate the string
  -------------------------------------*/
  va_start(arguments,format);
  vsprintf(s,format,arguments);
  va_end(arguments);
  /*------------------
    Trim the string
  ------------------*/
  len = strlen(s);
  for (i=len ; i<_cursvar.cols ; i++)
    s[i] = ' ';
  s[_cursvar.cols] = '\0';
  /*-----------------------------------
    Print string on bottom of display
  ------------------------------------*/
  v_prints(_cursvar.lines,1,s);
}
void do_action (MENU * menu, int i)
Definition at line 49 of file popup.c.
References _DRAW, action_col, action_row, MENU::data, EDIT_STR, editstr(), FALSE, MENU::flags, help(), HELP_ONLY, s, SELECTABLE, TRUE, void_sprintf(), and void_sscanf().
Referenced by popup(), and wn_dialog().
{
  char datastr[80], *s;
  /*---------------------------------------
    Toggle a BOOLEAN value
  ---------------------------------------*/
  if (menu[i].flags & SELECTABLE) {
    if (menu[i].data == FALSE)
      menu[i].data = (void *) TRUE;
    else
      menu[i].data = (void *) FALSE;
    return;
  }
  /*---------------------------------------
    Edit a string
  ---------------------------------------*/
  if (menu[i].data != NULL
  && (menu[i].format != NULL)
  && (menu[i].flags & EDIT_STR)) {
    s = void_sprintf(datastr,menu[i].format,menu[i].data);
    if (s) {
      editstr(action_row+2,action_col+2,30,menu[i].header,datastr,_DRAW);
      void_sscanf(datastr,menu[i].format,menu[i].data);
      return;
    }
  }
  /*---------------------------------------
    Enter help functions if HELP_ONLY
  ---------------------------------------*/
  if (menu[i].flags & HELP_ONLY)
  {
    help(menu[i].help);
    return;
  }
  /*---------------------------------------------
    If a function was defined, perform function
  -----------------------------------------------*/
  if (menu[i].function != NULL)
  {
    (*(PFI)(menu[i].function))();
    return;
  }
}
int do_funkey (int function_key)
Definition at line 173 of file funkey.c.
References func_index(), is_fkey(), and wn_log().
Referenced by popup(), and pulldown().
{
  int ndx;
  wn_log("do_funkey(key=%2d)\n");
  if (is_fkey(key)) {
    ndx = func_index(key);                /* Find array index       */
    if (funkey[ndx].function) {           /* If function defined    */
      (*(PFI)(funkey[ndx].function))();   /* then execute function  */
      return(0);
    }
    else
      return(key);
  }
  else
    return(key);
}
void drawbox (int row, int col, int width, int height, int attrib)
void edit_data (int row, int col, char * header, char * format, void * data)
Definition at line 181 of file windio.c.
References _DRAW, editstr(), s, void_sprintf(), and void_sscanf().
{
  char s[80];
  void_sprintf(s,format,data);
  editstr(row,col,10,header,s,_DRAW);
  void_sscanf(s,format,data);
}
int editstr (int row, int tcol, int len, char * header, char * str, int w_flag)
Definition at line 61 of file editstr.c.
References _border_att, _cursvar, _NO_BORDER, _SINGLE_LINE, _window_att, action_col, action_row, ARROW_LEFT, ARROW_RIGHT, BACKSPACE, col, DELETE, display_line(), empty_str, END_LINE, ENTER, ESC, FALSE, HOME, LEFT_SHIFT, len, maxcol, min, minmax, pos, RETURN, RIGHT_SHIFT, row, s, shift_status(), sstart, startcol, startrow, TRUE, waitkey(), wn_close(), wn_fixcsr(), wn_open(), wn_sync(), and wn_title().
Referenced by change_dir(), do_action(), do_dir(), edit_data(), and show_dir().
{
  int c_flag = TRUE;     /* Cursor OFF flag              */
  int i;
  unsigned int key;      /* Scancode of key pressed      */
  int key_stat;          /* Key status                   */
  int firstkey = TRUE;   /* Flag for for first key press */
  /*----------------
    Save variables
  ----------------*/
  startrow = srow;
  startcol = scol;
  if (startrow == -1) startrow = action_row + 2;
  if (startcol == -1) startcol = action_col + 2;
  maxcol = startcol + l -1;  /* Maximum column position of cursor     */
  /* CHECK IF WINDOW WITHIN BOUNDARIES
  ------------------------------------*/
  startcol = minmax(0,startcol,_cursvar.cols-l);
  startrow = minmax(0,startrow,_cursvar.lines);
  /* DRAW THE EDIT WINDOW
  -----------------------*/
  if (w_flag)
  {
    /*-------------------------------------------------------
      l is the number of characters to display,
      but use l+2 to reserve space for the '<' and '>'
      931012 V0.7: add another 2 for xsize and ysize of window
                   to include borders
    ------------------------------------------------------*/
    w = wn_open(_SINGLE_LINE, startrow-1, startcol-1,
                l+4,3,_window_att,_border_att);
    wn_sync(w,TRUE);          /* Set cursor on flag      */
    wn_fixcsr(w);             /* Update cursor in window */
    wn_title(w,header);
  }
  else
    w = wn_open(_NO_BORDER, startrow, startcol, l+2, 1,
                _window_att,_border_att);
  /*-----------------------------
    Clear string s and empty_str
  ------------------------------*/
  memset(s,'\0',80);
  memset(empty_str,' ',l);
  empty_str[l] = '\0';
  /*---------------------
    Initialize variables
  ----------------------*/
  len = strlen(str);           /* Determine string length */
  strcpy(s,str);               /* Original str will be used with ESCaping */
  row = startrow;
  col = startcol;
  pos = len;                      /* Set character pointer after last char */
  col += pos;                     /* Set cursor column                     */
  display_line(l);
  /*-------------------------------------------------------------------
    After each process the following rules have to be true:
    - pos will point to the next position in the string to process.
    - col (cursorcolumn) on the screen will indicate the next position.
    - len is the actual lenght of the string
  ---------------------------------------------------------------------*/
  do
  {
    /* GET A KEY AND KEYBOARD STATUS
    --------------------------------*/
    key = waitkey();
    key_stat = shift_status();
    /* THREAT FIRST KEYPRESS SPECIAL
    --------------------------------*/
    if (firstkey)
    {
      firstkey = FALSE;
      if (isalnum(key))               /* Alpha numberic char ?  */
      {                               /* Start with new string  */
        v_prints(startrow,startcol,empty_str);
        s[0] = (char) key;            /* Store key in string    */
        for (i=1 ; i<80 ; i++)        /* Fill string with NIL's */
          s[i] = '\0';
        pos = 1;                      /* Reset string pointer   */
        col = startcol+1;             /* Reset column           */
        len = 1;                      /* Reset string length    */
        display_line(l);
        continue;
      }
    }
    switch (key) {
      case ARROW_LEFT:
        if (key_stat & (RIGHT_SHIFT|LEFT_SHIFT)) {
          col = startcol;
          pos = 0;          /* Put cursor on first character */
        }
        else {
          if (pos > 0)      /* Cursor one character to left  */
            pos--;
          if (!sstart)      /* If not truncated to left ...  */
            col--;
        }
        break;
/*    --------------  startcol 0 ; l 10 ; len 10 ; maxcol 10
      |<012345678_>|
      --------------
*/
      case ARROW_RIGHT:
        if (key_stat & (RIGHT_SHIFT|LEFT_SHIFT)) {
          pos = len;                 /* Cursor after last character     */
          col = min(startcol+len,maxcol);
        }
        else {                         /* Cursor 1 char to the right      */
          if (pos < len) {             /* Stop at end of string           */
            pos++;
            col++;
          }
        }
        break;
      case RETURN:
        strcpy(str,s);
        break;
      case BACKSPACE:     /* Delete character left of the cursor */
        if (pos > 0)
        { if (!sstart)             /* If no left-truncation      */
            col--;
          pos--;                   /* Generate new string        */
          strcpy(s+pos,s+pos+1);
          len--;                   /* Adjust length              */
          i = startcol+len+1;
          if (i <= maxcol)
            v_printc(row,i,' ');   /* Delete last char on screen */
        }
        break;
      case DELETE:                 /* Delete character under the cursor */
        if (s[pos] && pos >= 0)
        {
          len--;
          i = startcol+len;
          if (i <= maxcol)
            v_printc(row,i,' ');   /* Delete last char on screen */
          strcpy(s+pos,s+pos+1);   /* Generate new string        */
        }
        break;
      case HOME:         /* Cursor on first character */
        pos = 0;
        col = startcol;
        break;
      case END_LINE:     /* Cursor after last character  */
        pos = len;
        col = min(startcol+len,maxcol);
        break;
      default:
        if (isprint(key & 0x00FF))
        {
          for (i=len ; i>=pos ; i--)
            s[i] = s[i-1];
          s[pos] = (char) (key & 0x00FF);
          pos++;                 /* Adjust pointer           */
          len++;                 /* Adjust string length     */
          col++;
        }
    }
    display_line(l);
  }
  while (key != ENTER && key != ESC);
  /* DELETE TRAILING BLANKS
  -------------------------*/
  i = len - 1;
  while (isspace(s[i]) && i>=0)
  {
    s[i] = '\0';
    i--;
  }
  /* RESTORE CURSOR AND WINDOW
  ----------------------------*/
  if (!c_flag) v_cursoroff();
  if (w_flag)
    w = wn_close(w);
  return(key);
}
void exit_funkey (void)
Definition at line 275 of file funkey.c.
References wn_close(), and wn_log().
Referenced by wn_exit().
{
  if (w)
  {
    wn_log("*** END FUNKEY\n");
    w = wn_close(w);
  }
}
void exit_help (void)
Definition at line 1113 of file help.c.
References topic_key_buffer.
Referenced by init_help(), and wn_exit().
{
  free(topic_key_buffer);
}
void exit_pulldown (void)
Definition at line 348 of file pulldown.c.
References columns, hotkeys, and wn_log().
Referenced by wn_exit().
{
  wn_log("exit_pulldown()\n");
  if (hotkeys)
    free(hotkeys);
  if (columns)
    free((char *)columns);
}
char* get_dir (char * path, char * filename)
Definition at line 313 of file dir.c.
References _border_att, _menu_att, _SINGLE_LINE, action_col, action_row, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, ARROW_UP, display_dir(), ENTER, ESC_KEY, file, filenr, first_file, full_path, get_files(), MAX_FILES, MAX_NAME_LENGTH, NO_HOR_CELLS, original_dir, TRUE, waitkey(), window_height, window_width, wn_close(), wn_open(), and wn_title().
Referenced by do_dir(), and show_dir().
{
  int i;
  unsigned int  key = ESC_KEY;
  char *backslash;
  /*--------------------------------
    Allocate memory for file names
  ---------------------------------*/
  for (i=0 ; i<MAX_FILES ; i++)
    file[i] = (char *) malloc(MAX_NAME_LENGTH);
  /*------------------------
    Get current directory
  ------------------------*/
  getcwd(original_dir,80);
  get_files(mask);
  /*------------------------
    Open directory window
  ------------------------*/
  dir_window = wn_open(_SINGLE_LINE, action_row+2, action_col+2,
    window_width+2, window_height+2, _menu_att, _border_att);
  wn_title(dir_window,mask);
  /*--------------------------
    Initialize variables
  ---------------------------*/
  filenr = 0;
  first_file = 0;
  while (TRUE)
  {
    /*-----------------------------
      Display filenames in window
    ------------------------------*/
    display_dir();
    key = waitkey();
    switch(key)
    {
       case ARROW_RIGHT:
         filenr++;
         break;
       case ARROW_LEFT:
         filenr--;
         break;
       case ARROW_DOWN:
         filenr += NO_HOR_CELLS;
         break;
       case ARROW_UP:
         filenr -= NO_HOR_CELLS;
         break;
       case ESC_KEY:
         filename[0] = '\0';
         /*------------------------
           Free allocated memory
         ------------------------*/
         for (i=0 ; i<MAX_FILES ; i++)
           free(file[i]);
         chdir(original_dir);     /* Go back to original directory */
         dir_window = wn_close(dir_window);
         return(NULL);
         break;
       case ENTER:
         /*---------------------------------------------------
           Check if directory selected. If so, change to this
           directory, get filenames and show directory
         -----------------------------------------------------*/
         backslash = strchr(file[filenr],'\\');
         if (backslash)
         {
           *backslash = '\0';
           if (chdir(file[filenr]) != -1)
           {
             get_files(mask);
             first_file = 0;
             filenr = 0;
             display_dir();
           }
         }
         else
         {
           getcwd(full_path,80);
           strcat(full_path,"\\");
           /*----------------------------
             Check if filename selected
           ----------------------------*/
           if (isalnum(file[filenr][0]))
           {
             strcpy(filename,file[filenr]);
             strcat(full_path,filename);
           }
           /*------------------------
             Free allocated memory
           ------------------------*/
           for (i=0 ; i<MAX_FILES ; i++)
             free(file[i]);
           chdir(original_dir);     /* Go back to original directory */
           dir_window = wn_close(dir_window);
           return(full_path);
         }
         break;
      default:
        break;
    } /* end of switch() */
  } /* end of while() */
}
int gettext (int row1, int col1, int row2, int col2, void * array)
int help (char * subject)
Definition at line 288 of file help.c.
References _cursvar, _help_border, _help_text, _SINGLE_LINE, current_subject, default_subject, FALSE, height, HELP_LINE_LEN, initflg, KEY_LEN, link_key_buffer, MAX_LINES, MAXKEY, pop_subject(), show_topic(), subject, topic_txt, topic_txt_buffer, trimstr(), TRUE, wn_close(), wn_error(), wn_log(), wn_log_indent(), wn_open(), wcb::y1, and wcb::y2.
Referenced by do_action(), popup(), pulldown(), and wn_dialog().
{
  int i;                                  /* scratch integers */
  int  topic_found = FALSE;
  if (!initflg)
  {
    wn_error("HELP system not initialized");
    return(FALSE);
  }
  wn_log_indent(2);
  wn_log("HELP() START ****\n");
  /*------------------------------------------
    Allocate memory for topic text buffer
    and assign pointer to it.
  ------------------------------------------*/
  topic_txt_buffer = calloc(MAX_LINES,HELP_LINE_LEN);
  if (!topic_txt_buffer)
  {
    wn_error("ERROR in allocating TOPIC_TXT_BUFFER");
    return(FALSE);
  }
  for(i=0; i<MAX_LINES; i++) /* Assign pointers to each text line*/
    topic_txt[i] =  topic_txt_buffer + i*HELP_LINE_LEN;
  /*--------------------------------------------
  | allocate memory for topic link key buffer
  | and assign pointer to it.
  --------------------------------------------*/
  link_key_buffer = calloc(MAXKEY,KEY_LEN);
  if (!link_key_buffer)
  {
    wn_error("ERROR in allocating memory for LINK_KEY_BUFFER");
    return(FALSE);
  }
  for(i=0; i<MAXKEY; i++)
    topic_link[i].key =  link_key_buffer + i*KEY_LEN;
  /*--------------------------------
    Remove leading ':' from subject
  ----------------------------------*/
  if (in_subject && in_subject[0] == ':')
  {
    in_subject[0] = ' ';
    trimstr(in_subject);
  }
  /*--------------------------------------------------------
    If no in_subject given, set subject to default subject
  ---------------------------------------------------------*/
  if (in_subject == NULL || in_subject[0] == '\0')
  {
    if (default_subject)
      in_subject = default_subject;
    else {
      wn_error("No default subject given");
      return(FALSE);
    }
  }
  strcpy(current_subject,in_subject);
  subject = in_subject;
  wn = wn_open(_SINGLE_LINE,0,0,_cursvar.cols,_cursvar.lines,
               _help_text,_help_border);
  if (!wn)
    return(FALSE);
  height = (wn->y2 - wn->y1) + 1;
  while (TRUE)
  {
    /*----------------------------
      Check if a subject is given
    ------------------------------*/
    if (subject == NULL)
      break;
    /*-----------------------------
      Search for key in topic list
    -------------------------------*/
    i=0;
    topic_found = FALSE;
    while(i < MAXKEY)
    {
      trimstr(subject);
      trimstr(topic[i].key);
      if(!strcmp(subject,topic[i].key))
      {
        topic_found = TRUE;
        break;
      }
      else i++;
    }
    /*---------------------------------------
      If key was found, display text of topic
    -----------------------------------------*/
    if (topic_found)
    {
      show_topic(topic[i].loc);
    }
    else
    {
      /*---------------------------------------
        Show that topic text is not available
      ----------------------------------------*/
      wn_error("Sorry... No help available on subject %s",subject);
      /*-------------------------------------------------
        Retrieve last subject from stack. If no subject
        is available, then stop this loop
      -------------------------------------------------*/
      subject = pop_subject();
      if (subject)
      {
        strcpy(current_subject,subject);
        subject = current_subject;
      }
      else      /* No subjects available any more */
        break;
    }
  }
  /*--------------------
    Close help window
  ---------------------*/
  wn_close(wn);
  /*-------------------------------------
    Free allocated memory
  ---------------------------------------*/
  free(topic_txt_buffer);
  free(link_key_buffer);
  wn_log_indent(-2);
  wn_log("HELP() END *****\n");
  return(FALSE);
}
void hotstring (int row, int col, int hotchar, char * s, int str_att)
Definition at line 165 of file windio.c.
References _menu_hotkey, and wn_log().
Referenced by display_dir(), popup(), printhotcenter(), show_bar(), and wn_dialog().
{
  wn_log("hotstring() (%d,%d), hotkey='%d' <%s>\n",row,col,hotkey,string);
  v_prints(row,col,string);
  v_setattrib_area(row,col,strlen(string),1,str_att);
  if (hotkey > -1)
    v_setattrib(row,col+hotkey,_menu_hotkey);
}
void init_funkey (int function_key, void * function, char * text)
Definition at line 146 of file funkey.c.
References func_index(), FUNCTION_HANDLER::function, FUNCTION_HANDLER::text, and wn_log().
{
  int ndx;
  wn_log("init_funkey(key=%d,function=%p,text=%s\n",
    function_key, function, text);
  /*-------------------------------
    Initialize funkey[] variables
  ---------------------------------*/
  ndx = func_index(function_key);       /* Calculate index to array         */
  funkey[ndx].function = function;      /* Copy pointer to funkey function  */
  if (strlen(text) > 6) text[6] = '\0'; /* Check if text is not to long     */
  funkey[ndx].text     = text;          /* Copy pointer to funkey text      */
}
int init_help (char * help_file_name)
Definition at line 206 of file help.c.
References exit_help(), fp, HELP_LINE_LEN, initflg, KEY_LEN, TOPIC::loc, MAXKEY, topic_key_buffer, TRUE, and wn_error().
Referenced by initialize().
{
  int i;
  char tmpname[30];                   /* temporary filename */
  char *ptr;
  char line[HELP_LINE_LEN];           /* line buffer                     */
  if (initflg)
  {
    wn_error("Help system for %s already initialized",*help_file_name);
    return(initflg);
  }
  /*-----------------------------------------------
  | allocate memory for strings in topic key index
  | and allocate pointers to it.
  ------------------------------------------------*/
  topic_key_buffer = calloc(MAXKEY,KEY_LEN);
  if (!topic_key_buffer)
  {
    wn_error("ERROR in allocating TOPIC_KEY_BUFFER");
    return(initflg);
  }
  for(i=0; i<MAXKEY; i++)
    topic[i].key = topic_key_buffer + i*KEY_LEN;
  /*--------------------------------------------------
    Call exit_help when exiting from the main program
  ----------------------------------------------------*/
  atexit(exit_help);
  /*-----------------------------------------------------
  | Build the topic index table will be build by using
  | file 'subject.ndx'. After this the helpfile
  | 'subject.hlp' will be opened and left open to use
  -------------------------------------------------------*/
  strcpy(tmpname,help_file_name);   /* form filename from root */
  strcat(tmpname,".ndx");
  fp = fopen(tmpname,"r");
  if (!fp)                          /* index file cant be found ! */
  {
    wn_error("Can't find indexfile %s for help functions",tmpname);
    return(initflg);
  }
  i = 0;                                /* read and process key file */
  while(fgets(line,HELP_LINE_LEN,fp))   /* build the topic index table */
  {
    ptr = strchr(line,'\n');        /* Find '\n'        */
    if (ptr) *ptr = '\0';           /* And make it '\0' */
    strcpy(topic[i].key, line);
    #ifdef DONT_SKIP_THIS
    if(line[0] != ':')              /* ignore all but subjects */
      continue;
    #endif
    fgets(line,HELP_LINE_LEN,fp);
    topic[i].loc = atol(line);
    i++;
  }
  fclose(fp);                       /* close index file */
  strcpy(tmpname, help_file_name);  /* form help file name from root */
  strcat(tmpname, ".hlp");          /* open and leave open ! */
  fp = fopen(tmpname, "r");
  if (!fp)
    return(initflg);
  initflg = TRUE;
  return(initflg);
}
void init_menu (MENU * menu, int n)
Definition at line 54 of file windio.c.
References MENU::data, MENU::flags, MENU::format, MENU::function, MENU::header, MENU::help, and MENU::hotkey.
{
  int i;
  for (i=0 ; i<n ; i++)
  {
    menu[i].function = NULL;
    menu[i].format = "";
    menu[i].hotkey = -1;
    menu[i].header = "";
    menu[i].help = "";
    menu[i].flags = 0;
    menu[i].data  = NULL;
  }
}
void OS_shell (void)
Definition at line 19 of file wn_os.c.
References _cursvar, _NO_BORDER, BLACK, WHITE, wn_clear(), wn_close(), and wn_open().
{
  WINDOW *OS_window;
  OS_window = wn_open(_NO_BORDER,0,0,_cursvar.cols,_cursvar.lines,
                      16*BLACK+WHITE,16*BLACK+WHITE);
  wn_clear(OS_window);
  v_cursoron();
  printf("Return to simulation program with 'exit' ...\n\n");
  system(getenv("COMSPEC"));
  OS_window = wn_close(OS_window);
}
unsigned int popup (int , MENU * , int , int)
Definition at line 112 of file popup.c.
References _border_att, _comment_att, _disabled_att, _menu_att, _menu_highlight, _SINGLE_LINE, action_col, action_row, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, ARROW_UP, AUTO_COL, AUTO_ROW, COMMENT, DISABLED, do_action(), do_funkey(), ENTER, ESC, ESC_KEY, EXIT, F1, FALSE, MENU::header, help(), MENU::hotkey, hotstring(), is_fkey(), max, s, MENU::string, TRUE, void_sprintf(), waitkey(), wn_close(), wn_log(), wn_log_indent(), wn_open(), wcb::x1, and wcb::y1.
Referenced by pulldown().
{
  int i,mlen;
  unsigned int key = ARROW_DOWN;    /* Default key */
  WINDOW *popup_window;
  char datastr[132], *s;
  static int select = 0, old_select = 0;
  static MENU *oldmenu = NULL;
  static int autorow = FALSE;
  static int last_row = 0;
  static int autocol = FALSE;
  static int last_col = 0;
  wn_log("START POPUP()\n");
  wn_log_indent(+2);
  /*---------------------------------------
    Determine row
  ---------------------------------------*/
  if (row == AUTO_ROW) {
    if (!autorow) {
      row = action_row;
      last_row = action_row;
      autorow = TRUE;
    }
    else {
      row = last_row;
    }
  }
  else {
    autorow = FALSE;
    last_row = row;
  }
  /*---------------------------------------
    Determine column
  ---------------------------------------*/
  if (col == AUTO_COL) {
    if (!autocol) {
      col = action_col;
      last_col = action_col;
      autocol = TRUE;
    }
    else {
      col = last_col;
    }
  }
  else {
    autocol = FALSE;
    last_col = col;
  }
  /*---------------------------------------
    Fill menu strings with data
  ---------------------------------------*/
  for (i=0 ; i<number ; i++)
  {
    menu[i].string[0] = '\0';
    strcpy(menu[i].string,menu[i].header);  /* Copy 'header' to 'string' */
    s = void_sprintf(datastr,menu[i].format,menu[i].data);
    if (s)
    {
      strcat(menu[i].string,"  ");      /* Add blanks  */
      strcat(menu[i].string,datastr);   /* Add 'datastr' to 'string' */
    }
  }
  /*-----------------------------------
    Determine the maximum line length
  ------------------------------------*/
  mlen = 0;
  for (i=0 ; i<number ; i++)
    mlen = max(mlen,strlen(menu[i].string));
  /*------------------------------------------------------------
    Open the window and print the items
    12-Oct-1993 V0.7: Add 2 for xsize to include window borders
  -------------------------------------------------------------*/
  popup_window = wn_open(_SINGLE_LINE, row, col, mlen+2, number+2,
                    _menu_att, _border_att);
  row = popup_window->y1;
  col = popup_window->x1;
  wn_log("printing popup menu items:\n");
  for (i=0 ; i<number ; i++)
  {
    if (menu[i].flags & COMMENT)
      hotstring(row+i,col,-1,menu[i].string,_comment_att);
    else if (menu[i].flags & DISABLED)
      hotstring(row+i,col,-1,menu[i].string,_disabled_att);
    else
      hotstring(row+i,col,menu[i].hotkey,menu[i].string,_menu_att);
  }
  /*-------------------------------------------------------
    If it is the same menu as last time, we use the last
    selected item to highlight
  -------------------------------------------------------*/
  if (menu == oldmenu)
  {
    select = ++select % number;
    old_select = select;
  }
  else
  {
    select = 0;
    old_select = 0;
    oldmenu = menu;
  }
  while(TRUE)
  {
    /*-------------------------------------------------------------------
      Reset attribute of old selected line.
      Don't do this when the item is a COMMENT or when it is DISABLED
    --------------------------------------------------------------------*/
    if (!(menu[old_select].flags & (COMMENT|DISABLED))) {
      v_setattrib_area(row+old_select,col,mlen,1,_menu_att);
      hotstring(row+old_select,col,
        menu[old_select].hotkey,menu[old_select].string,_menu_att);
    }
    /*-------------------------------------------------------------------
      Set attribute of new selected line.
      Don't do this when the item is a COMMENT or when it is DISABLED
    --------------------------------------------------------------------*/
    if (!(menu[select].flags & (COMMENT|DISABLED))) {
      action_row = row+select;
      action_col = col;
      v_setattrib_area(action_row,action_col,mlen,1,_menu_highlight);
    }
    if (!(menu[select].flags & (COMMENT|DISABLED)))
      key = waitkey();            /*--- Scancode is returned here  */
    if (is_fkey(key)) {
      switch(key) {
        case F1:  help(menu[select].help); break;
        default:  do_funkey(key); break;
      }
    }
    /*-----------------------------------------------
      If hotkey defined, make this the new key value
    ------------------------------------------------*/
    switch(key) {
      case ENTER:
        if (menu[select].hotkey != -1)
          key = menu[select].header[menu[select].hotkey];
        break;
      default:
        break;
    }
    switch(key) {
      /*----------------------
      | Up- and down arrow
      -----------------------*/
      case ARROW_UP:
            wn_log("ARROW_UP\n");
        old_select = select;
        select = (--select+number) % number;
        break;
      case ARROW_DOWN:
            wn_log("ARROW_DOWN\n");
        old_select = select;
        select = ++select % number;
        break;
      /*--------------------------------------
      | No hotkey defined for this popup menu
      ----------------------------------------*/
      case ENTER:
            wn_log("ENTER\n");
        if (menu[select].flags & EXIT) {
          wn_log_indent(-2);
          wn_log("END POPUP()\n");
          popup_window = wn_close(popup_window);   /* Close it before actions */
        }
        do_action(menu,select);
        wn_log_indent(-2);
        wn_log("END POPUP()\n");
        popup_window = wn_close(popup_window);
        return(select);           /* Return number of selected item [0,...> */
      /*----------------------
      | Escape from popup()
      ----------------------*/
      case ESC_KEY:
      case ARROW_LEFT:
      case ARROW_RIGHT:
            wn_log("ESC or ARROW_LEFT or ARROW_RIGHT\n");
        wn_log_indent(-2);
        wn_log("END POPUP()\n");
        popup_window = wn_close(popup_window);
        return(key);
      default:
            wn_log("OTHER KEY\n");
                key = key & 0x00FF;
        if (key > 31 && key < 128) {
          for (i=0 ; i<number ; i++) {
            if (toupper(key) == toupper(menu[i].header[menu[i].hotkey])) {
              if (menu[i].flags & EXIT) {
                wn_log_indent(-2);
                wn_log("END POPUP()\n");
                popup_window = wn_close(popup_window);
              }
              do_action(menu,i);
              wn_log_indent(-2);
              wn_log("END POPUP()\n");
              popup_window = wn_close(popup_window);
              return(toupper(key));
            }
          }
        } /* if (key ...) */
    } /* switch(key) */
  } /* while (TRUE) */
  if (key == ENTER)
    return(select);
  else if (key == ESC_KEY)
    return(ESC);
  else
    return(toupper(key));
}
void printcenter (int row, int col, char * s)
Definition at line 139 of file windio.c.
Referenced by wn_dialog(), and wn_title().
{
  v_prints(row, col - (strlen(string) >> 1), string);
}
void printchar (int row, int col, char c)
void printhotcenter (int row, int col, char * string, int str_att)
Definition at line 152 of file windio.c.
References hotstring().
{
  hotstring(row, col - (strlen(string) >> 1), -1, string, str_att);
}
int pulldown (MENU_HEAD * m, int i, char * help_subject)
Definition at line 92 of file pulldown.c.
References _menu_att, ARROW_LEFT, ARROW_RIGHT, columns, do_funkey(), ESC_KEY, F1, FALSE, help(), hotkeys, is_fkey(), menu, MENU_HEAD::mptr, no_heads, popup(), pulldown_bar(), show_bar(), TRUE, waitkey(), wn_log(), and wn_log_indent().
Referenced by main().
{
  unsigned int  key;
  char c;
  int match = FALSE;
  unsigned int choise = 0;
  int i;
  wn_log_indent(2);
  wn_log("pulldown() MENU_HEAD=%p\n",shead);
  /* SHOW MENU HEADERS
  --------------------*/
  pulldown_bar(shead);
  /*----------------------------------------
     Use initial key or wait for a keypress
  -----------------------------------------*/
  wn_log("pulldown() - Waiting for first key press\n");
  if (ikey)
    key = ikey;
  else
    key = waitkey();
  wn_log("key pressed = %x\n",key);
  /*--- If function key, react on it  */
  if (is_fkey(key)) {
    wn_log("function key pressed\n");
    switch(key) {
      case F1:  help(menu_help); return(0); break;
      default:  do_funkey(key); break;
    }
  }
  /*--- If ESC key, return  */
  if (key == ESC_KEY)
    return(ESC_KEY);
  c = (char) (key & 0x00FF);
  wn_log("character = <%c>\n",c);
  /*----------------------------------------------
    Check if key matches with one of the hotkeys
  -----------------------------------------------*/
  for (i=0 ; i<strlen(hotkeys) ; i++) {
    if (c == hotkeys[i] || toupper(c) == hotkeys[i]) {
          wn_log("we have a hotkey match\n");
          match = TRUE;
          break;
        }
  }
  if (match == TRUE) {
    menu = i;
  }
  else {
    wn_log("no match found\n");
    return(key);
  }
  /* THERE IS A MATCH ...
  ----------------------*/
  v_cursoroff();
  while(TRUE)
  {
    mptr = head[menu].mptr;
        wn_log("mptr = %p\n",mptr);
    if (head[menu].number != 0)
      choise = popup(head[menu].number,mptr,1,columns[menu]);
    else
    {
          wn_log("pulldown() - check if a function is defined\n");
      /*---------------------------------------------
        If a function was defined, perform function
      -----------------------------------------------*/
      if (mptr[0].function != NULL) {
            wn_log("perform function \n");
        (*(PFI)(mptr[0].function))();
          }
    }
    wn_log("choise = %x\n",choise);
    switch(choise)
    {
      case ARROW_LEFT:
        v_setattrib_area(0, columns[menu], strlen(head[menu].header), 1, _menu_att);
        menu = (--menu + no_heads) % no_heads;
        show_bar();
        break;
      case ARROW_RIGHT:
        v_setattrib_area(0, columns[menu], strlen(head[menu].header), 1, _menu_att);
        menu = ++menu % no_heads;
        show_bar();
        break;
      default:
        break;
    } /* switch(choise) */
    if (choise == ESC_KEY)
      break;
  } /* while(TRUE) */
  show_bar();
  return(0);
}
void pulldown_bar (MENU_HEAD * menu)
Definition at line 301 of file pulldown.c.
References calc_pulldownbar(), MENU_HEAD::header, mem_pulldownbar(), no_heads, show_bar(), and wn_log().
Referenced by pulldown().
{
  MENU_HEAD *h;
  wn_log("pulldown_bar() MENU_HEAD=%p\n",shead);
  /*--------------------------------------
    If same menuline as last time, return
  ----------------------------------------*/
  if (cptr == shead)
    return;
  else
  {
    cptr = shead;
    head = shead;
  }
  /*-------------------------------
    Determine number of menu heads
    this must be done before calling
    mem_pulldownbar()
  ---------------------------------*/
  h = shead;
  while (h->header)
  {
    no_heads++;
    h++;
  }
  /*------------------------------
    Assign memory and
    Perform initial calculations
    Show the menu bar
  -------------------------------*/
  mem_pulldownbar();
  calc_pulldownbar(head);
  show_bar();
}
int puttext (int row1, int col1, int row2, int col2, void * array)
void savewindow (int col1, int row1, int col2, int row2, char * videoarray)
void set_display_colors (int mode)
Definition at line 79 of file windio.c.
References _border_att, _comment_att, _desktop_att, _dialog_att, _disabled_att, _error_att, _menu_att, _menu_highlight, _menu_hotkey, _window_att, BLACK, BLUE, COLOR, display_mode, display_mode_str, INTENSE_WHITE, MONO, RED, WHITE, and YELLOW.
Referenced by wn_init().
{
  switch(mode)
  {
    case MONO:
      display_mode = MONO;
      strcpy(display_mode_str,"MONO");
      _menu_att       = (16*BLACK+WHITE) & 0x7F;          /* memu item        */
      _menu_hotkey    = (16*BLACK+INTENSE_WHITE) & 0x7F;  /* hotkey of item   */
      _menu_highlight = (16*WHITE+BLACK) & 0x7F;          /* highlighted item */
      _window_att     = (16*BLACK+WHITE) & 0x7F;          /* window attribute */
      _border_att     = (16*BLACK+WHITE) & 0x7F;          /* border           */
      _error_att      = (16*BLACK+WHITE) & 0x7F;          /* Error window     */
      _disabled_att   = (16*BLACK+WHITE) & 0x7F;          /* DISABLED item    */
      _comment_att    = (16*BLACK+WHITE) & 0x7F;          /* COMMENT item     */
      _dialog_att     = (16*BLACK+WHITE) & 0x7F;          /* Dialog menu      */
      _desktop_att    = (16*BLACK+WHITE) & 0x7F;          /* Desktop attrib   */
      break;
    default:
      display_mode = COLOR;
      strcpy(display_mode_str,"COLOR");
      _menu_att       = (16*WHITE+BLACK) & 0x7F;      /* memu item        */
      _menu_hotkey    = (16*WHITE+RED)   & 0x7F;      /* hotkey of item   */
      _menu_highlight = (16*BLACK+WHITE) & 0x7F;      /* highlighted item */
      _window_att     = (16*BLACK+WHITE) & 0x7F;      /* window attribute */
      _border_att     = (16*WHITE+BLACK) & 0x7F;      /* border           */
      _error_att      = (16*RED+YELLOW)  & 0x7F;      /* Error window     */
      _disabled_att   = (16*WHITE+RED)   & 0x7F;      /* DISABLED item    */
      _comment_att    = (16*WHITE+BLUE)  & 0x7F;      /* COMMENT item     */
      _dialog_att     = (16*WHITE+BLACK) & 0x7F;      /* Dialog menu      */
      _desktop_att    = (16*BLUE+YELLOW) & 0x7F;      /* Desktop attr     */
      break;
  }
}
void setattrib (int row1, int col1, int xsize, int ysize, int att)
void setup_menu (MENU * menu, int i, char * header, int hotkey, void * function, char * help, void * data, char * format, int flags)
Definition at line 35 of file windio.c.
References MENU::data, MENU::flags, MENU::format, MENU::function, MENU::header, MENU::help, and MENU::hotkey.
{
  menu[i].header   = header;
  menu[i].hotkey   = hotkey;
  menu[i].function = function;
  menu[i].help     = help;
  menu[i].data     = data;
  menu[i].format   = format;
  menu[i].flags    = flags;
}
void show_dir (void)
Definition at line 73 of file dir.c.
References _DRAW, action_col, action_row, editstr(), ESC, and get_dir().
{
  char filemask[40];
  int ret;
  strcpy(filemask,"*.*");
  ret = editstr(action_row+2,action_col+2,30,"File mask",filemask,_DRAW);
  if (ret != ESC)
    get_dir(filemask,filemask);
}
void show_time (void)
Definition at line 387 of file windio.c.
References _cursvar.
{
  char timestr[9];
  time_t     tnow;
  struct tm  *tmnow;
  /*--------------------------
  | Get and print actual time
  ---------------------------*/
  time(&tnow);
  tmnow = localtime(&tnow);
  sprintf(timestr,"%02d:%02d:%02d",tmnow->tm_hour,tmnow->tm_min,tmnow->tm_sec);
  v_prints(0,_cursvar.cols-7,timestr);
}
void trimstr (char * s)
Definition at line 91 of file genindex.c.
References FALSE, len, and TRUE.
Referenced by help(), and main().
{
  int i;
  if (s == NULL)
    return(FALSE);
  i = strlen(s);
  if (i==0)
    return(TRUE);
  while (isspace(s[--i]))       /* Delete trailing blanks */
    s[i] = '\0';
  i = 0;                      /* Delete leading blanks */
  while (isspace(s[i]))
    i++;
  strcpy(s,s+i);
  return(TRUE);
}
void vb_scroll (int left, int right, int top, int bottom, int amount)
char* void_sprintf (char * datastr, char * format, void * data)
Definition at line 197 of file windio.c.
References FALSE, s, and TRUE.
{
  char *s;
  int long_format = FALSE;
  if (!format) /* || !data) */
    return(NULL);
  s = strchr(format,'%'); /* Check for format identifier   */
  if (!s)                 /* If no identifier, return NULL */
    return(NULL);
  s = strpbrk(format,"duouxXfegEGcsB");
  if (*(s-1) == 'l')
    long_format = TRUE;
  switch (*s)
  {
    case 'd':
    case 'i':
      if (long_format)
        sprintf(str,format, *((long *) data));
      else
        sprintf(str,format, *((unsigned int *) data));
      break;
    case 'o':
    case 'u':
    case 'x':
      sprintf(str,format, *((unsigned int *) data));
      break;
    case 'X':
      if (long_format)
        sprintf(str,format,*((unsigned long *) data));
      else
        sprintf(str,format, *((unsigned int *) data));
      break;
    case 'f':
    case 'e':
    case 'g':
    case 'E':
    case 'G':
      if (long_format)
        sprintf(str,format,*((double *)data));
      else
        sprintf(str,format, *((float *) data));
      break;
    case 'c':
      sprintf(str,format,*(char *)data);
      break;
    case 's':
      sprintf(str,format,(char *) data);
      break;
    case 'B':
      if ((int *)data)
        strcpy(str,"ON");
      else
        strcpy(str,"OFF");
      break;
    default:
      break;
  }
  return(str);
}
void void_sscanf (char * str, char * format, void * data)
Definition at line 269 of file windio.c.
References FALSE, s, and TRUE.
{
  char *s;
  char *dummy;
  int long_format = FALSE;
  s = strchr(format,'%'); /* Check for format identifier   */
  if (!s)                 /* If no identifier, return NULL */
    return;
  if (format == NULL)
    return;
  s = strpbrk(format,"duouxXfegEGcsB");
  if (*(s-1) == 'l')
    long_format = TRUE;
  switch (*s)
  {
    case 'd':
    case 'i':
      if (long_format)
        *(long *)data = atol(str);
      else
        *(int *)data = atoi(str);
      break;
    case 'o':
      *(unsigned int *)data = (unsigned int) strtol(str,&dummy,8);
      break;
    case 'O':
      *(long *)data = strtoul(str,&dummy,8);
      break;
    case 'u':
      *(unsigned int *)data = (unsigned int) strtoul(str,&dummy,10);
      break;
    case 'U':
      *(long *)data = strtoul(str,&dummy,10);
      break;
    case 'x':
      *(unsigned int *) data = (unsigned int) strtoul(str,&dummy,16);
      break;
    case 'X':
      *(long *) data = strtoul(str,&dummy,16);
      break;
    case 'f':
    case 'e':
    case 'g':
    case 'E':
    case 'G':
      if (long_format)
        *(double *)data = atof(str);
      else
        *(float *)data = (float) atof(str);
      break;
    case 'c':
      sscanf(str,"%c",(char *)data);
      break;
    case 's':
      strcpy((char *)data,str);
      break;
    default:
      break;
  }
}
int wn_border (WINDOW * w, int style)
Referenced by wn_open(), and wn_title().
int wn_clear (WINDOW * w)
Definition at line 25 of file wn_clear.c.
References NO_WINDOW, wcb::title, top_window, TRUE, wcb::wcolor, wn_locate(), wn_log(), wn_top(), wcb::x1, wcb::x2, wcb::y1, and wcb::y2.
Referenced by disp_funkeys(), OS_shell(), show_topic(), wn_open(), and wn_shell().
{
  int l,h;
  wn_log("wn_clear(%p,%s) (%d,%d) x2=%d  y2=%d\n",w,w->title,w->y1,w->x1,w->x2,w->y2);
  /*----------------------------------------
    Check if window opened and top window.
  -----------------------------------------*/
  if (!w)
    return(NO_WINDOW);
  if (w != top_window)
    wn_top(w);
  /*-----------------------------------------------------
    Clear window by filling in attribute and SPACE's and
    Put cursor in upper-right corner of window
  -------------------------------------------------------*/
  l = w->x2 - w->x1 + 1;
  h = w->y2 - w->y1 + 1;
  wn_log("l=%d   h=%d   color=%d   \n",l,h,w->wcolor);
  v_fillarea(w->y1,w->x1,l,h,' ',w->wcolor);
  wn_locate(w,0,0);
  return(TRUE);
}
WINDOW* wn_close (WINDOW * w)
Definition at line 821 of file window.c.
References del_wn_list(), wcb::scrnsave, wcb::title, wn_log(), wn_top(), and wn_update().
Referenced by call_hexconv(), call_terminal(), call_zapload(), editstr(), exit_funkey(), get_dir(), help(), OS_shell(), overlap_demo(), popup(), wn_closeall(), wn_dialog(), and wn_shell().
{
  wn_log("wn_close(%p,%s)\n",w,w->title);
  /*---------------------------
    Check if window was opened
  -----------------------------*/
  if (w) {
    /*-------------------------------------------
      Check if window to close is the top window
    ---------------------------------------------*/
    if (w == top_window) {
      top_window = NULL;
      last_window = NULL;
    }
    /*-----------------------------------------------
      Delete the window from the double linked list
      and free memory of window's save area and
      control block
    -------------------------------------------------*/
    del_wn_list(w);
    if (w->scrnsave)
      free(w->scrnsave);
    if (w->title)
      free(w->title);
    free((char *) w);
    /*-----------------------------------------------
      Make last window in linked list the top window
      and update the screen
    -------------------------------------------------*/
    wn_top(last_window);
    wn_update();
  }
  return(NULL);
}
int wn_closeall (void)
Definition at line 71 of file window.c.
References wcb::next, TRUE, w, and wn_close().
Referenced by wn_exit().
{
  WINDOW *w, *nextw;
  /*------------------
    Close all windows
  --------------------*/
  if (start_window != NULL) {
    w = start_window;
    while (w) {
      nextw = w->next;
      wn_close(w);
      w = nextw;
    }
  }
  return(TRUE);
}
int wn_debug (char * format, ...)
Definition at line 20 of file wn_debug.c.
References _cursvar, _DOUBLE_LINE, BLACK, FALSE, wcb::monitor, MONITOR_2, s, TRUE, WHITE, wn_monitor(), wn_open(), wn_printf(), and wn_title().
{
  va_list arguments;
  static int first_time = TRUE;
  static WINDOW *debug_window;
  int old_mon;
  char s[132];
  /*---------------------------
    Switch to second monitor
  ---------------------------*/
  old_mon = monitor;
  wn_monitor(MONITOR_2);
  if (first_time) {
    debug_window = wn_open(_DOUBLE_LINE,0,0,_cursvar.cols,_cursvar.lines,
                   16*BLACK+WHITE,16*BLACK+WHITE);
    if (!debug_window)
      exit(-1);
    wn_title(debug_window,"DEBUG OUTPUT");
    first_time = FALSE;
  }
  /*----------------------------
    Make this the active window
  ------------------------------*/
  /*
  if (debug_window != top_window)
    wn_top(debug_window);
  */
  /*-----------------------
    Build and print string
  ------------------------*/
  va_start(arguments,format);
  vsprintf(s,format,arguments);
  va_end(arguments);
  wn_printf(debug_window,"%s",s);
  /*-----------------------------
    Switch to original monitor
  -----------------------------*/
  wn_monitor(old_mon);
  return(TRUE);
}
int wn_desktop (int mode)
Definition at line 23 of file wn_desk.c.
References _cursvar, FALSE, and TRUE.
{
  static char *desktop = NULL;
  switch(mode) {
    case 0:               /* Save desktop                        */
      if (!desktop) {     /* Allocate memory if not already done */
        desktop = (unsigned char *) malloc(_cursvar.cols*_cursvar.lines*2);
        if (desktop == NULL) {
          fprintf(stderr,"ERROR: out of memory for saving desktop");
          exit(0);
        }
      }
      v_gettext(0,0,_cursvar.cols,_cursvar.lines,desktop);
      return(FALSE);
      break;
    case 1:                 /* Restore desktop if already saved */
      if (desktop) {
        v_puttext(0,0,_cursvar.cols,_cursvar.lines,desktop);
        return(TRUE);
      }
      return(FALSE);
      break;
  }
  return(FALSE);
}
int wn_dialog (int , int , int , MENU * , int , ...)
Definition at line 34 of file dialog.c.
References _DOUBLE_LINE, _SINGLE_LINE, ARROW_LEFT, ARROW_RIGHT, b_att, do_action(), ENTER, ESC, EXIT, F1, MENU::header, height, help(), MENU::hotkey, hotstring(), m_att, max, printcenter(), TRUE, waitkey(), wn_close(), wn_hide(), wn_log(), wn_log_indent(), wn_open(), wn_setbox(), and wn_unhide().
Referenced by intro_screen(), wn_error(), and wn_yesno().
{
  int     i,j,height,width=0,choiselen=0,titlelen=0;
  unsigned int key;
  int     choise_row;
  int     tabs[25],select;
  char    *titles[25];
  int     xsize;
  WINDOW  *window;
  va_list arg_marker;
  /*------------------------------------------
    Get the titles by va_start and calculate
    the width, needed for the titles. Store
    this value in 'titlelen'
  -------------------------------------------*/
  va_start(arg_marker,ntitles);
  for (i=0 ; i<ntitles ; i++)
  {
    titles[i] = va_arg(arg_marker,char *);
    titlelen = max(titlelen,strlen(titles[i]));
  }
  /*------------------------------------------------
    Calculate the width, needed for
    the options (choises). Store it in 'choiselen'
  -------------------------------------------------*/
  choiselen = nchoices - 1;
  for (i=0 ; i<nchoices ; i++)
    choiselen += (strlen(menu[i].header) + 2);
  width  =  max(titlelen,choiselen)+4;
  height =  ntitles + 6;
  row    =  row - height/2;
  choise_row = row + height - 4;
  wn_log("*** START DIALOG\n");
  wn_log_indent(+2);
  /*------------------------
    Open the dialog window
  -------------------------*/
  wn_log("open window");
  window = wn_open(_DOUBLE_LINE, row, col-width/2, width, height,m_att,b_att);
  /*---------------------------------------
    Print test of dialog menu (titles)
  ---------------------------------------*/
  wn_log("print titles");
  for (i=0 ; i<ntitles ; i++)
    printcenter(row+i+1, col, titles[i]);
  /*---------------------------------
    Draw the 'choise' boxes
    The default box is double lined
  ----------------------------------*/
  wn_log("print boxes");
  j = col - choiselen/2;
  for (i=0 ; i<nchoices ; i++)
  {
    tabs[i] = j-2;
    xsize = strlen(menu[i].header);
    if (!i)
    {
      wn_setbox(_DOUBLE_LINE);
      v_drawbox(choise_row, tabs[i], xsize+2, 3, m_att);
    }
    else
    {
      wn_setbox(_SINGLE_LINE);
      v_drawbox(choise_row, tabs[i], xsize+2, 3,  b_att);
    }
    v_setattrib_area(choise_row,   tabs[i]+1, xsize, 1, m_att);
    hotstring(choise_row+1, tabs[i]+1, menu[i].hotkey, menu[i].header, m_att);
    j += strlen(menu[i].header) + 5;
  }
  select = 0;
  while (TRUE)
  {
    key = waitkey();
    wn_log("key pressed = %d",key);
    /*-----------------------------------------------
      If hotkey defined, make this the new key value
    ------------------------------------------------*/
    switch(key)
    {
      case ENTER:
        if (menu[select].hotkey != -1)
          key = menu[select].header[menu[select].hotkey];
        break;
      default:
        break;
    }
    switch (key)
    {
      case ESC:
        {
          wn_setbox(_SINGLE_LINE);     /* Restore default */
          window = wn_close(window);
          wn_log_indent(-2);
          wn_log("*** END DIALOG\n");
          return(ESC);
        }
        break;
      case ARROW_LEFT:
        if (nchoices != 1)
        {
          wn_setbox(_SINGLE_LINE);
          v_drawbox(choise_row, tabs[select],
                  strlen(menu[select].header)+2, 3, b_att);
          select = (--select + nchoices) % nchoices;
          wn_setbox(_DOUBLE_LINE);
          v_drawbox(choise_row, tabs[select],
                  strlen(menu[select].header)+2, 3, m_att);
        }
        continue;
      case ARROW_RIGHT:
        if (nchoices != 1)
        {
          wn_setbox(_SINGLE_LINE);
          v_drawbox(choise_row, tabs[select],
                  strlen(menu[select].header)+2, 3, b_att);
          select = ++select % nchoices;
          wn_setbox(_DOUBLE_LINE);
          v_drawbox(choise_row, tabs[select],
                  strlen(menu[select].header)+2, 3, m_att);
        }
        continue;
      case F1:
        help(menu[select].help);
        continue;
      /*--------------------------------------
      | No hotkey defined for this popup menu
      ----------------------------------------*/
      case ENTER:
        wn_hide(window);       /* Hide it before actions */
        do_action(menu,select);
        if (menu[select].flags & EXIT)
        {
          window = wn_close(window);
          wn_log_indent(-2);
          wn_log("*** END DIALOG\n");
          return(select);
        }
        else
        {
          wn_unhide(window);
          continue;
        }
        break;
      /*--------------------
      | React on hotkey
      --------------------*/
      default:
        if (key > 31 && key < 128)
        {
          for (i=0 ; i<nchoices ; i++)
          {
            if (toupper(key) == toupper(menu[i].header[menu[i].hotkey]))
            {
              wn_hide(window);
              do_action(menu,i);
              if (menu[i].flags & EXIT)
              {
                window = wn_close(window);
                wn_log_indent(-2);
                wn_log("*** END DIALOG\n");
                return(toupper(key));
              }
              else
              {
                wn_unhide(window);
                wn_setbox(_SINGLE_LINE);    /* Restore default */
                break;
              }
            }
          }
        } /* for (i=0 ; ... */
    } /* switch(key) */
  } /* while (TRUE) */
  wn_setbox(_SINGLE_LINE);     /* Restore default */
  return(ESC);
}
void wn_dma (int flag)
Definition at line 389 of file window.c.
{
  flag++;
}
void wn_error (char * format, ...)
Definition at line 16 of file wn_error.c.
References _dialog_att, EXIT, MENU::flags, menu, s, wn_dialog(), wn_log(), and wn_log_indent().
Referenced by change_dir(), func_index(), help(), and init_help().
{
  va_list arguments;
  static MENU menu[] = {{"OK"}};
  int _tmp_att;
  char s[132];
  wn_log("BEGIN WN_ERROR()\n");
  wn_log_indent(+3);
  menu[0].flags |= EXIT;
  va_start(arguments,format);
  vsprintf(s,format,arguments);
  va_end(arguments);
  _tmp_att = _dialog_att;
  wn_dialog(13,40,1,menu,1,s);
  _dialog_att = _tmp_att;
  wn_log_indent(-3);
  wn_log("END WN_ERROR\n");
}
void wn_exit (void)
Definition at line 930 of file window.c.
References exit_funkey(), exit_help(), exit_pulldown(), FALSE, start_screen, startcol, startrow, TRUE, wn_closeall(), and wn_log().
Referenced by exit_prog(), and wn_init().
{
  static int done = FALSE;
  if (!done)               /* Do this only once */
  {
    wn_log("wn_exit()\n");
    exit_help();
    exit_pulldown();
    exit_funkey();
    wn_closeall();
    if (start_screen)
      start_screen = v_restorescreen(start_screen);
    v_setcurpos(startrow,startcol);
    v_cursoron();
    done = TRUE;        /* Set flag (this routine has been executed */
  }
}
void wn_fill (WINDOW * w, int row, int col, int width, int height, int c, int att)
Definition at line 462 of file window.c.
References wcb::x1, and wcb::y1.
Referenced by show_line(), and wn_scroll().
{
  v_fillarea(w->y1+row,w->x1+col,width,height,c,att);
}
int wn_fixcsr (WINDOW * w)
Definition at line 426 of file window.c.
References wcb::ccx, wcb::ccy, NO_WINDOW, wcb::synflg, and TRUE.
Referenced by editstr(), wn_restore(), and wn_top().
{
  /*------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*--------------------------------
    Check if this is the top window
  ----------------------------------*/
  if (w != top_window)
    return(NO_WINDOW);
  /*--------------------------------------
    Get physical cursor coordinates and
    show cursor (if wanted
  --------------------------------------*/
  v_setcurpos(w->ccy,w->ccx);
  if (w->synflg)
    v_cursoron();
  else
    v_cursoroff();
  return(TRUE);
}
int wn_hide (WINDOW * w)
void wn_init (void)
Definition at line 876 of file window.c.
References _cursvar, COLOR, Fortify_ListAllMemory, set_display_colors(), start_screen, startcol, startrow, wn_exit(), and wn_log().
Referenced by initialize().
{
  /*------------------
    Initializations
  ------------------*/
  wn_log("wn_init()\n");
  atexit(wn_exit);
  /*-----------------------------------------------------------------
     Initializes global variables _NormAttr, _TextAttr, _LastMode,
     _CurCrtSize, _CheckSnow, _DirectVideo, _WindMin and _WindMax.
  -----------------------------------------------------------------*/
  initscr();
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
  /*-----------------------------
    Get original cursor position
  --------------------------------*/
  v_getcurpos(&startrow,&startcol);
  v_cursoroff();
  set_display_colors(COLOR);
  /*---------------------
    Open the top window
  ----------------------*/
  start_screen = v_savescreen(_cursvar.cols,_cursvar.lines);
#if defined(USE_FORTIFY)
  Fortify_ListAllMemory();
  // Fortify_OutputStatistics();
#endif
  clrscr();
}
int wn_locate (WINDOW * w, int row, int col)
Definition at line 21 of file wn_loc.c.
References wcb::ccx, wcb::ccy, NO_WINDOW, wcb::synflg, top_window, TRUE, wn_top(), wcb::x1, wcb::x2, wcb::y1, and wcb::y2.
Referenced by disp_funkeys(), display_dir(), show_line(), and wn_clear().
{
  /*------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*------------------
    Activate window
  -------------------*/
  if (w!=top_window)
    wn_top(w);
  /*------------------------
    Check cursor position
  ------------------------*/
  if (row > w->y2)
    row = w->y2;
  if (col > w->x2)
    col = w->x2;
  if (row < 0)
    row = 0;
  if (col < 0)
    col = 0;
  /*------------------------------
    Set window cursor coordinates
  --------------------------------*/
  w->ccx = w->x1 + col;
  w->ccy = w->y1 + row;
  /*----------------------
    Set cursor in window
  -----------------------*/
  v_setcurpos(w->ccy,w->ccx);
  if (w->synflg)
    v_cursoron();
  else
    v_cursoroff();
  return(TRUE);
}
void wn_log (char * format, ...)
Definition at line 68 of file wn_log.c.
References fp, and indent_str.
Referenced by add_wn_list(), calc_pulldownbar(), del_wn_list(), disp_funkeys(), do_funkey(), exit_funkey(), exit_pulldown(), help(), hotstring(), init_funkey(), key_pressed(), level_wnds(), popup(), pulldown(), pulldown_bar(), show_bar(), show_topic(), waitkey(), wn_border(), wn_clear(), wn_close(), wn_dialog(), wn_error(), wn_exit(), wn_hide(), wn_init(), wn_move(), wn_open(), wn_printf(), wn_restore(), wn_save(), wn_scroll(), wn_title(), wn_top(), wn_unhide(), and wn_update().
{
  va_list arguments;
  static char *ep = NULL;     /* Points to environment var that names file */
  FILE *fp = NULL;
  if (ep == NULL                /* First time through, just create blank file */
  && (ep = getenv("WN_LOG"))
  && (fp = fopen(ep,"w")) ) {
    fclose(fp);
    fp = NULL;
    indent_str[0] = '\0';
  }
  if (ep)  {                     /* If we have a filename, proceed */
    fp = fopen(ep,"r+");
    if (!fp) {
      fprintf(stderr,"\nCannot open %s\n\a",ep);
      return;
    }
    else {
      va_start(arguments,format);       /* va_... housekeeping             */
      fseek(fp,0L,SEEK_END);            /* position pointer on end of file */
      fprintf(fp,"%s",indent_str);      /* place indentation               */
      vfprintf(fp,format,arguments);    /* print the log message           */
      fclose(fp);                       /* close the file                  */
    } va_end(arguments);                /* va_... housekeeping             */
  }
}
int wn_log_indent (int i)
Definition at line 28 of file wn_log.c.
References indent_len, and indent_str.
Referenced by help(), popup(), pulldown(), show_bar(), wn_dialog(), wn_error(), wn_move(), and wn_update().
{
 int i;
 /*----------------------------------
   Adjust number of spaces to indent
 -----------------------------------*/
 indent_len += adjust_len;
 /*-----------------------------------------------------
   Check on valid indent lenght: 0 <= indent_len <= 40
   return 0 if OK, -1 if not
 -----------------------------------------------------*/
 if (indent_len < 0)
   indent_len = 0;
 if (indent_len > 40)
   indent_len = 40;
 /*-----------------
   Set the string
 -----------------*/
 i = 0;
 while (i < indent_len)
   indent_str[i++] = 0x20;
 indent_str[i] = '\0';
 return(0);
}
int wn_monitor (int monitor_nr)
Referenced by wn_debug().
int wn_move (WINDOW * w, int row, int col)
Definition at line 260 of file window.c.
References _cursvar, minmax, NO_WINDOW, wcb::title, wn_log(), wn_log_indent(), wn_restore(), wn_update(), wcb::wx1, wcb::wx2, wcb::wy1, wcb::wy2, wcb::x1, wcb::x2, wcb::y1, and wcb::y2.
{
  int dx = 0;
  int dy = 0;
  wn_log("wn_move(%p,%s,%2d,%2d)\n",w,w->title,row,col);
  wn_log_indent(+2);
  /*--------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*--------------------------
    Check parameters
  --------------------------*/
  row = minmax(0,row,_cursvar.lines);
  col = minmax(0,col,_cursvar.cols);
  /*----------------------------------------------
    Calculate in which direction we have to move
  -----------------------------------------------*/
  if (row > w->wy1) dy=1; else dy=-1 ;
  if (col > w->wx1) dx=1; else dx=-1 ;
  /*---------------------------------
    Move the window over the screen
  -----------------------------------*/
  do {
    /* Update column pointers */
    if (((dx>0 && w->wx2<_cursvar.cols) || (dx<0 && w->wx1 > 0)) && w->wx1 != col) {
      w->wx1 += dx;
      w->wx2 += dx;
      w->x1  += dx;
      w->x2  += dx;
    }
    /* Update row pointers */
    if (((dy>0 && w->wy2 < _cursvar.lines) || (dy<0 && w->wy1 > 0)) && w->wy1 != row) {
      w->wy1 += dy;
      w->wy2 += dy;
      w->y1  += dy;
      w->y2  += dy;
    }
    wn_restore(w);
    wn_update();
    wn_log("target row=%2d, target col=%2d\n",row,col);
    wn_log("moved to (%02d,%02d)\n",w->wx1, w->wy1);
  }
  while ((w->wx1 != col) || (w->wy1 != row));
  wn_log_indent(-2);
  wn_log("end of wn_move()\n");
  return(0);
}
int wn_nattrib (WINDOW * w, int wattrib)
Definition at line 519 of file window.c.
References NO_WINDOW, TRUE, wcb::wcolor, wn_top(), wcb::x1, wcb::xsize, wcb::y1, and wcb::ysize.
{
  /*----------------------------------
    Check if window opened and topped
  -----------------------------------*/
  if (!w)
    return(NO_WINDOW);
  if (w != top_window)
    wn_top(w);
  w->wcolor = wcolor;     /* Save attribute */
  v_setattrib_area(w->y1, w->x1, w->xsize, w->ysize, wcolor);
  return(TRUE);
}
WINDOW* wn_open (int page, int row, int col, int width, int height, int attrib, int battrib)
Definition at line 667 of file window.c.
References _cursvar, _NO_BORDER, add_wn_list(), wcb::bcolor, wcb::btype, wcb::ccx, wcb::ccy, FALSE, minmax, monitor, wcb::monitor, wcb::page, wcb::scrnsave, wcb::scroll_ok, wcb::synflg, wcb::title, TRUE, w, wcb::wcolor, wn_border(), wn_clear(), wn_log(), wn_save(), wn_shadow(), wcb::wx1, wcb::wx2, wcb::wy1, wcb::wy2, wcb::x1, wcb::x2, wcb::xsize, wcb::y1, wcb::y2, and wcb::ysize.
Referenced by call_hexconv(), call_terminal(), call_zapload(), disp_funkeys(), editstr(), get_dir(), help(), OS_shell(), overlap_demo(), popup(), show_bar(), wn_debug(), wn_dialog(), and wn_shell().
{
  WINDOWPTR w;
  /*----------------------------------
    Reserve memory for the window
  -----------------------------------*/
  w = (WINDOWPTR) calloc(sizeof(WINDOW),1);
  if (!w) {
    fprintf(stderr,"Not enough memory to open window\n");
    exit(1);
  }
  wn_log("wn_open() %p: (%2d,%2d) w=%2d h=%2d\n",w,row,col,xsize,ysize);
  /*------------------
    Check parameters
  -------------------*/
  if (btype == _NO_BORDER) {
    wn_log("wn_open(1) NO_BORDER\n");
    /*---------------------------------------
      Window has no border
    ---------------------------------------*/
    ysize  = minmax(0,ysize,_cursvar.lines);
    xsize  = minmax(0,xsize,_cursvar.cols);
        wn_log("wn_open(2) xsize = %d   ysize = %d\n",xsize,ysize);
    row = minmax(0,row,_cursvar.lines);
    col = minmax(0,col,_cursvar.cols);
        wn_log("wn_open(3) row = %d   col = %d\n",row,col);
    if (row+ysize > _cursvar.lines)
      ysize = _cursvar.lines-row;
    if (col+xsize > _cursvar.cols)
      xsize = _cursvar.cols-col;
        wn_log("wn_open(4) xsize = %d   ysize = %d\n",xsize,ysize);
  }
  else {
    wn_log("wn_open() WITH BORDER");
    /*---------------------------------------
      Window has a border
    ---------------------------------------*/
    ysize  = minmax(0,ysize,_cursvar.lines);
    xsize  = minmax(0,xsize,_cursvar.cols);
        wn_log("wn_open() xsize = %d   ysize = %d\n",xsize,ysize);
    row = minmax(0,row,_cursvar.lines-4);
    col = minmax(0,col,_cursvar.cols-4);
        wn_log("wn_open() row = %d   col = %d\n",row,col);
    if (row+ysize > _cursvar.lines-2)
      ysize  = (_cursvar.lines-row);
    if (col+xsize > _cursvar.cols-2)
      xsize = _cursvar.cols-col;
        wn_log("wn_open() xsize = %d   ysize = %d\n",xsize,ysize);
  }
  /*---------------------------------------
    Save coordinates of complete window
  ---------------------------------------*/
  w->wx1 = col;
  w->wy1 = row;
  w->wx2 = w->wx1 + xsize - 1;
  w->wy2 = w->wy1 + ysize - 1;
  /*---------------------------------------
    Save coordinates of 'text' window
  ---------------------------------------*/
  if (btype == _NO_BORDER) {
    w->x1 = w->wx1;
    w->y1 = w->wy1;
    w->x2 = w->wx2;
    w->y2 = w->wy2;
  }
  else {   /* Window has a border */
    w->x1 = w->wx1 + 1;
    w->y1 = w->wy1 + 1;
    w->x2 = w->wx2 - 1;
    w->y2 = w->wy2 - 1;
  }
  wn_log("wn_open(5) (%d,%d) x2 = %d  y2=%d\n",w->x1,w->y1,w->x2,w->y2);
  /*-----------------------------------
    Save variables in window structure
  -------------------------------------*/
  w->btype     = btype;           /* Border type         */
  w->xsize     = xsize;
  w->ysize     = ysize;
  w->wcolor    = wcolor;
  w->bcolor    = bcolor;
  w->ccy       = row;            /* Initialize screen cursor row  */
  w->ccx       = col;            /* Initialize screen cursor col  */
  w->synflg    = FALSE;          /* Standard cursor off           */
  w->scroll_ok = TRUE;           /* Standard scrolling window     */
  w->scrnsave  = NULL;
  w->monitor   = monitor;
  w->title     = NULL;
  w->page      = 0;
  wn_log("Variables are initialized\n");
  /*---------------------------------------
    Save contents of current active window
    Add window to double linked list
  --------------------------------------*/
  if (top_window != NULL) {
    wn_save(top_window);
  }
  add_wn_list(w);
  top_window = w;
  /*--------------------------------
    Draw window border (if wanted)
  --------------------------------*/
  if (btype != _NO_BORDER)
  {
    wn_border(w,btype);
  }
  /*-----------------------
    Add the shadow effect
  ------------------------*/
  if ( btype != _NO_BORDER && shadow != FALSE)
    wn_shadow(w);
  /*------------------------------
    Clear the inside of the window
  --------------------------------*/
  wn_clear(w);
  return(w);
}
int wn_printf (WINDOW * w, char * format, ...)
Referenced by disp_funkeys(), overlap_demo(), show_line(), and wn_debug().
void wn_restore (WINDOW * w)
WINDOW* wn_save (WINDOW * w)
int wn_scroll (WINDOW * w, int i)
Definition at line 23 of file wn_scrol.c.
References NO_WINDOW, wcb::scroll_ok, wcb::title, top_window, wcb::wcolor, wn_fill(), wn_log(), wn_top(), wcb::x1, wcb::x2, wcb::xsize, wcb::y1, wcb::y2, and wcb::ysize.
Referenced by show_topic(), and wn_printf().
{
  char *ptr;
  int  xsize;
  int  ysize;
  wn_log("wn_scroll(window=%p,%s,lines=%1d)\n",w,w->title,i);
  /*---------------------------------------
    Check if scrolling has to be performed
  ---------------------------------------*/
  if (i == 0)
    return(-1);
  /*------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*---------------------------------------
    Check if scrolling is OK
  ---------------------------------------*/
  if (!w->scroll_ok)
    return(-2);
  /*-------------------------------------------------------------
    Check if this is the active (top) window. If not, make it so
  --------------------------------------------------------------*/
  if (w != top_window)
    wn_top(w);
  xsize = w->x2 - w->x1 + 1;
  ysize = w->y2 - w->y1 + 1;
  /*-------------------------------------------------------------
    Allocate enough memory for saving the contents of the window
  ---------------------------------------------------------------*/
  ptr = (char *) calloc(xsize*ysize*2,1);
  if (!ptr)
  {
    fprintf(stderr,"Not enough memory to save window\n");
    return(-3);
  }
  if (i > 0) {
    /*---------------------------------------
      SCROLL UP:
      Copy the part of the window to scroll
      Past the part in the window
      Clear the remainder
    ---------------------------------------*/
    v_gettext(w->x1,w->y1+i,w->x2 ,w->y2,  ptr);
    v_puttext(w->x1,w->y1,  w->x2 ,w->y2-i,ptr);
    wn_fill(w,ysize-1,0,xsize,1,' ',w->wcolor);
 }
  if ( i < 0) {
    /*---------------------------------------
      SCROLL DOWN:
      Copy the part of the window to scroll
      Past the part in the window
      Clear the remainder
    ---------------------------------------*/
    v_gettext(w->x1,w->y1,  w->x2, w->y2+i,ptr);  /* i is negative !!! */
    v_puttext(w->x1,w->y1-i,w->x2, w->y2  ,ptr);
    wn_fill(w,0,0,xsize,1,' ',w->wcolor);
  }
  free(ptr);
  /*--------------------------------
    Return status of scroll_ok flag
  ----------------------------------*/
  return(w->scroll_ok);
}
void wn_setattrib (WINDOW * w, int row, int col, int xsize, int ysize, int att)
Definition at line 475 of file window.c.
References wcb::x1, and wcb::y1.
Referenced by show_line().
{
  v_setattrib_area(w->y1+row1, w->x1+col1, xsize, ysize, att);
}
void wn_setbox (int border_linestyle)
Definition at line 102 of file wn_bord.c.
References _DOUBLE_LINE, _SINGLE_LINE, FRAME_0, FRAME_1, FRAME_10, FRAME_11, FRAME_2, FRAME_3, FRAME_4, FRAME_5, FRAME_6, FRAME_7, FRAME_8, and FRAME_9.
Referenced by wn_border(), and wn_dialog().
{
  switch (style) {
                    /* setboxchars( ul, to, ur, ri, lr, bo, ll, le); */
    case _SINGLE_LINE: v_setboxchars(218,196,191,179,217,196,192,179); break;
    case _DOUBLE_LINE: v_setboxchars(201,205,187,186,188,205,200,186); break;
    case FRAME_0     : v_setboxchars(218,196,191,179,217,196,192,179); break;
    case FRAME_1     : v_setboxchars(201,205,187,186,188,205,200,186); break;
    case FRAME_2     : v_setboxchars(214,196,183,186,189,196,211,186); break;
    case FRAME_3     : v_setboxchars(213,205,184,179,190,205,212,179); break;
    case FRAME_4     : v_setboxchars(213,205,184,179,217,196,192,179); break;
    case FRAME_5     : v_setboxchars( 32, 32, 32, 32, 32, 32, 32, 32); break;
    case FRAME_6     : v_setboxchars(220,220,220,222,223,223,223,221); break;
    case FRAME_7     : v_setboxchars(176,176,176,176,176,176,176,176); break;
    case FRAME_8     : v_setboxchars(177,177,177,177,177,177,177,177); break;
    case FRAME_9     : v_setboxchars(178,178,178,178,178,178,178,178); break;
    case FRAME_10    : v_setboxchars(219,219,219,219,219,219,219,219); break;
    case FRAME_11    : v_setboxchars('*','*','*','*','*','*','*','*'); break;
    default          : v_setboxchars(218,191,191,179,217,196,192,179); break;
  }
}
int wn_setone (WINDOW * w, int row, int col, int attrib)
Definition at line 493 of file window.c.
References NO_WINDOW, wcb::x1, and wcb::y1.
Referenced by disp_funkeys().
{
  /*----------------------------------
    Check if window opened and topped
  -----------------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*---------------------------
    Call the routine setone()
  ----------------------------*/
  v_setattrib(w->y1+row,w->x1+col,attrib);
  return(0);
}
int wn_shadow (WINDOW * w)
Definition at line 19 of file wn_shad.c.
References _cursvar, FALSE, SHADOWC, TRUE, wcb::wx1, wcb::wx2, wcb::wy1, wcb::wy2, wcb::xsize, and wcb::ysize.
Referenced by wn_open().
{
  #define SHADOWC 16*BLACK+DARKGRAY
  if (!w)           /* Check if window opened */
    return(FALSE);
  if(w->wx2 < _cursvar.cols && w->wy2 < _cursvar.lines) {   /* Check if shadow within screen */
    v_setattrib_area(w->wy2+1,w->wx1+1,w->xsize,1,SHADOWC);  /* bottom */
    v_setattrib_area(w->wy1+1,w->wx2+1,1,w->ysize,SHADOWC);  /* right  */
    return(TRUE);
  }
  else
    return(FALSE);
}
void wn_shell (char * command)
Definition at line 19 of file wn_shell.c.
References _cursvar, _desktop_att, _NO_BORDER, wn_clear(), wn_close(), and wn_open().
{
  WINDOW *OS_window;
  OS_window = wn_open(_NO_BORDER,0,0,_cursvar.cols,_cursvar.lines,
                      _desktop_att,_desktop_att);
  wn_clear(OS_window);
  v_cursoron();
  printf("Return to simulation program with 'exit' ...\n\n");
  /*  MUST USE SPAWN IN THE FUTURE */
  system(command);
  OS_window = wn_close(OS_window);
}
int wn_show (WINDOW * w)
int wn_sync (WINDOW * w, int flag)
Definition at line 404 of file window.c.
References NO_WINDOW, and wcb::synflg.
Referenced by editstr().
{
  /*------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  w->synflg = flag;
  return(flag);
}
int wn_title (WINDOW * w, char * format, ...)
Referenced by editstr(), get_dir(), and wn_debug().
int wn_top (WINDOW * w)
Definition at line 356 of file window.c.
References add_wn_list(), del_wn_list(), NO_WINDOW, wcb::title, TRUE, wn_fixcsr(), wn_log(), wn_restore(), and wn_save().
Referenced by wn_border(), wn_clear(), wn_close(), wn_locate(), wn_nattrib(), wn_printf(), wn_scroll(), and wn_title().
{
  if (!w)                    /* Check if the window is opened */
    return(NO_WINDOW);
  wn_log("wn_top(%p,%s)\n",w,w->title);
  if (w != last_window) {    /* If the window is not the last window */
    del_wn_list(w);          /* Of the double linked list, put it in */
    add_wn_list(w);          /* the last position */
  }
  if (w == top_window)       /* Check if window not already top window */
    wn_fixcsr(w);
  else
  {
    if (top_window != NULL)
      wn_save(top_window);   /* Save contents of active window */
    top_window = w;          /* Set pointer to top window */
    wn_restore(w);           /* Restore contents of new active window */
  }
  return(TRUE);
}
int wn_unhide (WINDOW * w)
int wn_update (void)
Definition at line 102 of file window.c.
References wcb::flag, HIDDEN, wcb::next, TRUE, w, wn_log(), wn_log_indent(), wn_restore(), and wn_save().
Referenced by wn_close(), wn_hide(), wn_move(), and wn_unhide().
{
  WINDOW *w;
  wn_log("wn_update() START **** \n");
  wn_log_indent(+2);
  /*-------------------------------
    Save window currently active
  -------------------------------*/
  if (top_window)
    wn_save(top_window);
  /*---------------------------------------------
    Fill virtual screen with desktop attribute if
    no desktop saved
  ---------------------------------------------*/
  /*
  if (!wn_desktop(1))
    v_fillarea(0,0,_cursvar.cols,_cursvar.lines,' ',_desktop_att);
  */
  clrscr();
  /*------------------------------------
    Draw all windows on virtual screen
  -------------------------------------*/
  if (start_window != NULL) {
    w = start_window;
    while (w) {
      if (! (w->flag & HIDDEN))     /* Restore window if not hidden */
        wn_restore(w);
      w = w->next;
    }
  }
  wn_log_indent(-2);
  wn_log("wn_update() END ****\n");
  /*---------------------
    Return all OK flag
  ----------------------*/
  return(TRUE);
}
int wn_yesno (char * format, ...)
Definition at line 17 of file wn_yesno.c.
References _dialog_att, ESC, EXIT, MENU::flags, menu, s, and wn_dialog().
{
  va_list arguments;
  int _tmp_att;
  char s[132];
  static MENU menu[] =
  {
    {"Yes", 0 },
    {"No",  0 },
    { NULL }
  };
  int choise = ESC;
  menu[0].flags |= EXIT;
  menu[1].flags |= EXIT;
  va_start(arguments,format);
  vsprintf(s,format,arguments);
  va_end(arguments);
  _tmp_att = _dialog_att;
  choise = wn_dialog(13,40,2,menu,1,s);
  _dialog_att = _tmp_att;
  return(choise);
}
Variable Documentation
int _border_att
Referenced by editstr(), get_dir(), popup(), and set_display_colors().
int _comment_att
Referenced by popup(), and set_display_colors().
int _desktop_att
Referenced by set_display_colors(), and wn_shell().
int _dialog_att
Referenced by set_display_colors(), wn_error(), and wn_yesno().
int _disabled_att
Referenced by popup(), and set_display_colors().
int _error_att
Referenced by set_display_colors().
int _help_bold
Referenced by show_line().
int _help_border
Referenced by help().
int _help_linkselect
Referenced by show_line().
int _help_text
Referenced by help(), and show_line().
int _help_topiclink
Referenced by show_line().
int _menu_att
Referenced by disp_funkeys(), display_dir(), get_dir(), popup(), pulldown(), set_display_colors(), and show_bar().
int _menu_highlight
Referenced by display_dir(), popup(), and set_display_colors().
int _menu_hotkey
Referenced by disp_funkeys(), hotstring(), and set_display_colors().
int _window_att
Referenced by editstr(), and set_display_colors().
unsigned int action_col
Referenced by change_dir(), do_action(), do_dir(), editstr(), get_dir(), popup(), and show_dir().
unsigned int action_row
Referenced by change_dir(), do_action(), do_dir(), editstr(), get_dir(), popup(), and show_dir().
unsigned char CheckSnow
unsigned int CurCrtSize
int direct_screen
unsigned char DirectVideo
int display_mode
Referenced by set_display_colors().
char display_mode_str[]
Referenced by set_display_colors().
WINDOW* last_window
Definition at line 48 of file window.c.
unsigned int LastMode
int mon1_color
int mon2_color
int monitor
Referenced by wn_open().
unsigned char NormAttr
char* start_screen
Definition at line 45 of file window.c.
Referenced by wn_exit(), and wn_init().
WINDOW* start_window
Definition at line 47 of file window.c.
unsigned char TextAttr
WINDOW* top_window
Definition at line 46 of file window.c.
Referenced by wn_border(), wn_clear(), wn_locate(), wn_printf(), wn_scroll(), and wn_title().
unsigned int WindMax
unsigned int WindMin