HVA-WIN: windio.c File Reference
windio.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <ctype.h>
#include <bios.h>
#include <dos.h>
#include <string.h>
#include <stdarg.h>
#include <time.h>
#include "video/v_video.h"
#include "window.h"
Functions
void setup_menu (MENU *menu, int i, char *header, int hotkey, void *function, char *help, void *data, char *format, int flags)
void init_menu (MENU *menu, int n)
void set_display_colors (int mode)
void printcenter (int row, int col, char *string)
void printhotcenter (int row, int col, char *string, int str_att)
void hotstring (int row, int col, int hotkey, char *string, int str_att)
void edit_data (int row, int col, char *header, char *format, void *data)
char * void_sprintf (char *str, char *format, void *data)
void void_sscanf (char *str, char *format, void *data)
void disp_status (char *format,...)
void show_time ()
Variables
SCREEN _cursvar
Function Documentation
void disp_status (char * format, ...)
Definition at line 351 of file windio.c.
References _cursvar, len, and s.
{
  va_list arguments;
  static unsigned int i = 0;
  int len;
  char s[132];
  /*------------------------------------
    Generate the string
  -------------------------------------*/
  va_start(arguments,format);
  vsprintf(s,format,arguments);
  va_end(arguments);
  /*------------------
    Trim the string
  ------------------*/
  len = strlen(s);
  for (i=len ; i<_cursvar.cols ; i++)
    s[i] = ' ';
  s[_cursvar.cols] = '\0';
  /*-----------------------------------
    Print string on bottom of display
  ------------------------------------*/
  v_prints(_cursvar.lines,1,s);
}
void edit_data (int row, int col, char * header, char * format, void * data)
Definition at line 181 of file windio.c.
References _DRAW, editstr(), s, void_sprintf(), and void_sscanf().
{
  char s[80];
  void_sprintf(s,format,data);
  editstr(row,col,10,header,s,_DRAW);
  void_sscanf(s,format,data);
}
void hotstring (int row, int col, int hotkey, char * string, int str_att)
Definition at line 165 of file windio.c.
References _menu_hotkey, and wn_log().
Referenced by display_dir(), popup(), printhotcenter(), show_bar(), and wn_dialog().
{
  wn_log("hotstring() (%d,%d), hotkey='%d' <%s>\n",row,col,hotkey,string);
  v_prints(row,col,string);
  v_setattrib_area(row,col,strlen(string),1,str_att);
  if (hotkey > -1)
    v_setattrib(row,col+hotkey,_menu_hotkey);
}
void init_menu (MENU * menu, int n)
Definition at line 54 of file windio.c.
References MENU::data, MENU::flags, MENU::format, MENU::function, MENU::header, MENU::help, and MENU::hotkey.
{
  int i;
  for (i=0 ; i<n ; i++)
  {
    menu[i].function = NULL;
    menu[i].format = "";
    menu[i].hotkey = -1;
    menu[i].header = "";
    menu[i].help = "";
    menu[i].flags = 0;
    menu[i].data  = NULL;
  }
}
void printcenter (int row, int col, char * string)
Definition at line 139 of file windio.c.
Referenced by wn_dialog(), and wn_title().
{
  v_prints(row, col - (strlen(string) >> 1), string);
}
void printhotcenter (int row, int col, char * string, int str_att)
Definition at line 152 of file windio.c.
References hotstring().
{
  hotstring(row, col - (strlen(string) >> 1), -1, string, str_att);
}
void set_display_colors (int mode)
Definition at line 79 of file windio.c.
References _border_att, _comment_att, _desktop_att, _dialog_att, _disabled_att, _error_att, _menu_att, _menu_highlight, _menu_hotkey, _window_att, BLACK, BLUE, COLOR, display_mode, display_mode_str, INTENSE_WHITE, MONO, RED, WHITE, and YELLOW.
Referenced by wn_init().
{
  switch(mode)
  {
    case MONO:
      display_mode = MONO;
      strcpy(display_mode_str,"MONO");
      _menu_att       = (16*BLACK+WHITE) & 0x7F;          /* memu item        */
      _menu_hotkey    = (16*BLACK+INTENSE_WHITE) & 0x7F;  /* hotkey of item   */
      _menu_highlight = (16*WHITE+BLACK) & 0x7F;          /* highlighted item */
      _window_att     = (16*BLACK+WHITE) & 0x7F;          /* window attribute */
      _border_att     = (16*BLACK+WHITE) & 0x7F;          /* border           */
      _error_att      = (16*BLACK+WHITE) & 0x7F;          /* Error window     */
      _disabled_att   = (16*BLACK+WHITE) & 0x7F;          /* DISABLED item    */
      _comment_att    = (16*BLACK+WHITE) & 0x7F;          /* COMMENT item     */
      _dialog_att     = (16*BLACK+WHITE) & 0x7F;          /* Dialog menu      */
      _desktop_att    = (16*BLACK+WHITE) & 0x7F;          /* Desktop attrib   */
      break;
    default:
      display_mode = COLOR;
      strcpy(display_mode_str,"COLOR");
      _menu_att       = (16*WHITE+BLACK) & 0x7F;      /* memu item        */
      _menu_hotkey    = (16*WHITE+RED)   & 0x7F;      /* hotkey of item   */
      _menu_highlight = (16*BLACK+WHITE) & 0x7F;      /* highlighted item */
      _window_att     = (16*BLACK+WHITE) & 0x7F;      /* window attribute */
      _border_att     = (16*WHITE+BLACK) & 0x7F;      /* border           */
      _error_att      = (16*RED+YELLOW)  & 0x7F;      /* Error window     */
      _disabled_att   = (16*WHITE+RED)   & 0x7F;      /* DISABLED item    */
      _comment_att    = (16*WHITE+BLUE)  & 0x7F;      /* COMMENT item     */
      _dialog_att     = (16*WHITE+BLACK) & 0x7F;      /* Dialog menu      */
      _desktop_att    = (16*BLUE+YELLOW) & 0x7F;      /* Desktop attr     */
      break;
  }
}
void setup_menu (MENU * menu, int i, char * header, int hotkey, void * function, char * help, void * data, char * format, int flags)
Definition at line 35 of file windio.c.
References MENU::data, MENU::flags, MENU::format, MENU::function, MENU::header, MENU::help, and MENU::hotkey.
{
  menu[i].header   = header;
  menu[i].hotkey   = hotkey;
  menu[i].function = function;
  menu[i].help     = help;
  menu[i].data     = data;
  menu[i].format   = format;
  menu[i].flags    = flags;
}
void show_time (void)
Definition at line 387 of file windio.c.
References _cursvar.
{
  char timestr[9];
  time_t     tnow;
  struct tm  *tmnow;
  /*--------------------------
  | Get and print actual time
  ---------------------------*/
  time(&tnow);
  tmnow = localtime(&tnow);
  sprintf(timestr,"%02d:%02d:%02d",tmnow->tm_hour,tmnow->tm_min,tmnow->tm_sec);
  v_prints(0,_cursvar.cols-7,timestr);
}
char* void_sprintf (char * str, char * format, void * data)
Definition at line 197 of file windio.c.
References FALSE, s, and TRUE.
Referenced by do_action(), edit_data(), and popup().
{
  char *s;
  int long_format = FALSE;
  if (!format) /* || !data) */
    return(NULL);
  s = strchr(format,'%'); /* Check for format identifier   */
  if (!s)                 /* If no identifier, return NULL */
    return(NULL);
  s = strpbrk(format,"duouxXfegEGcsB");
  if (*(s-1) == 'l')
    long_format = TRUE;
  switch (*s)
  {
    case 'd':
    case 'i':
      if (long_format)
        sprintf(str,format, *((long *) data));
      else
        sprintf(str,format, *((unsigned int *) data));
      break;
    case 'o':
    case 'u':
    case 'x':
      sprintf(str,format, *((unsigned int *) data));
      break;
    case 'X':
      if (long_format)
        sprintf(str,format,*((unsigned long *) data));
      else
        sprintf(str,format, *((unsigned int *) data));
      break;
    case 'f':
    case 'e':
    case 'g':
    case 'E':
    case 'G':
      if (long_format)
        sprintf(str,format,*((double *)data));
      else
        sprintf(str,format, *((float *) data));
      break;
    case 'c':
      sprintf(str,format,*(char *)data);
      break;
    case 's':
      sprintf(str,format,(char *) data);
      break;
    case 'B':
      if ((int *)data)
        strcpy(str,"ON");
      else
        strcpy(str,"OFF");
      break;
    default:
      break;
  }
  return(str);
}
void void_sscanf (char * str, char * format, void * data)
Definition at line 269 of file windio.c.
References FALSE, s, and TRUE.
Referenced by do_action(), and edit_data().
{
  char *s;
  char *dummy;
  int long_format = FALSE;
  s = strchr(format,'%'); /* Check for format identifier   */
  if (!s)                 /* If no identifier, return NULL */
    return;
  if (format == NULL)
    return;
  s = strpbrk(format,"duouxXfegEGcsB");
  if (*(s-1) == 'l')
    long_format = TRUE;
  switch (*s)
  {
    case 'd':
    case 'i':
      if (long_format)
        *(long *)data = atol(str);
      else
        *(int *)data = atoi(str);
      break;
    case 'o':
      *(unsigned int *)data = (unsigned int) strtol(str,&dummy,8);
      break;
    case 'O':
      *(long *)data = strtoul(str,&dummy,8);
      break;
    case 'u':
      *(unsigned int *)data = (unsigned int) strtoul(str,&dummy,10);
      break;
    case 'U':
      *(long *)data = strtoul(str,&dummy,10);
      break;
    case 'x':
      *(unsigned int *) data = (unsigned int) strtoul(str,&dummy,16);
      break;
    case 'X':
      *(long *) data = strtoul(str,&dummy,16);
      break;
    case 'f':
    case 'e':
    case 'g':
    case 'E':
    case 'G':
      if (long_format)
        *(double *)data = atof(str);
      else
        *(float *)data = (float) atof(str);
      break;
    case 'c':
      sscanf(str,"%c",(char *)data);
      break;
    case 's':
      strcpy((char *)data,str);
      break;
    default:
      break;
  }
}
Variable Documentation
SCREEN _cursvar