HVA-WIN: wn_error.c File Reference
wn_error.c File Reference
#include <stdarg.h>
#include "window.h"
Functions
void wn_error (char *format,...)
Function Documentation
void wn_error (char * format, ...)
Definition at line 16 of file wn_error.c.
References _dialog_att, EXIT, MENU::flags, menu, s, wn_dialog(), wn_log(), and wn_log_indent().
Referenced by change_dir(), func_index(), help(), and init_help().
{
  va_list arguments;
  static MENU menu[] = {{"OK"}};
  int _tmp_att;
  char s[132];
  wn_log("BEGIN WN_ERROR()\n");
  wn_log_indent(+3);
  menu[0].flags |= EXIT;
  va_start(arguments,format);
  vsprintf(s,format,arguments);
  va_end(arguments);
  _tmp_att = _dialog_att;
  wn_dialog(13,40,1,menu,1,s);
  _dialog_att = _tmp_att;
  wn_log_indent(-3);
  wn_log("END WN_ERROR\n");
}