HVA-WIN: wn_os.c File Reference
wn_os.c File Reference
#include "video/v_video.h"
#include "window.h"
Functions
void OS_shell ()
Variables
SCREEN _cursvar
Function Documentation
void OS_shell (void)
Definition at line 19 of file wn_os.c.
References _cursvar, _NO_BORDER, BLACK, WHITE, wn_clear(), wn_close(), and wn_open().
{
  WINDOW *OS_window;
  OS_window = wn_open(_NO_BORDER,0,0,_cursvar.cols,_cursvar.lines,
                      16*BLACK+WHITE,16*BLACK+WHITE);
  wn_clear(OS_window);
  v_cursoron();
  printf("Return to simulation program with 'exit' ...\n\n");
  system(getenv("COMSPEC"));
  OS_window = wn_close(OS_window);
}
Variable Documentation
SCREEN _cursvar