HVA-WIN: wn_debug.c File Reference
wn_debug.c File Reference
#include <stdarg.h>
#include "video/v_video.h"
#include "window.h"
Functions
int wn_debug (char *format,...)
Variables
SCREEN _cursvar
Function Documentation
int wn_debug (char * format, ...)
Definition at line 20 of file wn_debug.c.
References _cursvar, _DOUBLE_LINE, BLACK, FALSE, wcb::monitor, MONITOR_2, s, TRUE, WHITE, wn_monitor(), wn_open(), wn_printf(), and wn_title().
{
  va_list arguments;
  static int first_time = TRUE;
  static WINDOW *debug_window;
  int old_mon;
  char s[132];
  /*---------------------------
    Switch to second monitor
  ---------------------------*/
  old_mon = monitor;
  wn_monitor(MONITOR_2);
  if (first_time) {
    debug_window = wn_open(_DOUBLE_LINE,0,0,_cursvar.cols,_cursvar.lines,
                   16*BLACK+WHITE,16*BLACK+WHITE);
    if (!debug_window)
      exit(-1);
    wn_title(debug_window,"DEBUG OUTPUT");
    first_time = FALSE;
  }
  /*----------------------------
    Make this the active window
  ------------------------------*/
  /*
  if (debug_window != top_window)
    wn_top(debug_window);
  */
  /*-----------------------
    Build and print string
  ------------------------*/
  va_start(arguments,format);
  vsprintf(s,format,arguments);
  va_end(arguments);
  wn_printf(debug_window,"%s",s);
  /*-----------------------------
    Switch to original monitor
  -----------------------------*/
  wn_monitor(old_mon);
  return(TRUE);
}
Variable Documentation
SCREEN _cursvar