HVA-WIN: wn_loc.c File Reference
wn_loc.c File Reference
#include "video/v_video.h"
#include "window.h"
Functions
int wn_locate (WINDOW *w, int row, int col)
Function Documentation
int wn_locate (WINDOW * w, int row, int col)
Definition at line 21 of file wn_loc.c.
References wcb::ccx, wcb::ccy, NO_WINDOW, wcb::synflg, top_window, TRUE, wn_top(), wcb::x1, wcb::x2, wcb::y1, and wcb::y2.
Referenced by disp_funkeys(), display_dir(), show_line(), and wn_clear().
{
  /*------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*------------------
    Activate window
  -------------------*/
  if (w!=top_window)
    wn_top(w);
  /*------------------------
    Check cursor position
  ------------------------*/
  if (row > w->y2)
    row = w->y2;
  if (col > w->x2)
    col = w->x2;
  if (row < 0)
    row = 0;
  if (col < 0)
    col = 0;
  /*------------------------------
    Set window cursor coordinates
  --------------------------------*/
  w->ccx = w->x1 + col;
  w->ccy = w->y1 + row;
  /*----------------------
    Set cursor in window
  -----------------------*/
  v_setcurpos(w->ccy,w->ccx);
  if (w->synflg)
    v_cursoron();
  else
    v_cursoroff();
  return(TRUE);
}