HVA-WIN: wn_print.c File Reference
wn_print.c File Reference
#include <stdarg.h>
#include <string.h>
#include "video\v_video.h"
#include "window.h"
Functions
int wn_printf (WINDOWPTR w, char *format,...)
Function Documentation
int wn_printf (WINDOWPTR w, char * format, ...)
Definition at line 19 of file wn_print.c.
References wcb::ccx, wcb::ccy, col, len, NO_WINDOW, row, s, wcb::title, top_window, TRUE, wn_log(), wn_scroll(), wn_top(), wcb::x1, wcb::x2, and wcb::y2.
{
  va_list arguments;
  int i;
  int row,col;
  int len;
  char s[132];
  /*------------------------
    Check if window opened
  --------------------------*/
  if (!w)
    return(NO_WINDOW);
  /*----------------------------
    Make this the active window
  ------------------------------*/
  if (w != top_window)
    wn_top(w);
  /*-------------
    Build string
  ---------------*/
  va_start(arguments,format);
  vsprintf(s,format,arguments);
  va_end(arguments);
  /*------------------------------------------
    Print string in window with own routines
  -------------------------------------------*/
  i = 0;                      /* Reset counter */
  col = w->ccx;               /* Get window cursor coordinates   */
  row = w->ccy;
  len = strlen(s);
  wn_log("(%02d,%02d)/%-d wn_printf(%p,%s,'%s')\n",row,col,len,w,w->title,s);
  if (s[len-1] != '\n') wn_log("\n");
  while (s[i])
  {
    switch (s[i])
    {
      case 0x0A:     /* LF */
        col = w->x1;
        row++;
        break;
      case 0x0D:     /* CR */
        col = w->x1;
        break;
      case 0x09:     /* HT */
        col += 4;
        break;
      case 0x0B:     /* VT */
        row++;
        break;
      case 0x0C:     /* FF */
        row++;
        col = w->x1;
        break;
      case 0x08:     /* BS */
        if (col <= w->x1)
          col = w->x1;
        else
          col--;
        v_setcurpos(row,col);
        v_printc(row,col,' ');
        break;
      default:
        v_printc(row,col,s[i]);
        col++;
    }
    /*----------------------------------------------
      Test position of cursor row and column, and
      adjust these if neccessary
    -----------------------------------------------*/
    if (col > w->x2) {
      col = w->x1;
      row++;
    }
    if (row > w->y2) {
      wn_scroll(w,1);
      col = w->x1;
      row = w->y2;
    }
    i++;        /* point to next character */
  }
  /*------------------------------------------------
    Update cursor position in window control block
    and on screen
  -------------------------------------------------*/
  w->ccx = col;
  w->ccy = row;
  v_setcurpos(row,col);
  return(TRUE);
}