HVA-WIN: wn_log.c File Reference
wn_log.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include "window.h"
Functions
int wn_log_indent (int adjust_len)
void wn_log (char *format,...)
Variables
static int indent_len = 0
static char indent_str [80]
Function Documentation
void wn_log (char * format, ...)
Definition at line 68 of file wn_log.c.
References fp, and indent_str.
Referenced by add_wn_list(), calc_pulldownbar(), del_wn_list(), disp_funkeys(), do_funkey(), exit_funkey(), exit_pulldown(), help(), hotstring(), init_funkey(), key_pressed(), level_wnds(), popup(), pulldown(), pulldown_bar(), show_bar(), show_topic(), waitkey(), wn_border(), wn_clear(), wn_close(), wn_dialog(), wn_error(), wn_exit(), wn_hide(), wn_init(), wn_move(), wn_open(), wn_printf(), wn_restore(), wn_save(), wn_scroll(), wn_title(), wn_top(), wn_unhide(), and wn_update().
{
  va_list arguments;
  static char *ep = NULL;     /* Points to environment var that names file */
  FILE *fp = NULL;
  if (ep == NULL                /* First time through, just create blank file */
  && (ep = getenv("WN_LOG"))
  && (fp = fopen(ep,"w")) ) {
    fclose(fp);
    fp = NULL;
    indent_str[0] = '\0';
  }
  if (ep)  {                     /* If we have a filename, proceed */
    fp = fopen(ep,"r+");
    if (!fp) {
      fprintf(stderr,"\nCannot open %s\n\a",ep);
      return;
    }
    else {
      va_start(arguments,format);       /* va_... housekeeping             */
      fseek(fp,0L,SEEK_END);            /* position pointer on end of file */
      fprintf(fp,"%s",indent_str);      /* place indentation               */
      vfprintf(fp,format,arguments);    /* print the log message           */
      fclose(fp);                       /* close the file                  */
    } va_end(arguments);                /* va_... housekeeping             */
  }
}
int wn_log_indent (int adjust_len)
Definition at line 28 of file wn_log.c.
References indent_len, and indent_str.
Referenced by help(), popup(), pulldown(), show_bar(), wn_dialog(), wn_error(), wn_move(), and wn_update().
{
 int i;
 /*----------------------------------
   Adjust number of spaces to indent
 -----------------------------------*/
 indent_len += adjust_len;
 /*-----------------------------------------------------
   Check on valid indent lenght: 0 <= indent_len <= 40
   return 0 if OK, -1 if not
 -----------------------------------------------------*/
 if (indent_len < 0)
   indent_len = 0;
 if (indent_len > 40)
   indent_len = 40;
 /*-----------------
   Set the string
 -----------------*/
 i = 0;
 while (i < indent_len)
   indent_str[i++] = 0x20;
 indent_str[i] = '\0';
 return(0);
}
Variable Documentation
int indent_len = 0 [static]
Definition at line 16 of file wn_log.c.
Referenced by wn_log_indent().
char indent_str[80] [static]
Definition at line 17 of file wn_log.c.
Referenced by wn_log(), and wn_log_indent().