HVA-WIN: wn_clear.c File Reference
wn_clear.c File Reference
#include "video/v_video.h"
#include "window.h"
Functions
int wn_clear (WINDOW *w)
Function Documentation
int wn_clear (WINDOW * w)
Definition at line 25 of file wn_clear.c.
References NO_WINDOW, wcb::title, top_window, TRUE, wcb::wcolor, wn_locate(), wn_log(), wn_top(), wcb::x1, wcb::x2, wcb::y1, and wcb::y2.
Referenced by disp_funkeys(), OS_shell(), show_topic(), wn_open(), and wn_shell().
{
  int l,h;
  wn_log("wn_clear(%p,%s) (%d,%d) x2=%d  y2=%d\n",w,w->title,w->y1,w->x1,w->x2,w->y2);
  /*----------------------------------------
    Check if window opened and top window.
  -----------------------------------------*/
  if (!w)
    return(NO_WINDOW);
  if (w != top_window)
    wn_top(w);
  /*-----------------------------------------------------
    Clear window by filling in attribute and SPACE's and
    Put cursor in upper-right corner of window
  -------------------------------------------------------*/
  l = w->x2 - w->x1 + 1;
  h = w->y2 - w->y1 + 1;
  wn_log("l=%d   h=%d   color=%d   \n",l,h,w->wcolor);
  v_fillarea(w->y1,w->x1,l,h,' ',w->wcolor);
  wn_locate(w,0,0);
  return(TRUE);
}