HVA-WIN: wn_bord.c File Reference
wn_bord.c File Reference
#include "video/v_video.h"
#include "window.h"
Functions
int wn_border (WINDOWPTR w, int style)
void wn_setbox (int style)
Function Documentation
int wn_border (WINDOWPTR w, int style)
Definition at line 22 of file wn_bord.c.
References _NO_BORDER, wcb::bcolor, wcb::btype, FALSE, NO_WINDOW, wcb::title, top_window, TRUE, wn_log(), wn_setbox(), wn_top(), wcb::wx1, wcb::wy1, wcb::xsize, and wcb::ysize.
{
  wn_log("wn_border(%p,%s, style = %2d)\n",w,w->title,style);
  /*----------------------------------
    Check if window opened and topped
  -----------------------------------*/
  if (!w)
    return(NO_WINDOW);
  if (w != top_window)
    wn_top(w);
  if (w->btype != _NO_BORDER) {
    wn_setbox(style);
    v_drawbox(w->wy1,w->wx1,w->xsize,w->ysize,w->bcolor);
    return(TRUE);
  }
  else
    return(FALSE);
}
void wn_setbox (int style)
Definition at line 102 of file wn_bord.c.
References _DOUBLE_LINE, _SINGLE_LINE, FRAME_0, FRAME_1, FRAME_10, FRAME_11, FRAME_2, FRAME_3, FRAME_4, FRAME_5, FRAME_6, FRAME_7, FRAME_8, and FRAME_9.
Referenced by wn_border(), and wn_dialog().
{
  switch (style) {
                    /* setboxchars( ul, to, ur, ri, lr, bo, ll, le); */
    case _SINGLE_LINE: v_setboxchars(218,196,191,179,217,196,192,179); break;
    case _DOUBLE_LINE: v_setboxchars(201,205,187,186,188,205,200,186); break;
    case FRAME_0     : v_setboxchars(218,196,191,179,217,196,192,179); break;
    case FRAME_1     : v_setboxchars(201,205,187,186,188,205,200,186); break;
    case FRAME_2     : v_setboxchars(214,196,183,186,189,196,211,186); break;
    case FRAME_3     : v_setboxchars(213,205,184,179,190,205,212,179); break;
    case FRAME_4     : v_setboxchars(213,205,184,179,217,196,192,179); break;
    case FRAME_5     : v_setboxchars( 32, 32, 32, 32, 32, 32, 32, 32); break;
    case FRAME_6     : v_setboxchars(220,220,220,222,223,223,223,221); break;
    case FRAME_7     : v_setboxchars(176,176,176,176,176,176,176,176); break;
    case FRAME_8     : v_setboxchars(177,177,177,177,177,177,177,177); break;
    case FRAME_9     : v_setboxchars(178,178,178,178,178,178,178,178); break;
    case FRAME_10    : v_setboxchars(219,219,219,219,219,219,219,219); break;
    case FRAME_11    : v_setboxchars('*','*','*','*','*','*','*','*'); break;
    default          : v_setboxchars(218,191,191,179,217,196,192,179); break;
  }
}