HVA-WIN: wn_shell.c File Reference
wn_shell.c File Reference
#include <stdlib.h>
#include "video/v_video.h"
#include "window.h"
Functions
void wn_shell (char *command)
Variables
SCREEN _cursvar
Function Documentation
void wn_shell (char * command)
Definition at line 19 of file wn_shell.c.
References _cursvar, _desktop_att, _NO_BORDER, wn_clear(), wn_close(), and wn_open().
{
  WINDOW *OS_window;
  OS_window = wn_open(_NO_BORDER,0,0,_cursvar.cols,_cursvar.lines,
                      _desktop_att,_desktop_att);
  wn_clear(OS_window);
  v_cursoron();
  printf("Return to simulation program with 'exit' ...\n\n");
  /*  MUST USE SPAWN IN THE FUTURE */
  system(command);
  OS_window = wn_close(OS_window);
}
Variable Documentation
SCREEN _cursvar